### ISSUE TITLE
Cases vs Positives

### ISSUE THREAD

**Issue by HarryLeroy** [nychealth/coronavirus-data#102]
What accounts for the difference between Cases (in case-hosp-death.csv) and Positives (in tests.csv)? Are "Cases" only for new, unique positives? Do "Positives" include subsequent tests for those who have already tested positive?

Thank you,
Harry

**Comment by mmontesanonyc** [comment]
Yes, you are correct. Cases are unique individuals, and the diagnosis date is recorded as first time someone was positive for a diagnostic test (virus, or PCR, test). Positives in tests.csv refer to the number of people testing positive over time, and are unique to an individual and a day.

So, for example, if somebody tests positive for the first time on July 6th, they are recorded as having a diagnosis date on July 6th, and they would appear in Cases on that date. If they are given a follow-up test on July 10th and still test positive, they are not re-counted as a New Case, but they are counted as a positive test result on July 10th.
