### ISSUE TITLE
Cases, hospitalizations and deaths by age, for all days you have been running the survey

### ISSUE THREAD

**Issue by cipolla4eq** [nychealth/coronavirus-data#103]
Hi I am interested in the 1) cases, hospitalizations and deaths for confirmed (or probable) COVID 19 cases, by age groups, for every day you have been recording your data. Also 2) I would love to have information by age, and possibly by date too, of the death rates conditional on hospitalization. I understand 10 is available but perhaps not published, while 2) is hard. Anything you can help me with would be greatly appreciated. Thank you.

**Comment by mmontesanonyc** [comment]
Thanks for your inquiry. Unfortunately we're not able to accommodate all custom data requests.

**Comment by cipolla4eq** [comment]
> Thanks for your inquiry. Unfortunately we're not able to accommodate all custom data requests.

Thank you so much for your reply. Would it be possible to satisfy only one of the data requests, namely the deaths and hospitalizations, by age, for every day you run the data survey? I need the data for important research we are doing, in COVID 19 and more, and can't find it anywhere. Thank you for your help and time.
