### ISSUE TITLE
ERROR in case-hosp-death.csv for 7/18

### ISSUE THREAD

**Issue by fianchetto1** [nychealth/coronavirus-data#104]
_case-hosp-death.csv_ updated on 7/18 shows the cumulative case count for July 10 equal to 215. That's 16 cases LESS than the cumulative case count of 231 for the same date (July 10) reported in _case-hosp-death.csv_ updated on 7/17. Is there a typo in the version of _case-hosp-death.csv_ updated on 7/18? Correction of a previous error?

**Comment by mmontesanonyc** [comment]
Changes to values, including downward changes, don't necessarily reflect correction of errors, but rather, further improvements to what we know as we get more information. For example, case records may get updated with a different diagnosis date, which would mean +1 to the new date and -1 to the old date. Or, we may get additional information that allows us to ensure that patient records are de-duplicated, which can mean -1 to a date of diagnosis.
