### ISSUE TITLE
Non-proportional disparity between state dashboard hospitalizations and city hospital admissions

### ISSUE THREAD

**Issue by PhilMiller** [nychealth/coronavirus-data#106]
In `case-hosp-death.csv` there's a day-by-day count of absolute hospital admissions. At https://forward.ny.gov/covid-19-regional-metrics-dashboard the state gives a rolling average of per-capital hospital admissions. 

When I make the same computation of a rolling average of the per-capita admissions from the city data, the two curves don't actually line up - the computed values have had ratios ranging from 0.82 to a recent 1.84

https://docs.google.com/spreadsheets/d/1fk0fGWM44U8stHpYLz9kt_wmoNa4fnWNUaDzfJW-yPU/edit?usp=sharing

I'm trying to use hospital admissions as an estimation parameter for the number of active infections, independent of general testing data. I'm not sure what to make of the city and state persistently showing disparate numbers, when the descriptions as best as I can tell represent the same underlying activity.

**Comment by mmontesanonyc** [comment]
There are differences in how the State and City collect, process, analyze, and report data that results in different values for the same metrics. Unfortunately the State's portal does not provide documentation that clarifies how they are counting those hospitalizations and calculating those rates, so it's difficult to identify any single reason for the difference. We hope that our documentation helps answer some of those questions about how the City is producing those values.
