### ISSUE TITLE
July 22 data in case-hosp-death.csv

### ISSUE THREAD

**Issue by EdithB** [nychealth/coronavirus-data#107]
Is this a more limited update than the usual?  Hospitalization and death numbers are virtually unchanged since yesterday, and changes in reported cases are uncharacteristically small also.  Is this update based on a partial gathering of data for the day?

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. We had a data processing issue that led to a larger number of cases being reported on July 21 and a smaller number on July 22. As always, we recommend the use of date of event (date of diagnosis, date of admission, date of death), not date of report, as date of report is subject to data issues that are unrelated to when someone gets sick or gets admitted to a hospital.
