### ISSUE TITLE
Deaths by underlying conditions 

### ISSUE THREAD

**Issue by thythythy-code** [nychealth/coronavirus-data#108]
This may be obvious but what defines death count illness and death count no illness? Is there a certain set of criteria for what constitutes illness? Where is the information pulled from? Thank you for all the work you do to increase transparency and useful information.

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. We have a team of investigators who review medical charts in some instances, and we also import data from external sources. Underlying illnesses are defined as lung disease, asthma, heart disease, a weakened immune system, obesity, diabetes, kidney disease, liver disease and cancer.
