### ISSUE TITLE
Question: coronavirus indicators by zip code AND by date

### ISSUE THREAD

**Issue by cebeaudoin** [nychealth/coronavirus-data#114]
Dear Sir/Madam: 

In the Excel file named “data-by-modzcta,” I can see that there is a series of coronavirus indicators that are reported by zip code (in New York City). From various figures that I have found elsewhere, it seems that there is also data on coronavirus indicators as reported by zip code AND by date.

Do you happen to know how can I get access to this data in raw form (e.g., Excel)?

Thanks for your assistance with this matter.

**Comment by mmontesanonyc** [comment]
Closing this old issue, as for a while this repository has contained trend data by modzcta.
