### ISSUE TITLE
Location of Death

### ISSUE THREAD

**Issue by ryanzalla** [nychealth/coronavirus-data#115]
Where can I find time series data on location of death due to COVID-19 in New York? 

I found the cumulative totals but not the time series. Location of death is either hospital or non-hospital, where non-hospital is divided among nursing home, hospice, residence, etc.

Thank you so much!

**Comment by mmontesanonyc** [comment]
Hello, thanks for the question. We are closing this old issue since these data aren’t available in this repository, and though it's helpful to see what data people are interested in, we are not able to field custom data requests through Github.
