### ISSUE TITLE
9/13 update?

### ISSUE THREAD

**Issue by svfnyc** [nychealth/coronavirus-data#117]
Will we get an update today 9/13? We did not get one last Sunday. It's about 2:30 - no update - and usually the daily upload is done by around 1.

**Comment by mmontesanonyc** [comment]
Apologies for the delay. As was indicated on the [Data Webpage](https://www1.nyc.gov/site/doh/covid/covid-19-data.page), there was no update for Sunday 9/13, and Monday's update included Sunday's update.
