### ISSUE TITLE
Trended zip code data

### ISSUE THREAD

**Issue by kwhittinghill** [nychealth/coronavirus-data#122]
Forgive me if this has been addressed - does trended zip code data exist (testing and positives)?

**Comment by mmontesanonyc** [comment]
Hello,
You may already have seen weekly testrate-by-modzcta, caserate-by-modzcta, and percentpositive-by-modzcta in [Trends](https://github.com/nychealth/coronavirus-data/tree/master/trends), as well as daily percent positive (pp-by-modzcta) in [Latest](https://github.com/nychealth/coronavirus-data/tree/master/latest).
