### ISSUE TITLE
NYC recent data by zip code

### ISSUE THREAD

**Issue by raptorc85** [nychealth/coronavirus-data#123]
Greetings, 

I see that there is testing data with the 7-day rolling for the city. And there is updated COVID data, including testing, for each modified zip code. However, the latter is cumulative. Is there a data that includes the recent 7-day rolling COVID-19 positivity rate broken down by zip code? 

Thanks,

**Comment by davor999** [comment]
I would also like tp see more granular zip code data please. With recent changes to NYC policy targeting specific zip codes this is of pressing public interest.

**Comment by bhs1** [comment]
Is this what you're looking for? https://github.com/MickeyLane/ByZip/tree/master/NewYork

**Comment by raptorc85** [comment]
I've used that file to find the difference but it doesn't equal what the city ends up reporting for zip codes. For example the hot spot zip codes the city is watching right now have considerably higher 7-day rolling averages if you calculate it based on the comparing the current to historic data for the zip code file. My guess is that the city is using data that is being cleaned whereas there isn't a reason to clean the history files for this data set. So in doing the calculation myself, I'm coming up with trends that aren't accurate and thus not helpful in predicting new hot spots. What's frustrating is that the city clearly has the data and when there is a hot spot, is sharing that data for those zip codes. What they aren't doing is sharing all the zip code data so we can see how our zip code is doing compared to where the hot spot is and whether, as one who lives a neighborhood over, we should be preparing for the same restrictions.

**Comment by vacquaviva** [comment]
I have the same issues - I've used the history to get % positive rate on a daily basis, and it doesn't match any of the tables published by Cuomo (at least in my zip code). It's really frustrating to not be able to see recent trends, and it's so important for people to know what their *current* situation is to make decisions!

**Comment by jyatcha** [comment]
This is a serious problem. We are being governed by data that is opaque and contradictory.

**Comment by mmontesanonyc** [comment]
Closing this old issue, as the repository has included positivity by modzcta for a while.
