### ISSUE TITLE
Zip Code Data - Recent

### ISSUE THREAD

**Issue by davor999** [nychealth/coronavirus-data#124]
Please can you make recent data by zip code available.

**Comment by mmontesanonyc** [comment]
Currently, recent data by ZIP is available [on the website](https://www1.nyc.gov/site/doh/covid/covid-19-data-recent.page) and in the file [recent-4-week-by-modzcta](https://github.com/nychealth/coronavirus-data/blob/master/recent/recent-4-week-by-modzcta.csv).
