### ISSUE TITLE
Cumulative hospitalizations dropped in 10/6 update

### ISSUE THREAD

**Issue by OBHSplanning** [nychealth/coronavirus-data#128]
From 10/5 to 10/6 the total hospitalizations data dropped by about 2000 cases.  I want to verify if there was some cleaning or data validation done that adjusted this value.  And what caused this value to change.

**Comment by mmontesanonyc** [comment]
Yes. Per [commit note](https://github.com/nychealth/coronavirus-data/commit/40fc9f45101c0bc5043d2fa214ae84ba1e12ecca):

> Please note that the overall number of hospitalizations has decreased. This is because of data cleaning processes where we have restricted classifying a hospitalization as related to COVID-19 only if the patient was admitted within 14 days of diagnosis date.

**Comment by OBHSplanning** [comment]
My apologies, I missed the commit note.  Thank you for the clarification.
