### ISSUE TITLE
ESRI ArcGIS shapefile for COVID zones (red, orange, yellow)?

### ISSUE THREAD

**Issue by lfeldmanhay** [nychealth/coronavirus-data#130]
Hi there, is there a publicly available shapefile for the current covid hotspot zones?
https://nycgov.maps.arcgis.com/apps/instant/lookup/index.html?appid=021940a41da04314827e2782d3d1986f
I wanted to cross some service sites against the hotspots rather than doing them one by one. Thanks!

**Comment by willcwelch** [comment]
Chris Whong has dataset on QRI that explains how to pull the data as GeoJSON directly from the public map or convert it to a Shapefile: https://qri.cloud/chriswhong-demo/new_york_city_covid_19_hot_spot_zones.

**Comment by lfeldmanhay** [comment]
Thanks so much!
