### ISSUE TITLE
Possible Error 10034: this week's case count = 4 week case count?

### ISSUE THREAD

**Issue by nycmom** [nychealth/coronavirus-data#132]
This week's (10/15) recent-4-week-by-modzcta in 10034 shows COVID_CASE_COUNT_WEEK2 equal to 3 and COVID_CASE_COUNT_WEEK1 equal to 23 which is a notable (and seemingly improbable?) increase.

I'm wondering if this may have been the result of a typo, as in last week's (10/8) recent-4-week-by-modzcta in 10034 the COVID_CASE_COUNT_4WEEK was also 23.

**Comment by mmontesanonyc** [comment]
This isn't a typo, but thanks for being attentive.
