### ISSUE TITLE
Age and zip code 

### ISSUE THREAD

**Issue by allomate1** [nychealth/coronavirus-data#133]
Can you post the data for positive testing by zip code and age (non cumulative)? Our team is curious to see the break out by school aged children vs adults.

**Comment by mmontesanonyc** [comment]
Hi, thanks for the interest. Our new data release includes citywide breakdowns of test numbers, rates, and percent positivity by age [here](https://github.com/nychealth/coronavirus-data/blob/master/trends/testing-by-age.csv), as well as more refined data on percent positivity by ZIP code.
