### ISSUE TITLE
PCTCHANGE_2WEEK Definition Error

### ISSUE THREAD

**Issue by nycmom** [nychealth/coronavirus-data#134]
In recent/recent-4-week-by-modzcta.csv the definition of PCTCHANGE_2WEEK does not seem to match the data. 
It seems that the correct definition should be: [(week 1+week2)/(week 3+week 4)-1]*100.

**Comment by mmontesanonyc** [comment]
Thanks for your comment. That is indeed the formula we are using, but there was a mistake in our documentation.
