### ISSUE TITLE
Question: data definition "newly reported cases" vs. "positive tests"

### ISSUE THREAD

**Issue by samerubin** [nychealth/coronavirus-data#135]
What is the difference between the "newly reported cases" shown in "[Milestones](https://www1.nyc.gov/site/doh/covid/covid-19-goals.page)" (under the "New Cases" tab) vs. the "positive tests" counts in tests.csv?

The data for positivity rates are the same in Milestones and tests.csv, but the new case counts are not. What explains the difference? And where does the data for the "newly reported cases" in Milestones come from / how is it calculated?

Thank you!

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. There are two reasons for the differences between those two metrics: report date vs date of event, and the difference between cases and positive tests.

**Report date vs date of event:** In tests.csv, “People tested” (not tests — these are deduplicated by person and day, so somebody who is tested twice per day is only counted once) is reported by the date of test. So, if today (10/22) we find out that someone was tested and was positive on 10/15, it's shown on trend charts as having taken place on 10/15. But, presenting data by “report date” would show when the Health Department found out about it — and would show it in 10/22 data (all of the data in this repository are by [date of event](https://github.com/nychealth/coronavirus-data#report-date-versus-date-of-event), not report date). 

But, the Milestones data shows _newly reported cases_, which means that the date associated with a case isn't when it was diagnosed, but when the Health Department found out about the diagnosis. For more information, [search previous issues ](https://github.com/nychealth/coronavirus-data/issues?q=report+date)for “report date” or “date of report.” 

**Positive tests aren’t the same as cases:** A person is counted as a case on the date of their first positive test. People may test positive more than once, which is reflected in testing data but not in case data.
