### ISSUE TITLE
recent-4-week NUM_PEOP_TEST_

### ISSUE THREAD

**Issue by robambalu** [nychealth/coronavirus-data#137]
I noticed in the recent/recent-4-week-by-modzcta.csv there is data per week like case count week 1/2/3/4 but for num_peop_test and percent_positive you only provide the total of the 4 week period ( not the individual weeks )
Would it be possible to include the per-week numbers as well?  I'm particularly interested in seeing changes in positivity rates given the important of this statistic and its impact on red/orange/yellow zones

Thanks!

**Comment by mmontesanonyc** [comment]
Hi, thanks for the interest. Our new data release includes [weekly test rate, percent positive, and case rates by modZCTA here](https://github.com/nychealth/coronavirus-data/tree/master/trends), and [daily values of 7-day cumulative percent positivity, here](https://github.com/nychealth/coronavirus-data/tree/master/latest), which may provide what you're interested in.
