### ISSUE TITLE
Data Organization- "recent-4-week-by-modzcta.csv"

### ISSUE THREAD

**Issue by jyatcha** [nychealth/coronavirus-data#139]
Hello Contributors,

I hope you are all well as you continue your foundational work to help us see an invisible virus. Your work is integral as sight is necessary to fight. 

I am trying to work through some of this data but am running into some difficulty. Why is weekly data being saved under a transitory data field defined by the number of weeks it is away from us ex. "COVID_CASE_COUNT_WEEK4"? Wouldn't data be clearer and more temporally sound if fields were titled by their respective date, or some other non-moving metric, so that we can maintain data over the course of time? This data is integral to the governance of our state, city, and zip codes, and seems it will continue to be so for a foreseeable future. This data should be properly stored for its present clarity and for its continued archival use.

Any insight would be greatly appreciated,
Jamie Yatcha
jyatcha@gmail.com

**Comment by MickeyLane** [comment]
Does MickeyLane/ByZip contain what you want? The data is organized by NewYork\YYYY-MM-DD and is sourced from this repository. I don't process it

**Comment by jyatcha** [comment]
Thank you MickeyLane for your referral! The field definitions there are a bit ambiguous. Aside I think it is important we can receive reliable data amidst a pandemic from a, hopefully, reliable governmental source. It is important that we develop a coherent data system that can be expanded, developed, and improved. An unstable structure will not support further data accumulation, which may be essential to a proper grip of out public health emergency.

Thank you Mickey lane once again!
jy

**Comment by mmontesanonyc** [comment]
Thanks for the comments, but since those files are out of use, I'll close this issue.
