### ISSUE TITLE
Could you add a license to the project?

### ISSUE THREAD

**Issue by MylesBorins** [nychealth/coronavirus-data#14]
Hello,

I am an engineer at Google interested in using your project. If you are comfortable with permitting this, could you please add an open source license (https://opensource.org/licenses) to your project directory?

**Comment by jnubian** [comment]
Would this be a GNU license? If not, it should remain where how it is.

**Comment by ret394** [comment]
a license is  not 100% essential for this use-case and repo can be forked. The source website doesn't mention license.
