### ISSUE TITLE
Population Data- recent-4-week-by-modzcta.csv

### ISSUE THREAD

**Issue by jyatcha** [nychealth/coronavirus-data#141]
Hello Contributors,

A select few fields are devoted rates (i.e. COVID_DEATH_RATE_4WEEK, TESTING_RATE_4WEEK). Would it be possible to provide the raw zip code population data you use? 

This would clearly provide the raw data for others to calculate rates for any and all fields as they desire. Best practice would also seems to advocate stripping a centralized data set, such as this, from any non raw data fields for sake of clarity, flexibility, and standard. 

One problem manifest in the current organization is that rates are reported on a per 100,000 basis. I know this because I referred back to the definitions table. Referring to a definition table is obstacle or disincentive to engage with this foundational data. Reporting raw data will operate on universal understandings that will best serve all.

Thank you and best,
Jamie Yatcha
jyatcha@gmail.com

**Comment by mmontesanonyc** [comment]
Population denominators for modified ZCTAs are available [here](https://github.com/nychealth/coronavirus-data/blob/master/data-by-modzcta.csv).
