### ISSUE TITLE
Hospitalization Data recent-4-week-by-modzcta.csv

### ISSUE THREAD

**Issue by jyatcha** [nychealth/coronavirus-data#142]
Hello Contributors,

The governors has professed that hospitalization data is among the most significant indicators of an outbreak's present intensity. He has also said this data has been provided. While some of his presentations have included this information it is not available in any helpful form.

Is it possible to retrieve weekly zip code hospitalization data to keep the most precise pulse on our pandemic?

Thank you for all your great work,
Jamie Yatcha
jyatcha@gmail.com

**Comment by mmontesanonyc** [comment]
Hello,
I'm closing this issue now that monthly hospitalization rates by modzcta have been published in this repository.
