### ISSUE TITLE
Testing Positivity Rates recent-4-week-by-modzcta.csv

### ISSUE THREAD

**Issue by jyatcha** [nychealth/coronavirus-data#143]
Hello Contributors,

The mayor and governor have justified lockdowns on swaths on Brooklyn and Queens on the basis of testing positivity rates. Yet this data is not reported for zip codes at any recurring interval. Can we get the weekly zip code testing positivity rates that have supposedly justified major shutdowns of businesses, schools, and much of daily life in select areas?

Any insight would be much appreciated,
Jamie Yatcha
jyatcha@gmail.com

**Comment by mmontesanonyc** [comment]
Hi, thanks for the interest. Our new data release includes [weekly test rate, percent positive, and case rates by modZCTA here](https://github.com/nychealth/coronavirus-data/tree/master/trends), and [daily values of 7-day cumulative percent positivity, here](https://github.com/nychealth/coronavirus-data/tree/master/latest).
