### ISSUE TITLE
New tests vs. new cases discrepancy, is it all due to retesting?

### ISSUE THREAD

**Issue by dyoung95437** [nychealth/coronavirus-data#144]
Hi I realize others have asked about this before and I read some of those, but I wanted to ask about the discrepancy between the numbers of new "Positive Tests" for particular dates in the tests.csv file, versus the new "Case Count" numbers for the same dates in the case-hosp-death.csv file. If I am reading a previous comment correctly, my understanding is the discrepancy is entirely or mainly accounted for by retesting of individuals who previously tested positive, is that correct? I refer to this comment from July 20 here: https://github.com/nychealth/coronavirus-data/issues/102

I just want to confirm that is correct, because, for example, in the last 30 days there is complete data for as of now, 9/23 to 10/22, there were a total of 14,940 new cases recorded but 19,494 new positive tests. This means there were about 30% more positive tests than new cases in those 30 days. As 30% is a big difference, I just wanted to check that discrepancy was primarily or entirely accounted for by re-testing. 

Thanks so much for all you do,
Dan Young

**Comment by mmontesanonyc** [comment]
Yes, the difference is due to people who previously tested positive, per that previous comment. Thanks.
