### ISSUE TITLE
Title of "data update"

### ISSUE THREAD

**Issue by DataAnalyst2020** [nychealth/coronavirus-data#145]
Instead of "Daily data update" , could you switch back to include the actual date like it used to be (e.g. 10/29 data update)? It's extremely helpful to see the date of the data. Thanks.

![Screenshot 2020-11-03 085214](https://user-images.githubusercontent.com/72752320/97993567-3d042c80-1db2-11eb-95e5-eb526cd49ab5.png)

**Comment by MickeyLane** [comment]
I'm not part of this repository effort. I use it to populate the zip data by date at MickeyLane/ByZip.

You can do a "git log" to see the date and time of the commits. Use "q" to terminate the output.

**Comment by pechersky** [comment]
You can also check the `summary.csv` file at any commit to see the info, which should be even more reliable than git log dates, because it directly corresponds to what they uploaded.

**Comment by mmontesanonyc** [comment]
Thanks, we'll continue including the date in our commit notes.
