### ISSUE TITLE
# of Tests not updated today

### ISSUE THREAD

**Issue by svfnyc** [nychealth/coronavirus-data#146]
Looks like in the file data-by-modzcta.csv, total tests are the same as yesterday. Similar to same problem a few days ago.

**Comment by MickeyLane** [comment]
I compared the two dates (2020-11-03 & 2020-11-02) in my capture of the file and they're different. See GitHub MickeyLane/ByZip/NewYork/2020-11-xx. For zip 10001 (1st data row in the file), tot test is 10599 on the 2nd, 10637 on the 3rd.

**Comment by svfnyc** [comment]
11/3 and 11/4 are different for the zips I follow. 


  | MODIFIED_ZCTA | COVID_CASE_COUNT | TOTAL_COVID_TESTS
3-Nov | 10023 | 779 | 23,538
4-Nov | 10023 | 783 | 23,538
3-Nov | 10028 | 656 | 17,823
4-Nov | 10028 | 660 | 17,823
3-Nov | 10029 | 2,248 | 28,233
4-Nov | 10029 | 2,251 | 28,233
3-Nov | 10069 | 85 | 2,937
4-Nov | 10069 | 85 | 2,937
3-Nov | 10128 | 835 | 24,479
4-Nov | 10128 | 835 | 24,479

**Comment by mmontesanonyc** [comment]
data-by-modzcta.csv was updated today per usual.
