### ISSUE TITLE
Total Covid tests unchanged from 11/3 upload to 11/4 upload

### ISSUE THREAD

**Issue by svfnyc** [nychealth/coronavirus-data#147]
Since you closed my earlier post about this, I'm reminding you there was the same issue last week (TOTAL_COVID_TESTS unchanged from the 10/25 upload to the 10/26 upload #136) and showing you that EVERY ZIP CODE IS UNCHANGED from 11/3 to 11/4 for TOTAL_COVID_TESTS. See attached. Given the return of testing lines at my City MD, I doubt there were 0 tests done....

[Missing cases 11.4.xlsx](https://github.com/nychealth/coronavirus-data/files/5491012/Missing.cases.11.4.xlsx)

**Comment by mmontesanonyc** [comment]
Closing this old issue with the note that daily updates to cumulative files don't events from the previous day, and small changes can reflect ordinary delays in reporting or data processing.
