### ISSUE TITLE
New cases and 7-day averages by zip code

### ISSUE THREAD

**Issue by sarah-hf** [nychealth/coronavirus-data#149]
Hello, I am wondering if there's a way to release data by zip code that captures trends, as others have suggested. Specifically I am looking for 7-day averages and new daily cases. It seems like this could be calculated by comparing daily releases, but it looks like this is discouraged because of delays receiving data: https://github.com/nychealth/coronavirus-data#report-date-versus-date-of-event

Is there any way that trend data can be released by zip code, even if it is delayed by a few days?

If anyone has come up with a solution for this or I am missing something please let me know!

**Comment by mmontesanonyc** [comment]
Hi, thanks for asking this, and thanks for understanding the difference between report date and event date in our documentation. 
Our new data release includes [weekly test rate, percent positive, and case rates by modZCTA here](https://github.com/nychealth/coronavirus-data/tree/master/trends), and [daily values of 7-day cumulative percent positivity, here](https://github.com/nychealth/coronavirus-data/tree/master/latest).
