### ISSUE TITLE
Will the data in "archive" folder still be updated from this latest Major Update commit? 

### ISSUE THREAD

**Issue by nygeog** [nychealth/coronavirus-data#150]
@mmontesanonyc I've built tools that use the following files:

```python
data-by-modzcta_all.csv
tests-by-zcta_all.csv
antibody-by-modzcta_all.csv
modzcta_2010.shp
zcta-to-modzcta.csv
```

I loop through all your commits to derive dated timestamps for daily additions. You had mentioned there are some shortcomings to relying on this methodology but it is better than no historical data. But this new format breaks all this functionality and isn't daily data but weekly. **Will the older files and formats and data be preserved?**

I don't see all the files in the: 
https://github.com/nychealth/coronavirus-data/tree/master/archive

Thanks,
Danny

**Comment by mmontesanonyc** [comment]
Most of our files, including data-by-modzcta and antibody-by-modzcta, are still being updated. You can find those two in [the Totals folder](https://github.com/nychealth/coronavirus-data/tree/master/totals). Apologies for changing URLs on you but it was a one-time change that is helpful for our internal workflow.

**Comment by nygeog** [comment]
@mmontesanonyc it's not the URLs that's the problem, by moving the files changes the commit history for all of the files. 

See here: https://github.com/nychealth/coronavirus-data/commits/b671e0ed09b458f148110ad0d71479cf62580ea4/totals/data-by-modzcta.csv

There's no longer that history of updates for files posted. 

Would it be possible to get advanced warnings of any future updates as this disrupts tracking this data pretty severely?
