### ISSUE TITLE
Change in Population Denominator

### ISSUE THREAD

**Issue by svfnyc** [nychealth/coronavirus-data#151]
The population denominator - which remained unchanged for all the months I've been tracking - has now changed for each of the 5 zips I'm following, and not in the same direction (ie, reduced for deaths). Are you getting from a different source? Does this mean the counts in the cume totals were also adjusted as you count different patients?  

Change in Population Denominator

 Zip | Previous | 9-Nov | Change
10028 | 49,155 | 47,370 | (1,785)
10029 | 78,842 | 78,225 | (617)
10128 | 61,352 | 58,559 | (2,793)
10023 | 24,204 | 24,281 | 77
10069 | 3,041 | 3,057 | 16

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. 

[Per our documentation](https://github.com/nychealth/coronavirus-data#rates-per-100000-people), we revised our population estimates, consistent with standard epidemiology practice. This affects rates, but not counts.
