### ISSUE TITLE
Why are there 2 lines for data pending

### ISSUE THREAD

**Issue by laurenc-FML** [nychealth/coronavirus-data#158]
Hello, 
I have been utilizing your daily data information for months, thank you for providing this daily information.
Last several days there are 2 rows for Data pending

coronavirus-data/totals/probable-confirmed-by-age.csv

each row of Data Pending is identical
is this an error?
Thank you
laurenc@feingoldmedical.com

![image](https://user-images.githubusercontent.com/68200373/99854770-729b6a80-2b53-11eb-9bd5-3efa4dedf40f.png)

**Comment by mmontesanonyc** [comment]
Hi, thanks for catching this. We've fixed this issue.
