### ISSUE TITLE
History by Zipcodes going back to April?

### ISSUE THREAD

**Issue by jakedobkin** [nychealth/coronavirus-data#160]
Hi, 

When you guys changed the file structure two weeks ago, it stopped showing the history for the totals-by-modzip file; and I need to pull the total positivity per zipcode from a week back in May- can you either restore the history or send me a link to the version from the 5/1?

Thanks,

Jake

**Comment by jpfreeley** [comment]
Because this is on github, every single change is archived.. You should be able to find a "commit" for the time you need.

**Comment by jpfreeley** [comment]
Here's a list of all changes https://github.com/nychealth/coronavirus-data/commits/master

**Comment by mmontesanonyc** [comment]
@jakedobkin, if you visit the link that @jpfreeley kindly provided, scroll to your date of interest, and click the <> button ("Browse the repository at this point in history") then you'll be able to see data from that day.
