### ISSUE TITLE
Poverty Rates

### ISSUE THREAD

**Issue by oliverripps** [nychealth/coronavirus-data#161]
Hi, These datasets are incredible and have been very helpful for a project I am doing for a college statistics class. Do you have a link to your resource for getting poverty categorization for each zip code?

Once again, really an incredible project.

**Comment by mmontesanonyc** [comment]
Hi, glad you're finding it useful. You can find [information on poverty classifications in our documentation](https://github.com/nychealth/coronavirus-data#poverty-groups).
