### ISSUE TITLE
Missing file in Totals directory based on filename updates as of November 9

### ISSUE THREAD

**Issue by masinazarian** [nychealth/coronavirus-data#162]
The table you included in documentation for file organization updates of November 9th maps the filename `deaths/probable-confirmed-dod.csv` to `totals/data-by-day.csv` but there is no such file under the `totals` directory. The `case-hosp-death.csv` file is mapped to a similar filename `trends/data-by-day.csv` which exists. Is it a copy-paste error in documents? Which file is equivalent to `deaths/probable-confirmed-dod.csv`? Thanks!

**Comment by mmontesanonyc** [comment]
You can find [data-by-day](https://github.com/nychealth/coronavirus-data/blob/master/trends/data-by-day.csv) in [Trends](https://github.com/nychealth/coronavirus-data/tree/master/trends). That file includes daily probable and confirmed death counts.

**Comment by masinazarian** [comment]
Thanks @mmontesanonyc! So basically two files (`deaths/probable-confirmed-dod.csv` and `case-hosp-death.csv`) have been combined into one (`trends/data-by-day.csv`), right?

**Comment by mmontesanonyc** [comment]
Yes, exactly.

**Comment by masinazarian** [comment]
Thanks!
