### ISSUE TITLE
Zip data from before 11/9 major update?

### ISSUE THREAD

**Issue by dyoung95437** [nychealth/coronavirus-data#163]
I'm interested in looking at the by zip code data that used to be available by looking at the file history/old updates before the 11/9 Major update, and from there you could get an idea of the daily from how it was changing from one day to the next. None of that is available in the Archive if you go to the file history for those, is it somewhere else I can view? Or is it included with one of the other files on here and I'm just not seeing it? I can't find any daily or weekly data by zip from before 8/8/20.

**Comment by mmontesanonyc** [comment]
Hi, thanks for asking. We have not published data (like test rate, case rate, and percent positivity) by ZIP prior to 8/8/2020. The 11/9 update began publishing those data for the previous 3 months.
