### ISSUE TITLE
Significant drop in death count

### ISSUE THREAD

**Issue by jhtep** [nychealth/coronavirus-data#165]
The death count has drop on 12/07
For example zip code Brooklyn 11234
Check from the New York Times web site and tracked back to this repo.
File: https://github.com/nychealth/coronavirus-data/blob/master/totals/data-by-modzcta.csv

| Date  | Cases | Per 100,000 | Deaths | Per 100,000 |
| ----- | ----- | ----------- | ------ | ----------- |
| 12/07 | 3,295 | 3,457       | 187    | 196         |
| 11/30 | 3,144 | 3,299       | 198    | 208         |
| 11/19 | 2,975 | 3,122       | 197    | 207         |
| 11/04 | 2,828 | 2,967       | 196    | 206         |
| 09/17 | 2,526 | 2,650       | 195    | 205         |
...
| 07/23 | 2,353 | 2,469       | 195    | 205         |
..
| 07/08 | 2,313 | 2,427       | 192    | 201         |
...
| 07/03 | 2,291 | 2,404       | 191    | 200         |

**Comment by mmontesanonyc** [comment]
Thanks for the question. We do constant data cleaning to ensure data quality; all data are preliminary and subject to change.   [As mentioned in the documentation](https://github.com/nychealth/coronavirus-data#important-changes-on-december-7-2020), the 12/7 update reflects a new geocoding process that causes some zip-level data to change slightly.

**Comment by jhtep** [comment]
Even with a slight change to zip-level data, shouldn't the overall total be same or increase?

Zipcode 11234 drop by 11 deaths, shouldn't the 11 deaths  show up in another zip code?

I see a city wide drop in death stats on 12-07.

I extracted the historical data for totals/data-by-modzcta.csv and
I see a significant drop in deaths totals on 12-07
that is NOT balanced out across zip codes.

Here's what I see - 

-- Total deaths in NYC during period 11-30 to 12-09:
19,550 New York City Deaths to date 2020-11-30
19,555 New York City Deaths to date 2020-12-01
19,625 New York City Deaths to date 2020-12-06 ********
19,288 New York City Deaths to date 2020-12-07
19,306 New York City Deaths to date 2020-12-09
