### ISSUE TITLE
Merged commits with HEAD information in the uploaded data

### ISSUE THREAD

**Issue by asboner** [nychealth/coronavirus-data#167]
It seems that the latest batch of data has the conflicting merge information. Here is an example from: [now-test.csv](https://github.com/nychealth/coronavirus-data/blob/master/latest/now-tests.csv)
`<<<<<<< HEAD
DATE,TOTAL_TESTS,POSITIVE_TESTS,PERCENT_POSITIVE,TOTAL_TESTS_7DAYS_AVG,POSITIVE_TESTS_7DAYS_AVG,PERCENT_POSITIVE_7DAYS_AVG,TOTAL_ANTIGEN_TESTS,TOTAL_ANTIGEN_TESTS_7DAYS_AVG,INCOMPLETE
09/07/2020,18900,272,0.0144,29232,298,0.0102,153,184,0
09/08/2020,47140,526,0.0112,30098,317,0.0105,360,208,0
`

**Comment by mmontesanonyc** [comment]
Thanks, we're aware and working on it.
