### ISSUE TITLE
Covid deaths with or without underlying medical condition

### ISSUE THREAD

**Issue by gmaguire1** [nychealth/coronavirus-data#168]
As far back as at least September you had an age-based category of Covid-19 deaths with or without underlying medical conditions as well as those in which the presence or absence was yet undetermined.  

I can't seem to locate that breakdown under your new format. Can you give me some guidance on this?
Thanks,
Gil Maguire

**Comment by mmontesanonyc** [comment]
Hi, thanks for asking. You can find [that file, deaths-by-underlying-conditions.csv ](https://github.com/nychealth/coronavirus-data/blob/master/totals/deaths-by-underlying-conditions.csv) in the folder named [totals](https://github.com/nychealth/coronavirus-data/tree/master/totals).

**Comment by gmaguire1** [comment]
Thank you so much.
