### ISSUE TITLE
daily testing data (testing.csv)

### ISSUE THREAD

**Issue by DoaneAS** [nychealth/coronavirus-data#17]
Hi,

Thanks so much for making this available.  

I was wondering if the data for daily testing- hospitalizations- deaths is still available in testing.csv.  I'm not seeing this in the updated repo and we were interested in looking at these numbers.

Best,
Ashley

**Comment by liang2zhu1** [comment]
Totally agree, thanks for the data but we *really* need the **daily test count** and positive rate

**Comment by DTPOTO** [comment]
The City Health dept is now deferring us to the State.   I did find the state dash board and with some work you can re-create the Positive/Negative results along with the cumulative Positive results for the 5 counties (boroughs) of NYC.   The information is provided by TEST RESULT date (or REPORTING DATE).   This is the format that we were used to seeing as of last week. 
NYS dashboard is https://covid19tracker.health.ny.gov/views/NYS-COVID19-Tracker/NYSDOHCOVID-19Tracker-Map?%3Aembed=yes&%3Atoolbar=no 

![image](https://user-images.githubusercontent.com/63018432/78500639-a55c3400-7725-11ea-90f0-7e6d9ba5e104.png)

Note:  The Testing.csv file did give us the ability to see the test results at the Diagnosis-Date (the date the test was ordered, most likely administered).    Just for context there is ruffly a 3-10 delay between Diagnosis & Reporting.     Reporting is just what we have been used to seeing and looks more consistent.  Consistently up and to the right!
@DoaneAS @liang2zhu1

**Comment by psylum** [comment]
The state's testing data is now also available in the Open Data NY portal: https://data.ny.gov/browse?tags=covid-19

**Comment by yywong01** [comment]
@DTPOTO, this is super valuable info! I have been looking for days for a more disaggregated data on testing and find none. Thanks so v much!
