### ISSUE TITLE
Weighted average Total Death Rate by Race or by Age not equal to published Total Death Rate

### ISSUE THREAD

**Issue by gugmifrt** [nychealth/coronavirus-data#170]
Hi, I'm wondering whether there's something in how Race data or total death rate per 100K (or something else) is defined differently from how I'm interpreting it in the README.

My problem:
I am cross-referencing ZIP code data by ACS 5Y 2019 demographic data to form a weighted average Total Death Rate per 100K rate.

The problem is of course that a sanity check of a weighted average of, for example, Race/ethnicity - White for Manhattan does not equal 

(Age 0-17 COVID total death rate per 100K) * (% of Race/ethnicity - White & Age 0-17) + (Age 18-24 COVID total death rate per 100K) * (% of Race/ethnicity - White & Age 18-24) + (Age 25-34 COVID total death rate per 100K) * (% of Race/ethnicity - White & Age 25-34) + (Age 35-44 COVID total death rate per 100K) * (% of Race/ethnicity - White & Age 35-44) + (Age 45-54 COVID total death rate per 100K) * (% of Race/ethnicity - White & Age 0-17)  + (Age 55-64 COVID total death rate per 100K) * (% of Race/ethnicity - White & Age 55-64) + (Age 65-74 COVID total death rate per 100K) * (% of Race/ethnicity - White & Age 65-74) + (Age 75+ COVID total death rate per 100K) * (% of Race/ethnicity - White & Age 75+)

This holds true for all weighted averages I've tried. I'm wondering how to fill/account for that inconsistency and whether that invalidates weighted average breakdowns on a ZTCA level by demographic/borough-level variables.

Has anyone encountered this and figure out a workaround? Is there a way to get more granularity/something that checks out?

Thank you!

**Comment by mmontesanonyc** [comment]
Hi there. We can't comment on your calculations, but left this issue open in hopes that other data users might be able to help you out. At this point, though, we're going to close this issue.
