### ISSUE TITLE
POSITIVE_TESTS_7DAYS_AVG is not actual 7-day-avg of POSITIVE_TESTS in trends/tests.csv?!?

### ISSUE THREAD

**Issue by dyoung95437** [nychealth/coronavirus-data#171]
In the file trends/tests.csv, the numbers in the POSITIVE_TESTS_7DAYS_AVG column do not seem to be what I get when I independently calculate 7-day-averages using the numbers in the POSITIVE_TESTS column. What is the methodology here? Thanks so much for all your hard work!

**Comment by mmontesanonyc** [comment]
As noted [in the readme](https://github.com/nychealth/coronavirus-data#calculation-of-percent-positivity), individuals are counted once in the 7-day average percent positivity, so it will be slightly different than calculating from daily values in tests.csv. We'll update the file-specific documentation to make that clear.
