### ISSUE TITLE
1.2 and 1.1 uploads for data by zip

### ISSUE THREAD

**Issue by svfnyc** [nychealth/coronavirus-data#173]
Yes, I know you hate questions from those of us tracking daily changes. However, after what looks like a huge adjustment that drove down numbers with the 1.1 upload, there seems to be an even bigger upward adjustment with the 1.2 upload. Was this reversing whatever was done on 1.1? Otherwise, these testing numbers are crazy. Example below:

Change in daily tests
10023  1/1 down -310, 1/2 up 569 (previous 7 day average was 111)
10029  1/1 down -532, 1/2 up 850 (previous 7 day average was 116)
10128  1/1 down -325, 1/2 up 547 (previous 7 day average was 121)

**Comment by svfnyc** [comment]
Just following up. The 1/3 and 1/4 uploads demonstrate just how out of whack 1/1 and 1/2 was. I'm attaching my file. 
[Covid January 2021 Tracker.xlsx](https://github.com/nychealth/coronavirus-data/files/5766162/Covid.January.2021.Tracker.xlsx)

**Comment by mmontesanonyc** [comment]
We don’t hate these questions, we welcome them. Thanks for your patience.

When cumulative data get updated every day, counts are sometimes adjusted as data cleaning and geocoding procedures are constant, and ongoing processes. This is why we recommend against using daily changes to cumulative data as trend data. And, of course, all data are preliminary and subject to change.
