### ISSUE TITLE
Vaccine stats?

### ISSUE THREAD

**Issue by jakedobkin** [nychealth/coronavirus-data#174]
Hi,

When will the data underlying this page be made available on Github?  https://www1.nyc.gov/site/doh/covid/covid-19-data-vaccines.page

Thanks,

Jake

**Comment by lukegil** [comment]
For now I'm manually downloading it and compiling it here: https://github.com/lukegil/covid-19/tree/main/raw_data/nyc/covid19-vaccine

**Comment by jakedobkin** [comment]
Checking in on this one!  It would be great if the sheets powering the Tableau viz on the city site were up on Github!

**Comment by jakedobkin** [comment]
Still checking in on this!  I noticed you guys added the vax zipcode to the Tableau but it would make life much easier for us if it were on github too!

**Comment by nygeog** [comment]
+1 on this issue. Is there a reliable endpoint for the Tableau dashboard? download of a `.csv`? It only now allows for an export of the tab file.

**Comment by fiddleHeads** [comment]
+1 on this issue again. I would appreciate being able to download this data via github.

**Comment by bertrandmartel** [comment]
I've made a [Tableau scraper library](https://github.com/bertrandmartel/tableau-scraping) in python, it would be possible to extract the data daily in a Github action with :

```python
from tableauscraper import TableauScraper as TS

url = 'https://public.tableau.com/views/COVID-19VaccineTrackerDashboard_16153822244270/Dosesadministered'

ts = TS()
ts.loads(url)

workbook = ts.getWorkbook()

for t in workbook.worksheets:
    print(f"worksheet name : {t.name}")
    print(t.data)
```

https://replit.com/@bertrandmartel/TableauCovidVaccine

**Comment by bertrandmartel** [comment]
I've set up a repository extracting the data every day from this Tableau dashboard : https://github.com/bertrandmartel/covid19-nyc-vaccine-tracker

**Comment by mmontesanonyc** [comment]
Hello, [data on NYC's COVID-19 vaccinations are available here](https://github.com/nychealth/covid-vaccine-data).
