### ISSUE TITLE
Questions from an undergrad working on a senior thesis!?

### ISSUE THREAD

**Issue by critical-nomad** [nychealth/coronavirus-data#176]
Hi folks!!

I am a senior undergrad @ Columbia working on my thesis, and I was wondering if it would be at all possible for a few things: hospitalization by modzcta and death by modzcta over time. My thesis is focusing on mortality and the effects of income and race on it specifically in the city, and this data would be super helpful if it exists. I'm trying to scrounge it up, and its just not working. My method is a time series analysis of this and other metrics, and the crux of it lies with historical data. Thank you SO much!!

**Comment by insidenothing** [comment]
Have you through the commit history for older data?

**Comment by critical-nomad** [comment]
If I am being honest with you, I haven't. Do I have access to this?? It seems the only branch is the main one, and there are no other ones available to me as an end user. To be fair, I started using git hub solely for this project and I am far from a pro.

**Comment by insidenothing** [comment]
By hand is the best way, as time passed the data format changes a little, enough to mess with automation.

**Comment by critical-nomad** [comment]
Word, sounds good!! Is there hospitalization data for modzcta's?? Or is it too specific / laggy for it to be recorded more in depth than for the borough level?

**Comment by insidenothing** [comment]
That I don't know, maybe someone else does.

**Comment by nygeog** [comment]
@critical-nomad 

I have the daily diff's - see here: https://nyc-covid-data-u46xbtaf6a-uk.a.run.app/nyc_covid    but search for Issue's in this repo on DOH's explanations of issues w/ that methodology. They update and corrected data in the summer as data was reconciled. 

I have a sqlite database here: https://nyc-covid-data-u46xbtaf6a-uk.a.run.app/nyc_covid.db

^ These URL's will change so grab this soon or ask me later for the most recent url of the Datasette app I'm hosting. 

Here's the Data Dictionary: 
https://www.dropbox.com/s/lhiq8opfbsa0eh0/nyc_covid_data_dictionary.pdf

Just make sure you cite our work here at Mount Sinai compiling this data. Best of luck. 

Also, as @insidenothing said, have not seen hospitalizations data at MODZTA.

**Comment by mmontesanonyc** [comment]
Thanks for the inquiry.

Per this repository’s [readme](https://github.com/nychealth/coronavirus-data#how-to-use-this-repository), we cannot fulfill custom data requests. However, check back in this repository regularly, as we may continue to enhance our offerings and release new data files, and issues like this help us understand what people are interested in tracking.

**Comment by critical-nomad** [comment]
Thank you so much guys for the help!! I got the nyc_covid.db file, and its AMAZING! However, it does not start tracking deaths or cases until like 07/12/2020. Is there any way I can find the data stretching back further into 2020?? Like around February maybe? I will 10000000% be citing you guys, this would not be possible without you!!

**Comment by mmontesanonyc** [comment]
Hi @critical-nomad, we have added hospitalization rate and death rate by modzcta, by month, since March 2020. Note that data are suppressed in instances of small counts; more notes are available in [Trends/Readme.md](https://github.com/nychealth/coronavirus-data/tree/master/trends).
