### ISSUE TITLE
Is there weekly data of case rate by modzcta prior to August?

### ISSUE THREAD

**Issue by kaymaw** [nychealth/coronavirus-data#179]
Hello! I'm a senior undergrad writing a thesis on case rate by zip code, subway turnstile entries, and income by zip code. Is there weekly data of case rate by modzcta prior to August? I see that there is data on daily cases by borough, but not by zip code. 

Thanks so much!

**Comment by mmontesanonyc** [comment]
Hello, thanks for the question. We do not currently publish trend data by modzcta prior to August.
