### ISSUE TITLE
Question about race/ethnicity categories

### ISSUE THREAD

**Issue by sarah-hf** [nychealth/coronavirus-data#180]
Hello,

Are race/ethnicity categories mutually exclusive? As in, do the White, Black/African-American, and Asian/Pacific-Islander categories include people who are Hispanic/Latino, or no?

Thank you!

**Comment by mmontesanonyc** [comment]
Hello, thanks for the question. 

These categories are mutually exclusive. Hispanic/Latino includes people of any race; all other categories exclude those who identify as Hispanic/Latino. We will update our documentation to clarify this.
