### ISSUE TITLE
percentpositive-by-modzcta.csv

### ISSUE THREAD

**Issue by DataAnalyst2020** [nychealth/coronavirus-data#181]
Forgive me if this has been addressed – For the data on “percentpositive-by-modzcta.csv”, is the zip code based on people who live or based on the tests are completed. For example, if a person living in 10010 get a molecular test in 10011, does this number show up  in Denominator and/or Numerator in 10010 or 10011? Thank you!

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. This is by ZIP Code of residence, and we will clarify in our documentation.
