### ISSUE TITLE
Data Before 11/9/20

### ISSUE THREAD

**Issue by salwanajmi** [nychealth/coronavirus-data#182]
Hello!

I noticed the change in the categorization of the case, hospitalization and death data on November 9th, however I can't seem to find the data prior to this. Would someone mind linking me to where I can find this? Thank you!

**Comment by mmontesanonyc** [comment]
If you visit the [commit history](https://github.com/nychealth/coronavirus-data/commits/master) you can navigate to the repository at any point in its history.
