### ISSUE TITLE
Cumulative data for data-by-modzcta.csv

### ISSUE THREAD

**Issue by nejohnson2** [nychealth/coronavirus-data#183]
IIs there non-cumulative data available for case rate by modzcta?  I'm not entire clear why this data is being published as a cumulative rate, rather than daily rates.  Can I just look at the daily difference to get the non-cumulative rates?  Thanks!

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. Cumulative data are useful to look at total burden or experience. However, trend data is also available in the folder [Trends](https://github.com/nychealth/coronavirus-data/tree/master/trends). It sounds like you're interested in [caserate-by-modzcta.csv](https://github.com/nychealth/coronavirus-data/blob/master/trends/caserate-by-modzcta.csv). These data are weekly (as opposed to daily) to provide greater stability. 

We don't recommend interpreting daily differences in cumulative files as trend data. For why, [see documentation on report date versus date of event](https://github.com/nychealth/coronavirus-data#report-date-versus-date-of-event) or search issues for "report date."

**Comment by nejohnson2** [comment]
Thanks so much for the response.  Very helpful.  Though I have to ask, are caserate-by-modzcta data available prior to 8/8?  It seems like the cumulative case-rate data (i.e data-by-modzcta.csv) are available starting 5/18.

**Comment by mmontesanonyc** [comment]
Correct, while we've been publishing cumulative data since May, we've only been publishing those weekly rates since August.
