### ISSUE TITLE
What constitutes a covid hospitalization, compared to a hospital admitance due to a covid-like-illness?

### ISSUE THREAD

**Issue by kleisman7** [nychealth/coronavirus-data#185]
Hello,

Thanks for all your work on this!

I am confused about the difference between the daily count of hospitalizations as reported in hosp-by-day.csv, and the rate of hospital admissions as reported in covid-like-illness.csv.  I realize that one is a rate per 100,000 people while the other is a count.  

When I re-scale the covid-like-illness city-wide hospital admission data to be a count (assuming a NYC population of about 8340000), I find that in early March 2020, this number is far larger than the count in hosp-by-day (this I can understand), while at the end of March 2020, it is much lower than the count in hosp-by-day (this makes less sense to me). 

Are there ways to be counted in hosp-by-day that would not count towards covid-like-illness?

I would have assumed that in order to be counted in hosp-by-day, one would need to both receive a positive covid test and be admitted to the hospital, and that they would be going to the hospital because they had symptoms of covid, which would also mean they would be counted in covid-like-illness.  Could you clarify this for me?

Thanks again!

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. 

Data in covid-like-illness.csv reflect people who come to the emergency department (emergency room) for covid-like-illness (flu-like symptoms, cough, fever, etc), and those who are subsequently hospitalized following the ED visit. They are likely tested for COVID, but we don't know for sure if they have COVID at the time of admission. These data come to us fast, but are imprecise. 

Data in hosp-by-day.csv reflect people who have been hospitalized (by any pathway, not just via an initial visit to the ED) within 14 days of a COVID diagnosis. These data take longer to receive and produce, but are a more precise look at people who have been hospitalized with COVID.

**Comment by kleisman7** [comment]
Thanks for your quick response!  This is helpful.
