### ISSUE TITLE
Hospitalizations discrepancy btwn. main page & Milestones?

### ISSUE THREAD

**Issue by dd11235** [nychealth/coronavirus-data#188]
Thank you website administrators for all you do!

Are you able to explain what accounts for the discrepancy between the daily hospitalizations data on the main page and in the Github repository and that in the Milestones "Hospitalizations" section (not the "Hospitalization Rate" which I realize comes from NYS as it is labeled such)? Especially the major discrepancy for the dates 3/19-3/21? Also why is 3/22 included at the Milestones Hospitalizations page but not the other page?

To be 100% clear I'm talking about the difference in the Daily Hospitalized Count between that shown here: https://raw.githubusercontent.com/nychealth/coronavirus-data/master/latest/now-data-by-day.csv

And that shown here: https://www1.nyc.gov/site/doh/covid/covid-19-goals.page

And I'm particularly interested in the discrepancy currently for 3/19-3/21.

Also, again, why is 3/22 included at the Milestones Hospitalizations page but not the other page?

Thanks again!

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. 

These are two different datasets. The hospitalization data in this repository, as found in now-data-by-day.csv, is for people hospitalized with a confirmed case of COVID-19. 

According to documentation on the Milestones page, those data reflect people hospitalized following a visit to the emergency department for covid-like illness. 

Those are more comparable to data found in this repository's [covid-like-illness](https://github.com/nychealth/coronavirus-data/tree/master/trends#covid-like-illnesscsv) files. [For more information see this recent issue](https://github.com/nychealth/coronavirus-data/issues/185).
