### ISSUE TITLE
Vaccine data by zip?

### ISSUE THREAD

**Issue by sarah-hf** [nychealth/coronavirus-data#189]
Hi, I see on the DOH website that vaccination data are available by zip: https://www1.nyc.gov/site/doh/covid/covid-19-data-vaccines.page

However, I don't see a way to download this data. Are there plans to make this available on this repository? Or is there somewhere else where the data are accessible?

**Comment by bertrandmartel** [comment]
@sarah-hf Hello, the latest data from the tableau source is available in [this repo](https://github.com/bertrandmartel/covid19-nyc-vaccine-tracker) and a script is running every day in Github action

latest export: https://github.com/bertrandmartel/covid19-nyc-vaccine-tracker/tree/master/deploy/latest
zip data: https://github.com/bertrandmartel/covid19-nyc-vaccine-tracker/blob/master/deploy/latest/geography/Map%20ZIP.csv

**Comment by svfnyc** [comment]
I just copy paste from the site into an excel file. Been doing that since May and keep it all on different tabs.

**Comment by jsonkao** [comment]
@svfnyc would you be open to sharing that data? It'd be super helpful for vaccination research I'm working on

**Comment by svfnyc** [comment]
@jsonkao I don't know that I've saved all the way back to May, and I was only focused on my area (Yorkville) and Lincoln Center.

**Comment by jsonkao** [comment]
@svfnyc got it, thank you

**Comment by mmontesanonyc** [comment]
Hello, [data on NYC's COVID-19 vaccinations are available here](https://github.com/nychealth/covid-vaccine-data).

**Comment by jsonkao** [comment]
Incredible!!!!!!!!! @mmontesanonyc

**Comment by sarah-hf** [comment]
Thanks so much, this is great! For the information by zip, can you please clarify: do these numbers represent people who **live** in each modzcta, or people who **received their doses** in each modzcta?

**Comment by mmontesanonyc** [comment]
@sarah-hf You might find answers in [the vaccine data repository's documentation](https://github.com/nychealth/covid-vaccine-data#zip-codes-and-zip-code-tabulation-areas-zctas).
