### ISSUE TITLE
Neighborhood & Race/ethnicity data

### ISSUE THREAD

**Issue by msp334** [nychealth/coronavirus-data#19]
Thanks for creating this platform and regularly sharing the updated counts. 

I would love to see these data presented by zip code in raw form so that it can linked to existing govt datasets on neighborhood level factors. Currently, I only see tests and positive frequencies by zcta. Are you planning to release hospitalizations, deaths and recovery by zcta as well?

Also, is there any plan to release these data by race/ethnic? For social epidemiologist who examine disparities, this would be crucial information to understand spread and burden in communities of color.

Stay safe everyone.

**Comment by ricky-shin** [comment]
There seems to now be some data regarding the death rate by race/ethnicity in a PDF [here](https://www1.nyc.gov/assets/doh/downloads/pdf/imm/covid-19-deaths-race-ethnicity-04082020-1.pdf). @mmontesanonyc, are there any plans to include this data in this Github?

**Comment by jshenry11963** [comment]
In case you missed this 5/13/20 analysis of nyc zip data: https://www.the-american-interest.com/2020/05/13/the-distribution-of-suffering-and-greed-in-the-pandemic/

**Comment by mmontesanonyc** [comment]
Closed - case, hospitalization, and death counts and rates by race/ethnicity, both citywide as well as borough-specific, plus death rates by race/ethnicity and age, as well as probable death counts by race/ethnicity have been added to this repository.
