### ISSUE TITLE
Question about the variables on tests.csv

### ISSUE THREAD

**Issue by anacarolinamoreno** [nychealth/coronavirus-data#199]
Hi! Quick question about this file: https://github.com/nychealth/coronavirus-data/blob/master/trends/tests.csv

The columns with "TOTAL TESTS" on the name a sum of molecular, antigen and antibody tests? Where can I find data for only the molecular (RT-PCR) tests?

Thanks!

**Comment by mmontesanonyc** [comment]
Hello, thanks for the question. You can find [documentation on that file's column headers here](https://github.com/nychealth/coronavirus-data/tree/master/trends#testscsv). TOTAL_TESTS is the number of people who received a molecular test.

**Comment by anacarolinamoreno** [comment]
Perfect, thank you very much!
