### ISSUE TITLE
Consider appending rows to datasets instead of overwriting the entire table

### ISSUE THREAD

**Issue by chriswhong** [nychealth/coronavirus-data#2]
It would be useful if each update was just a new row or rows appended to each table so users of the data can track changes over time.

Also, using ISO8601 timestamps for the "as of" value would also be helpful for machines reading the dataset.

I'm curious, is there a data standard you are complying with that wants the data in the shape it's currently published in? 

For `summary.csv` this would look like:

```
as_of,cases,total_hospitalized,deaths
2019-03-25T17:28,20011,3922,280
2019-03-26T17:30,23112,4712,364
2019-03-27T17:30,26697,5039,450
2019-03-30T17:30,38087,7741,914
2019-03-31T17:30,41771,8549,1096
```

**Comment by chriswhong** [comment]
Nevermind, it seems these data are here to power the website via AJAX calls: https://www1.nyc.gov/site/doh/covid/covid-19-data.page

**Comment by chriswhong** [comment]
This project has been tracking some of the nyc stats and has a bulk CSV of confirmed cases and deaths over time: https://github.com/trevf/covid19cases-nyc

**Comment by jehiah** [comment]
@chriswhong I've built a script that will iterate all revisions of this repo and build such a delta csv

https://gist.github.com/jehiah/052c5d76dfc3ca6e2dfd0244d16e6650

AS_OF|DATE_OF_INTEREST|NEW_COVID_CASE_COUNT|HOSPITALIZED_CASE_COUNT|DEATH_COUNT
--|-|-:|-:|-:
March 25, 5:30 p.m.|3/2/20|1||
March 25, 5:30 p.m.|3/3/20|2|3|
March 25, 5:30 p.m.|3/4/20|9|3|
March 25, 5:30 p.m.|3/5/20|1|4|
March 25, 5:30 p.m.|3/6/20|8|5|
March 25, 5:30 p.m.|3/7/20|11|9|
March 25, 5:30 p.m.|3/8/20|20|13|
March 25, 5:30 p.m.|3/9/20|53|25|
March 25, 5:30 p.m.|3/10/20|69|42|
March 25, 5:30 p.m.|3/11/20|155|53|
March 25, 5:30 p.m.|3/12/20|350|69|
March 25, 5:30 p.m.|3/13/20|603|123|1
March 25, 5:30 p.m.|3/14/20|601|160|2
March 25, 5:30 p.m.|3/15/20|975|193|5
March 25, 5:30 p.m.|3/16/20|1913|290|9
March 25, 5:30 p.m.|3/17/20|2163|315|7
March 25, 5:30 p.m.|3/18/20|2371|355|16
March 25, 5:30 p.m.|3/19/20|2401|434|19
March 25, 5:30 p.m.|3/20/20|2594|492|37
March 25, 5:30 p.m.|3/21/20|1388|415|30
March 25, 5:30 p.m.|3/22/20|1266|415|33
March 25, 5:30 p.m.|3/23/20|1707|361|49
March 25, 5:30 p.m.|3/24/20|1328|137|53
March 25, 5:30 p.m.|3/25/20|21||18
March 26, 5:00 p.m.|3/12/20|1|0|
March 26, 5:00 p.m.|3/18/20|60|-5|1
March 26, 5:00 p.m.|3/20/20|171|38|1
March 26, 5:00 p.m.|3/22/20|136|22|6
March 26, 5:00 p.m.|3/23/20|423|214|9
March 26, 5:00 p.m.|3/24/20|639|381|4
March 26, 5:00 p.m.|3/25/20|1098|108|50
March 26, 5:00 p.m.|3/26/20|49|2|14
March 27, 5:00 p.m.|3/5/20|1|0|
March 27, 5:00 p.m.|3/13/20|3|-6|
March 27, 5:00 p.m.|3/18/20|81|-35|2
March 27, 5:00 p.m.|3/21/20|130|-52|1
March 27, 5:00 p.m.|3/22/20|87|-32|2
March 27, 5:00 p.m.|3/23/20|155|23|5
March 27, 5:00 p.m.|3/24/20|173|72|7
March 27, 5:00 p.m.|3/25/20|1248|416|7
March 27, 5:00 p.m.|3/26/20|887|93|40
March 27, 5:00 p.m.|3/27/20|32|2|20
March 30, 5:00 p.m.|3/10/20|1|4|
March 30, 5:00 p.m.|3/12/20|3|6|
March 30, 5:00 p.m.|3/18/20|165|62|1
March 30, 5:00 p.m.|3/19/20|198|71|3
March 30, 5:00 p.m.|3/20/20|658|102|4
March 30, 5:00 p.m.|3/21/20|388|113|1
March 30, 5:00 p.m.|3/22/20|482|122|3
March 30, 5:00 p.m.|3/23/20|657|97|10
March 30, 5:00 p.m.|3/24/20|896|48|8
March 30, 5:00 p.m.|3/25/20|573|174|23
March 30, 5:00 p.m.|3/26/20|2070|607|67
March 30, 5:00 p.m.|3/27/20|2814|669|100
March 30, 5:00 p.m.|3/28/20|1717|423|122
March 30, 5:00 p.m.|3/29/20|590|68|94
March 30, 5:00 p.m.|3/30/20|24||14
March 31, 5:00 p.m.|3/12/20|1|2|
March 31, 5:00 p.m.|3/13/20|1|-4|
March 31, 5:00 p.m.|3/24/20|177|18|2
March 31, 5:00 p.m.|3/25/20|269|23|1
March 31, 5:00 p.m.|3/26/20|71|43|14
March 31, 5:00 p.m.|3/27/20|114|98|10
March 31, 5:00 p.m.|3/28/20|287|189|10
March 31, 5:00 p.m.|3/29/20|1325|486|42
March 31, 5:00 p.m.|3/30/20|1217|67|91
March 31, 5:00 p.m.|3/31/20|54||23
04/01/2020, 5:00pm|3/7/20|2|0|
04/01/2020, 5:00pm|3/13/20|3|4|
04/01/2020, 5:00pm|3/18/20|17|37|1
04/01/2020, 5:00pm|3/19/20|38|4|1
04/01/2020, 5:00pm|3/20/20|5|-10|1
04/01/2020, 5:00pm|3/21/20|7|34|1
04/01/2020, 5:00pm|3/23/20|20|66|2
04/01/2020, 5:00pm|3/24/20|161|61|3
04/01/2020, 5:00pm|3/25/20|227|51|2
04/01/2020, 5:00pm|3/26/20|215|45|5
04/01/2020, 5:00pm|3/27/20|107|22|12
04/01/2020, 5:00pm|3/28/20|81|47|16
04/01/2020, 5:00pm|3/29/20|322|137|25
04/01/2020, 5:00pm|3/30/20|1759|577|46
04/01/2020, 5:00pm|3/31/20|899|101|125
04/01/2020, 5:00pm|4/1/20|43||37
04/02/2020, 5:00pm|3/4/20|1|0|
04/02/2020, 5:00pm|3/12/20|1|1|
04/02/2020, 5:00pm|3/13/20|1|0|
04/02/2020, 5:00pm|3/24/20|37|12|1
04/02/2020, 5:00pm|3/25/20|269|15|1
04/02/2020, 5:00pm|3/26/20|205|25|-1
04/02/2020, 5:00pm|3/27/20|302|29|6
04/02/2020, 5:00pm|3/28/20|130|19|10
04/02/2020, 5:00pm|3/29/20|132|48|5
04/02/2020, 5:00pm|3/30/20|531|137|9
04/02/2020, 5:00pm|3/31/20|1239|399|32
04/02/2020, 5:00pm|4/1/20|1004|117|108
04/02/2020, 5:00pm|4/2/20|82||13
04/03/2020, 5:00pm|3/13/20|1|0|
04/03/2020, 5:00pm|3/19/20|18|5|1
04/03/2020, 5:00pm|3/24/20|97|30|3
04/03/2020, 5:00pm|3/25/20|109|36|1
04/03/2020, 5:00pm|3/26/20|419|25|10
04/03/2020, 5:00pm|3/27/20|177|42|12
04/03/2020, 5:00pm|3/28/20|146|37|24
04/03/2020, 5:00pm|3/29/20|221|70|26
04/03/2020, 5:00pm|3/30/20|511|115|31
04/03/2020, 5:00pm|3/31/20|904|194|24
04/03/2020, 5:00pm|4/1/20|1714|450|36
04/03/2020, 5:00pm|4/2/20|1955|113|118
04/03/2020, 5:00pm|4/3/20|63||21
