### ISSUE TITLE
Question about variant-epi-data.csv

### ISSUE THREAD

**Issue by BWMosher** [nychealth/coronavirus-data#200]
Why did counts and rates change all the way back in January in the last commit? It's June.

Also, what do the incomplete markers mean on the last weeks if these weeks are subject to edits?

`01/30/2021,21... → 01/30/2021,23...`

**Comment by BWMosher** [comment]
![20210626_192324](https://user-images.githubusercontent.com/85713845/123528246-12a20f00-d6b4-11eb-98a4-17927c702b0a.jpg)

this is a conditionally formatted picture highlighting the changes between all of the data last two commits (6/17 and 6/24)?

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. The incomplete markers indicate that the most recent data are incomplete and should be interpreted with caution.

Despite this, we occasionally learn more about even older cases. For example, given dramatically reduced case counts now, some older cases of interest are being sequenced. As we learn new information about these cases, we update the reported data accordingly.
