### ISSUE TITLE
Where is the file with data on SARS-CoV-2 variants organized by MODZCTA? 

### ISSUE THREAD

**Issue by TeamOYC** [nychealth/coronavirus-data#202]
Where is the file with data on SARS-CoV-2 variants organized by MODZCTA? I am having trouble locating the file.

**Comment by mmontesanonyc** [comment]
Hi, thanks for the question. There are not published data on variants by MODZCTA in this repository. I see that there's an erroneous reference to MODZCTA-level data in the documentation, which we'll revise.
