### ISSUE TITLE
UHF Neighborhood documentation

### ISSUE THREAD

**Issue by srhrnkn** [nychealth/coronavirus-data#203]
Could you add more documentation for UHF neighborhoods as used in the new 7day-transmission-rate.csv file, and either provide a link to a shapefile or include a shapefile in Geography-resources? (Or if they are built out of modZCTAs, provide a modZCTA-UHF mapping?) Thanks!

**Comment by mmontesanonyc** [comment]
UHF shapefiles and a UHF to zip crosswalk are available [here](https://github.com/nychealth/coronavirus-data/tree/master/Geography-resources/UHF_resources).
