### ISSUE TITLE
No update since 8/8/21

### ISSUE THREAD

**Issue by svfnyc** [nychealth/coronavirus-data#204]
Is this still being updated? I don't see any update since Sun 8/8, which itself seemed incomplete, and now it is after 5:30 on Tue 8/10....

**Comment by mmontesanonyc** [comment]
Updates have resumed. In the future, feel free to [check the agency's COVID-19 data web page](https://www1.nyc.gov/site/doh/covid/covid-19-data.page), where we post a note if there are delays with our regular updates.
