### ISSUE TITLE
Missing updates for 8/9 & 8/10 - change to update schedule?

### ISSUE THREAD

**Issue by jeremydratcliff** [nychealth/coronavirus-data#205]
Hello,

I'm part of the team at @CSSEGISandData and we use your GitHub repository for our borough level data for four of the five boroughs in New York City (we've corresponded before). We noticed that this week there were no updates for August 9 (Monday) or August 10 (Tuesday). Was this just a one-off delay in reporting or is the department changing your update schedule? If that is the case, we would want to include it in our documentation. Thank you!

**Comment by mmontesanonyc** [comment]
Last week's delays were due to one-off technical issues. In the future, feel free to [check the agency's COVID-19 data web page](https://www1.nyc.gov/site/doh/covid/covid-19-data.page), where we post a note if there are delays with regular updates.
