### ISSUE TITLE
Same data as Saturday

### ISSUE THREAD

**Issue by Tatabanya** [nychealth/coronavirus-data#209]
Hi,
Today's data is the same data that was posted on Saturday 9/11/2021.

**Comment by mmontesanonyc** [comment]
Hello, the data were updated yesterday with new data.

**Comment by Tatabanya** [comment]
Hi,

Over the last three days the data for totals has been the same in the totals folder.
By-age
By- boro
By-race
Thanks,
Nora Santiago


Nora Santiago
Urban Policy Analyst
Office of Sustainable Community Planning
Economic Development, Continuing Studies and Government Relations
College of Staten Island
2800 Victory Blvd 2A 301F
Staten Island, NY 10314
718-982-2354

**Comment by mmontesanonyc** [comment]
You can find those data in [by-group.csv](https://github.com/nychealth/coronavirus-data/tree/master/totals#by-groupcsv).
