### ISSUE TITLE
by_age double count?

### ISSUE THREAD

**Issue by esattezza** [nychealth/coronavirus-data#21]
Your binning is off in the by_age table such that I'm not sure whether 75yos are being counted twice, or if there is simply a typo in one of the bin labels:
65-75 years
75 and older years

**Comment by mvfolino68** [comment]
Can you close this

**Comment by DTPOTO** [comment]
Hi @esattezza, I don't know if any one responded to you.   It looks to me that the age group has been 65-74.    All my research has been with 65-74.   I suspect that on the day you look at the age file there was a typo error.   I have done quit a bit of work with the age files in comparing them to census groupings, I am sure that I would have had a problem getting the numbers to match if there was a doubling of the 75 year olds.

**Comment by mmontesanonyc** [comment]
Data are being reported out for 65-74 year olds, and for 75+ year olds.
