### ISSUE TITLE
probable-confirmed-by-boro.csv not updated since 9/11

### ISSUE THREAD

**Issue by jeremydratcliff** [nychealth/coronavirus-data#210]
Hello nychealth team, 

I'm part of the team at @CSSEGISandData and we use your GitHub repository for our borough level data for four of the five boroughs in New York City. We noticed that probable-confirmed-by-boro.csv has not updated since September 11 while other files in the repository (such as group-cases-by-boro.csv) have updated today (9/14). Is probable-confirmed-by-boro.csv being retired or moved to a new update schedule?

Thank you very much in advance for the help.

**Comment by Tatabanya** [comment]
Yes, since Saturday the files in the Total folder, by-age, by-boro, by-race have not been updated! Please let me know if you will stop reporting this data. I use it to update the daily Covid Dashboard.

**Comment by mmontesanonyc** [comment]
Hi, thanks for the query. We've some changes to files and have retired a few. [We've added details to our changelog here](https://github.com/nychealth/coronavirus-data#update-on-september-14-2021).
