### ISSUE TITLE
Child Deaths

### ISSUE THREAD

**Issue by BethPathak** [nychealth/coronavirus-data#211]
Hey guys!

Your new "by group" file does NOT include actual death counts by age - please restore these valuable data, which were previously available in the "by age" file (which has not been updated).

Thank you!!
Beth Pathak, Director
The COVKID Project

**Comment by mmontesanonyc** [comment]
Hello, can you please clarify exactly what data you are used to getting from by-age that you are not finding in by-group?

**Comment by BethPathak** [comment]
Sure – in the totals by age file, there are death COUNTS. 

 

In the by-group file, there are only death RATES – I need the counts.

 

Thanks!

 

Elizabeth Pathak, PhD, President

Women’s Institute for Independent Social Enquiry

 <http://www.wiise-usa.org/> www.wiise-usa.org  @wiise_usa

 <http://www.covkidproject.org/> www.covkidproject.org @covkidproject

@bethpathak

**Comment by mmontesanonyc** [comment]
As in by-age.csv, the field ```DEATH_COUNT``` in by-group.csv contains death counts for the 0-17 age group.

**Comment by BethPathak** [comment]
I found it – it was off screen and I didn’t see the scroll bar at the bottom. Thanks for the reply.
