### ISSUE TITLE
Missing UHF associated ZIP codes

### ISSUE THREAD

**Issue by fazilkhan** [nychealth/coronavirus-data#212]
Hi,

The ZIP codes 10004 and 11693 are missing from the UHF to ZCTA file "uhf-to-zip crosswalk.xlsx" here: https://github.com/nychealth/coronavirus-data/tree/master/Geography-resources/UHF_resources

The MOD_ZCTA file mentions both of these ZIPs but this UHF excel does not. Please add them to their respective UHF neighborhood. Thanks!

**Comment by mmontesanonyc** [comment]
[Updated](https://github.com/nychealth/coronavirus-data/blob/master/Geography-resources/UHF_resources/uhf-to-zip%20crosswalk.csv).
