### ISSUE TITLE
Error? on the 10/30/2021 data: coronavirus-data/trends/testrate-by-modzcta.csv

### ISSUE THREAD

**Issue by DataAnalyst2020** [nychealth/coronavirus-data#217]
Hello. 10/30/2021 numbers seem to be very different from the rest of the days (e.g. TESTRATE_CITY for 10/23 was 5016.64, but 10/30 was 293). Could you please confirm that this is accurate? Or did the definition of the data changed? Thanks!

**Comment by mmontesanonyc** [comment]
Hi, thanks for catching that. Because of some back-end issues last week, the 10/30 data were incomplete. We've updated the weekly/Thursday files today, which include backfilled data for the week of 10/30.
