### ISSUE TITLE
11/19 decrease in number of unvaccinated cases

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/coronavirus-data#218]
We [received in inquiry](https://github.com/nychealth/coronavirus-data/commit/76c663d7da3d98e2db14dd200f6c21f40ecfaabe#diff-4471dcbe1ba8917917076adb0d9a51ba786981437db266c82af8e867b2e965bb) asking why the 11/18 update saw a decrease in the count of deaths among unvaccinated people, in the file [breakthrough-summary.csv](https://github.com/nychealth/coronavirus-data/blob/master/latest/breakthrough-summary.csv).

The count for the cases, hospitalizations, and deaths among the unvaccinated in the breakthrough-summary file mistakenly included some diagnosed prior to Jan 17 2021. This was corrected starting in the update on 11/19.  The counts among the vaccinated weren’t affected; these were always limited to Jan 17 and after.

**Comment by dancingRNA** [comment]
Thank you so much! I really appreciate you taking the time to respond and for all of your efforts on this project. 
Best wishes, -Trinna
