### ISSUE TITLE
Errors in HOSPITALIZED_COUNT in last update of data-by-day.csv

### ISSUE THREAD

**Issue by hjstein** [nychealth/coronavirus-data#219]
There appears to be an error in the last commit of `trends/data-by-day.csv`.  Comparing the 12/1 version:

> https://github.com/hjstein/coronavirus-data/blob/019c84edd82f13a8cae3dca861f729bb25fd553a/trends/data-by-day.csv

to the 12/2 version:

> https://github.com/hjstein/coronavirus-data/blob/f65e89990d413b75e97ab8d01fe8ad6171d6f0c2/trends/data-by-day.csv

you can see that the `HOSPITALIZED_COUNT` column for the last two updates were largely the same through 1/15/2021, and then started changing wildly.  It looks like there's an error in the last update.

Date | HOSPITALIZED_COUNT 12/1 | HOSPITALIZED_COUNT 12/2 | Difference
-- | -- | -- | --
2/29/2020 | 1 | 1 | 0
3/1/2020 | 1 | 1 | 0
3/2/2020 | 2 | 2 | 0
3/3/2020 | 7 | 7 | 0
3/4/2020 | 2 | 2 | 0
3/5/2020 | 14 | 14 | 0
3/6/2020 | 8 | 8 | 0
3/7/2020 | 8 | 8 | 0
3/8/2020 | 18 | 18 | 0
3/9/2020 | 37 | 37 | 0
3/10/2020 | 58 | 58 | 0
3/11/2020 | 79 | 79 | 0
3/12/2020 | 107 | 107 | 0
3/13/2020 | 152 | 152 | 0
3/14/2020 | 176 | 176 | 0
3/15/2020 | 210 | 210 | 0
3/16/2020 | 340 | 340 | 0
3/17/2020 | 387 | 387 | 0
3/18/2020 | 494 | 494 | 0
3/19/2020 | 634 | 633 | -1
3/20/2020 | 740 | 740 | 0
3/21/2020 | 740 | 740 | 0
3/22/2020 | 774 | 774 | 0
3/23/2020 | 1142 | 1142 | 0
3/24/2020 | 1304 | 1304 | 0
3/25/2020 | 1421 | 1421 | 0
3/26/2020 | 1534 | 1534 | 0
3/27/2020 | 1569 | 1569 | 0
3/28/2020 | 1382 | 1382 | 0
3/29/2020 | 1502 | 1502 | 0
3/30/2020 | 1848 | 1848 | 0
3/31/2020 | 1783 | 1783 | 0
4/1/2020 | 1729 | 1728 | -1
4/2/2020 | 1661 | 1662 | 1
4/3/2020 | 1707 | 1707 | 0
4/4/2020 | 1444 | 1444 | 0
4/5/2020 | 1400 | 1400 | 0
4/6/2020 | 1741 | 1741 | 0
4/7/2020 | 1574 | 1574 | 0
4/8/2020 | 1539 | 1539 | 0
4/9/2020 | 1343 | 1343 | 0
4/10/2020 | 1284 | 1284 | 0
4/11/2020 | 1038 | 1038 | 0
4/12/2020 | 949 | 949 | 0
4/13/2020 | 1144 | 1144 | 0
4/14/2020 | 978 | 978 | 0
4/15/2020 | 858 | 858 | 0
4/16/2020 | 777 | 777 | 0
4/17/2020 | 788 | 788 | 0
4/18/2020 | 585 | 585 | 0
4/19/2020 | 533 | 533 | 0
4/20/2020 | 630 | 630 | 0
4/21/2020 | 585 | 585 | 0
4/22/2020 | 512 | 512 | 0
4/23/2020 | 443 | 443 | 0
4/24/2020 | 462 | 462 | 0
4/25/2020 | 324 | 324 | 0
4/26/2020 | 312 | 312 | 0
4/27/2020 | 370 | 370 | 0
4/28/2020 | 350 | 350 | 0
4/29/2020 | 309 | 309 | 0
4/30/2020 | 253 | 253 | 0
5/1/2020 | 262 | 262 | 0
5/2/2020 | 205 | 205 | 0
5/3/2020 | 215 | 215 | 0
5/4/2020 | 238 | 238 | 0
5/5/2020 | 212 | 211 | -1
5/6/2020 | 212 | 212 | 0
5/7/2020 | 177 | 177 | 0
5/8/2020 | 170 | 170 | 0
5/9/2020 | 122 | 122 | 0
5/10/2020 | 104 | 104 | 0
5/11/2020 | 180 | 180 | 0
5/12/2020 | 112 | 112 | 0
5/13/2020 | 128 | 128 | 0
5/14/2020 | 142 | 142 | 0
5/15/2020 | 126 | 126 | 0
5/16/2020 | 91 | 91 | 0
5/17/2020 | 81 | 81 | 0
5/18/2020 | 114 | 114 | 0
5/19/2020 | 115 | 115 | 0
5/20/2020 | 79 | 79 | 0
5/21/2020 | 84 | 84 | 0
5/22/2020 | 101 | 101 | 0
5/23/2020 | 75 | 75 | 0
5/24/2020 | 87 | 87 | 0
5/25/2020 | 78 | 78 | 0
5/26/2020 | 75 | 75 | 0
5/27/2020 | 76 | 76 | 0
5/28/2020 | 80 | 80 | 0
5/29/2020 | 85 | 85 | 0
5/30/2020 | 54 | 54 | 0
5/31/2020 | 60 | 60 | 0
6/1/2020 | 82 | 82 | 0
6/2/2020 | 63 | 63 | 0
6/3/2020 | 75 | 75 | 0
6/4/2020 | 75 | 75 | 0
6/5/2020 | 55 | 55 | 0
6/6/2020 | 37 | 37 | 0
6/7/2020 | 54 | 54 | 0
6/8/2020 | 62 | 62 | 0
6/9/2020 | 65 | 65 | 0
6/10/2020 | 63 | 63 | 0
6/11/2020 | 50 | 50 | 0
6/12/2020 | 53 | 53 | 0
6/13/2020 | 34 | 34 | 0
6/14/2020 | 46 | 46 | 0
6/15/2020 | 53 | 53 | 0
6/16/2020 | 61 | 61 | 0
6/17/2020 | 50 | 50 | 0
6/18/2020 | 58 | 58 | 0
6/19/2020 | 45 | 45 | 0
6/20/2020 | 27 | 27 | 0
6/21/2020 | 43 | 43 | 0
6/22/2020 | 50 | 50 | 0
6/23/2020 | 44 | 44 | 0
6/24/2020 | 53 | 53 | 0
6/25/2020 | 42 | 42 | 0
6/26/2020 | 33 | 33 | 0
6/27/2020 | 42 | 42 | 0
6/28/2020 | 32 | 32 | 0
6/29/2020 | 48 | 48 | 0
6/30/2020 | 45 | 45 | 0
7/1/2020 | 38 | 38 | 0
7/2/2020 | 46 | 46 | 0
7/3/2020 | 30 | 30 | 0
7/4/2020 | 30 | 30 | 0
7/5/2020 | 28 | 28 | 0
7/6/2020 | 54 | 54 | 0
7/7/2020 | 47 | 47 | 0
7/8/2020 | 34 | 34 | 0
7/9/2020 | 46 | 46 | 0
7/10/2020 | 44 | 44 | 0
7/11/2020 | 33 | 33 | 0
7/12/2020 | 26 | 26 | 0
7/13/2020 | 49 | 49 | 0
7/14/2020 | 43 | 43 | 0
7/15/2020 | 44 | 44 | 0
7/16/2020 | 35 | 35 | 0
7/17/2020 | 49 | 49 | 0
7/18/2020 | 27 | 27 | 0
7/19/2020 | 38 | 38 | 0
7/20/2020 | 38 | 38 | 0
7/21/2020 | 24 | 24 | 0
7/22/2020 | 40 | 40 | 0
7/23/2020 | 32 | 32 | 0
7/24/2020 | 40 | 40 | 0
7/25/2020 | 35 | 35 | 0
7/26/2020 | 25 | 25 | 0
7/27/2020 | 39 | 39 | 0
7/28/2020 | 37 | 37 | 0
7/29/2020 | 30 | 30 | 0
7/30/2020 | 37 | 37 | 0
7/31/2020 | 34 | 34 | 0
8/1/2020 | 27 | 27 | 0
8/2/2020 | 33 | 33 | 0
8/3/2020 | 38 | 38 | 0
8/4/2020 | 32 | 32 | 0
8/5/2020 | 39 | 39 | 0
8/6/2020 | 34 | 34 | 0
8/7/2020 | 23 | 23 | 0
8/8/2020 | 20 | 20 | 0
8/9/2020 | 27 | 27 | 0
8/10/2020 | 41 | 41 | 0
8/11/2020 | 25 | 25 | 0
8/12/2020 | 31 | 31 | 0
8/13/2020 | 38 | 38 | 0
8/14/2020 | 38 | 38 | 0
8/15/2020 | 23 | 23 | 0
8/16/2020 | 21 | 21 | 0
8/17/2020 | 34 | 34 | 0
8/18/2020 | 39 | 39 | 0
8/19/2020 | 35 | 35 | 0
8/20/2020 | 36 | 36 | 0
8/21/2020 | 31 | 31 | 0
8/22/2020 | 27 | 27 | 0
8/23/2020 | 21 | 21 | 0
8/24/2020 | 36 | 36 | 0
8/25/2020 | 42 | 42 | 0
8/26/2020 | 27 | 27 | 0
8/27/2020 | 30 | 30 | 0
8/28/2020 | 22 | 22 | 0
8/29/2020 | 22 | 22 | 0
8/30/2020 | 20 | 20 | 0
8/31/2020 | 42 | 42 | 0
9/1/2020 | 20 | 20 | 0
9/2/2020 | 27 | 27 | 0
9/3/2020 | 18 | 18 | 0
9/4/2020 | 32 | 32 | 0
9/5/2020 | 22 | 22 | 0
9/6/2020 | 31 | 31 | 0
9/7/2020 | 20 | 20 | 0
9/8/2020 | 27 | 27 | 0
9/9/2020 | 32 | 32 | 0
9/10/2020 | 25 | 25 | 0
9/11/2020 | 32 | 32 | 0
9/12/2020 | 11 | 11 | 0
9/13/2020 | 17 | 17 | 0
9/14/2020 | 32 | 32 | 0
9/15/2020 | 30 | 30 | 0
9/16/2020 | 45 | 45 | 0
9/17/2020 | 34 | 34 | 0
9/18/2020 | 35 | 35 | 0
9/19/2020 | 21 | 21 | 0
9/20/2020 | 21 | 21 | 0
9/21/2020 | 28 | 28 | 0
9/22/2020 | 33 | 33 | 0
9/23/2020 | 38 | 38 | 0
9/24/2020 | 41 | 41 | 0
9/25/2020 | 46 | 46 | 0
9/26/2020 | 27 | 27 | 0
9/27/2020 | 35 | 35 | 0
9/28/2020 | 38 | 38 | 0
9/29/2020 | 50 | 50 | 0
9/30/2020 | 51 | 51 | 0
10/1/2020 | 41 | 40 | -1
10/2/2020 | 49 | 49 | 0
10/3/2020 | 24 | 24 | 0
10/4/2020 | 44 | 44 | 0
10/5/2020 | 56 | 56 | 0
10/6/2020 | 47 | 47 | 0
10/7/2020 | 45 | 45 | 0
10/8/2020 | 46 | 46 | 0
10/9/2020 | 54 | 54 | 0
10/10/2020 | 37 | 37 | 0
10/11/2020 | 47 | 47 | 0
10/12/2020 | 51 | 51 | 0
10/13/2020 | 49 | 49 | 0
10/14/2020 | 58 | 58 | 0
10/15/2020 | 74 | 74 | 0
10/16/2020 | 49 | 49 | 0
10/17/2020 | 34 | 34 | 0
10/18/2020 | 40 | 40 | 0
10/19/2020 | 68 | 68 | 0
10/20/2020 | 71 | 71 | 0
10/21/2020 | 52 | 52 | 0
10/22/2020 | 53 | 53 | 0
10/23/2020 | 59 | 59 | 0
10/24/2020 | 46 | 46 | 0
10/25/2020 | 44 | 44 | 0
10/26/2020 | 55 | 55 | 0
10/27/2020 | 46 | 46 | 0
10/28/2020 | 44 | 44 | 0
10/29/2020 | 59 | 59 | 0
10/30/2020 | 58 | 58 | 0
10/31/2020 | 47 | 47 | 0
11/1/2020 | 53 | 53 | 0
11/2/2020 | 62 | 62 | 0
11/3/2020 | 75 | 75 | 0
11/4/2020 | 66 | 66 | 0
11/5/2020 | 82 | 82 | 0
11/6/2020 | 63 | 63 | 0
11/7/2020 | 58 | 58 | 0
11/8/2020 | 63 | 63 | 0
11/9/2020 | 78 | 78 | 0
11/10/2020 | 87 | 87 | 0
11/11/2020 | 97 | 97 | 0
11/12/2020 | 79 | 79 | 0
11/13/2020 | 90 | 90 | 0
11/14/2020 | 98 | 98 | 0
11/15/2020 | 88 | 88 | 0
11/16/2020 | 122 | 122 | 0
11/17/2020 | 101 | 101 | 0
11/18/2020 | 117 | 117 | 0
11/19/2020 | 131 | 131 | 0
11/20/2020 | 131 | 131 | 0
11/21/2020 | 119 | 119 | 0
11/22/2020 | 114 | 114 | 0
11/23/2020 | 147 | 147 | 0
11/24/2020 | 129 | 129 | 0
11/25/2020 | 139 | 139 | 0
11/26/2020 | 153 | 153 | 0
11/27/2020 | 156 | 156 | 0
11/28/2020 | 124 | 124 | 0
11/29/2020 | 164 | 164 | 0
11/30/2020 | 187 | 187 | 0
12/1/2020 | 203 | 203 | 0
12/2/2020 | 169 | 169 | 0
12/3/2020 | 207 | 207 | 0
12/4/2020 | 179 | 179 | 0
12/5/2020 | 176 | 176 | 0
12/6/2020 | 175 | 175 | 0
12/7/2020 | 222 | 221 | -1
12/8/2020 | 221 | 221 | 0
12/9/2020 | 274 | 274 | 0
12/10/2020 | 241 | 240 | -1
12/11/2020 | 247 | 247 | 0
12/12/2020 | 207 | 207 | 0
12/13/2020 | 225 | 225 | 0
12/14/2020 | 259 | 259 | 0
12/15/2020 | 232 | 231 | -1
12/16/2020 | 212 | 212 | 0
12/17/2020 | 227 | 227 | 0
12/18/2020 | 273 | 273 | 0
12/19/2020 | 236 | 236 | 0
12/20/2020 | 239 | 239 | 0
12/21/2020 | 327 | 327 | 0
12/22/2020 | 283 | 283 | 0
12/23/2020 | 300 | 300 | 0
12/24/2020 | 273 | 273 | 0
12/25/2020 | 265 | 265 | 0
12/26/2020 | 267 | 267 | 0
12/27/2020 | 244 | 244 | 0
12/28/2020 | 347 | 345 | -2
12/29/2020 | 318 | 318 | 0
12/30/2020 | 313 | 313 | 0
12/31/2020 | 280 | 280 | 0
1/1/2021 | 302 | 300 | -2
1/2/2021 | 322 | 322 | 0
1/3/2021 | 299 | 299 | 0
1/4/2021 | 403 | 403 | 0
1/5/2021 | 347 | 347 | 0
1/6/2021 | 376 | 376 | 0
1/7/2021 | 361 | 360 | -1
1/8/2021 | 352 | 352 | 0
1/9/2021 | 325 | 325 | 0
1/10/2021 | 305 | 305 | 0
1/11/2021 | 401 | 401 | 0
1/12/2021 | 389 | 389 | 0
1/13/2021 | 428 | 427 | -1
1/14/2021 | 434 | 432 | -2
1/15/2021 | 392 | 386 | -6
1/16/2021 | 367 | 361 | -6
1/17/2021 | 334 | 332 | -2
1/18/2021 | 439 | 436 | -3
1/19/2021 | 385 | 373 | -12
1/20/2021 | 364 | 362 | -2
1/21/2021 | 416 | 404 | -12
1/22/2021 | 431 | 411 | -20
1/23/2021 | 322 | 310 | -12
1/24/2021 | 337 | 325 | -12
1/25/2021 | 403 | 385 | -18
1/26/2021 | 367 | 354 | -13
1/27/2021 | 419 | 400 | -19
1/28/2021 | 391 | 319 | -72
1/29/2021 | 401 | 231 | -170
1/30/2021 | 266 | 137 | -129
1/31/2021 | 304 | 183 | -121
2/1/2021 | 288 | 234 | -54
2/2/2021 | 404 | 281 | -123
2/3/2021 | 442 | 175 | -267
2/4/2021 | 432 | 156 | -276
2/5/2021 | 441 | 107 | -334
2/6/2021 | 364 | 134 | -230
2/7/2021 | 311 | 192 | -119
2/8/2021 | 393 | 172 | -221
2/9/2021 | 397 | 107 | -290
2/10/2021 | 363 | 77 | -286
2/11/2021 | 321 | 79 | -242
2/12/2021 | 345 | 93 | -252
2/13/2021 | 280 | 116 | -164
2/14/2021 | 248 | 80 | -168
2/15/2021 | 324 | 62 | -262
2/16/2021 | 352 | 56 | -296
2/17/2021 | 292 | 40 | -252
2/18/2021 | 262 | 43 | -219
2/19/2021 | 306 | 63 | -243
2/20/2021 | 298 | 44 | -254
2/21/2021 | 271 | 33 | -238
2/22/2021 | 350 | 35 | -315
2/23/2021 | 328 | 37 | -291
2/24/2021 | 355 | 39 | -316
2/25/2021 | 292 | 35 | -257
2/26/2021 | 329 | 37 | -292
2/27/2021 | 244 | 22 | -222
2/28/2021 | 244 | 18 | -226
3/1/2021 | 325 | 30 | -295
3/2/2021 | 273 | 39 | -234
3/3/2021 | 306 | 23 | -283
3/4/2021 | 299 | 29 | -270
3/5/2021 | 258 | 24 | -234
3/6/2021 | 243 | 29 | -214
3/7/2021 | 249 | 32 | -217
3/8/2021 | 295 | 36 | -259
3/9/2021 | 282 | 29 | -253
3/10/2021 | 282 | 31 | -251
3/11/2021 | 294 | 34 | -260
3/12/2021 | 293 | 34 | -259
3/13/2021 | 220 | 21 | -199
3/14/2021 | 252 | 20 | -232
3/15/2021 | 292 | 31 | -261
3/16/2021 | 248 | 20 | -228
3/17/2021 | 280 | 27 | -253
3/18/2021 | 305 | 34 | -271
3/19/2021 | 261 | 42 | -219
3/20/2021 | 261 | 26 | -235
3/21/2021 | 267 | 33 | -234
3/22/2021 | 328 | 33 | -295
3/23/2021 | 279 | 37 | -242
3/24/2021 | 293 | 22 | -271
3/25/2021 | 310 | 32 | -278
3/26/2021 | 313 | 34 | -279
3/27/2021 | 260 | 20 | -240
3/28/2021 | 206 | 20 | -186
3/29/2021 | 304 | 48 | -256
3/30/2021 | 263 | 25 | -238
3/31/2021 | 289 | 27 | -262
4/1/2021 | 265 | 22 | -243
4/2/2021 | 262 | 34 | -228
4/3/2021 | 234 | 15 | -219
4/4/2021 | 215 | 24 | -191
4/5/2021 | 265 | 24 | -241
4/6/2021 | 229 | 14 | -215
4/7/2021 | 220 | 17 | -203
4/8/2021 | 216 | 27 | -189
4/9/2021 | 204 | 15 | -189
4/10/2021 | 189 | 13 | -176
4/11/2021 | 160 | 16 | -144
4/12/2021 | 201 | 17 | -184
4/13/2021 | 202 | 20 | -182
4/14/2021 | 195 | 14 | -181
4/15/2021 | 219 | 24 | -195
4/16/2021 | 196 | 23 | -173
4/17/2021 | 164 | 19 | -145
4/18/2021 | 166 | 12 | -154
4/19/2021 | 173 | 23 | -150
4/20/2021 | 155 | 15 | -140
4/21/2021 | 114 | 7 | -107
4/22/2021 | 161 | 15 | -146
4/23/2021 | 155 | 12 | -143
4/24/2021 | 104 | 9 | -95
4/25/2021 | 120 | 16 | -104
4/26/2021 | 144 | 8 | -136
4/27/2021 | 115 | 12 | -103
4/28/2021 | 127 | 14 | -113
4/29/2021 | 115 | 11 | -104
4/30/2021 | 95 | 8 | -87
5/1/2021 | 79 | 10 | -69
5/2/2021 | 72 | 14 | -58
5/3/2021 | 88 | 8 | -80
5/4/2021 | 95 | 16 | -79
5/5/2021 | 76 | 9 | -67
5/6/2021 | 81 | 9 | -72
5/7/2021 | 72 | 5 | -67
5/8/2021 | 62 | 5 | -57
5/9/2021 | 62 | 6 | -56
5/10/2021 | 70 | 3 | -67
5/11/2021 | 69 | 8 | -61
5/12/2021 | 62 | 5 | -57
5/13/2021 | 66 | 4 | -62
5/14/2021 | 69 | 4 | -65
5/15/2021 | 39 | 3 | -36
5/16/2021 | 41 | 2 | -39
5/17/2021 | 72 | 7 | -65
5/18/2021 | 52 | 5 | -47
5/19/2021 | 58 | 8 | -50
5/20/2021 | 64 | 4 | -60
5/21/2021 | 52 | 4 | -48
5/22/2021 | 35 | 5 | -30
5/23/2021 | 45 | 4 | -41
5/24/2021 | 35 | 5 | -30
5/25/2021 | 40 | 7 | -33
5/26/2021 | 33 | 1 | -32
5/27/2021 | 45 | 2 | -43
5/28/2021 | 35 | 6 | -29
5/29/2021 | 25 | 2 | -23
5/30/2021 | 25 | 5 | -20
5/31/2021 | 19 | 1 | -18
6/1/2021 | 33 | 1 | -32
6/2/2021 | 44 | 1 | -43
6/3/2021 | 30 | 3 | -27
6/4/2021 | 23 | 2 | -21
6/5/2021 | 17 | 3 | -14
6/6/2021 | 25 | 3 | -22
6/7/2021 | 31 | 2 | -29
6/8/2021 | 38 | 4 | -34
6/9/2021 | 24 | 1 | -23
6/10/2021 | 25 | 5 | -20
6/11/2021 | 25 | 1 | -24
6/12/2021 | 22 | 2 | -20
6/13/2021 | 30 | 1 | -29
6/14/2021 | 25 | 4 | -21
6/15/2021 | 25 | 1 | -24
6/16/2021 | 23 | 1 | -22
6/17/2021 | 30 | 2 | -28
6/18/2021 | 18 | 3 | -15
6/19/2021 | 13 | 0 | -13
6/20/2021 | 25 | 1 | -24
6/21/2021 | 29 | 2 | -27
6/22/2021 | 33 | 5 | -28
6/23/2021 | 23 | 2 | -21
6/24/2021 | 14 | 0 | -14
6/25/2021 | 18 | 2 | -16
6/26/2021 | 18 | 0 | -18
6/27/2021 | 23 | 2 | -21
6/28/2021 | 25 | 2 | -23
6/29/2021 | 23 | 1 | -22
6/30/2021 | 21 | 1 | -20
7/1/2021 | 31 | 0 | -31
7/2/2021 | 36 | 3 | -33
7/3/2021 | 20 | 1 | -19
7/4/2021 | 21 | 3 | -18
7/5/2021 | 15 | 3 | -12
7/6/2021 | 23 | 2 | -21
7/7/2021 | 23 | 3 | -20
7/8/2021 | 24 | 3 | -21
7/9/2021 | 37 | 1 | -36
7/10/2021 | 17 | 2 | -15
7/11/2021 | 27 | 4 | -23
7/12/2021 | 24 | 2 | -22
7/13/2021 | 25 | 3 | -22
7/14/2021 | 47 | 1 | -46
7/15/2021 | 27 | 0 | -27
7/16/2021 | 36 | 1 | -35
7/17/2021 | 36 | 5 | -31
7/18/2021 | 37 | 5 | -32
7/19/2021 | 50 | 4 | -46
7/20/2021 | 52 | 3 | -49
7/21/2021 | 41 | 4 | -37
7/22/2021 | 51 | 4 | -47
7/23/2021 | 47 | 4 | -43
7/24/2021 | 42 | 6 | -36
7/25/2021 | 41 | 1 | -40
7/26/2021 | 58 | 5 | -53
7/27/2021 | 71 | 4 | -67
7/28/2021 | 74 | 3 | -71
7/29/2021 | 74 | 11 | -63
7/30/2021 | 78 | 4 | -74
7/31/2021 | 67 | 4 | -63
8/1/2021 | 47 | 3 | -44
8/2/2021 | 70 | 5 | -65
8/3/2021 | 94 | 4 | -90
8/4/2021 | 84 | 9 | -75
8/5/2021 | 88 | 8 | -80
8/6/2021 | 113 | 10 | -103
8/7/2021 | 84 | 5 | -79
8/8/2021 | 96 | 6 | -90
8/9/2021 | 128 | 8 | -120
8/10/2021 | 117 | 10 | -107
8/11/2021 | 136 | 8 | -128
8/12/2021 | 115 | 4 | -111
8/13/2021 | 136 | 7 | -129
8/14/2021 | 90 | 7 | -83
8/15/2021 | 106 | 11 | -95
8/16/2021 | 122 | 9 | -113
8/17/2021 | 128 | 7 | -121
8/18/2021 | 112 | 8 | -104
8/19/2021 | 91 | 13 | -78
8/20/2021 | 113 | 11 | -102
8/21/2021 | 112 | 10 | -102
8/22/2021 | 102 | 10 | -92
8/23/2021 | 112 | 8 | -104
8/24/2021 | 101 | 6 | -95
8/25/2021 | 107 | 9 | -98
8/26/2021 | 102 | 6 | -96
8/27/2021 | 102 | 10 | -92
8/28/2021 | 78 | 5 | -73
8/29/2021 | 86 | 7 | -79
8/30/2021 | 120 | 8 | -112
8/31/2021 | 119 | 10 | -109
9/1/2021 | 120 | 10 | -110
9/2/2021 | 91 | 8 | -83
9/3/2021 | 74 | 8 | -66
9/4/2021 | 100 | 8 | -92
9/5/2021 | 71 | 15 | -56
9/6/2021 | 74 | 5 | -69
9/7/2021 | 106 | 5 | -101
9/8/2021 | 95 | 8 | -87
9/9/2021 | 92 | 7 | -85
9/10/2021 | 93 | 7 | -86
9/11/2021 | 80 | 6 | -74
9/12/2021 | 86 | 3 | -83
9/13/2021 | 98 | 8 | -90
9/14/2021 | 79 | 10 | -69
9/15/2021 | 92 | 11 | -81
9/16/2021 | 81 | 4 | -77
9/17/2021 | 81 | 7 | -74
9/18/2021 | 83 | 9 | -74
9/19/2021 | 70 | 5 | -65
9/20/2021 | 92 | 8 | -84
9/21/2021 | 80 | 8 | -72
9/22/2021 | 93 | 11 | -82
9/23/2021 | 88 | 2 | -86
9/24/2021 | 79 | 10 | -69
9/25/2021 | 63 | 3 | -60
9/26/2021 | 50 | 5 | -45
9/27/2021 | 71 | 7 | -64
9/28/2021 | 61 | 5 | -56
9/29/2021 | 61 | 3 | -58
9/30/2021 | 56 | 3 | -53
10/1/2021 | 81 | 5 | -76
10/2/2021 | 58 | 3 | -55
10/3/2021 | 62 | 0 | -62
10/4/2021 | 74 | 6 | -68
10/5/2021 | 67 | 3 | -64
10/6/2021 | 60 | 4 | -56
10/7/2021 | 60 | 6 | -54
10/8/2021 | 41 | 2 | -39
10/9/2021 | 68 | 9 | -59
10/10/2021 | 46 | 3 | -43
10/11/2021 | 50 | 4 | -46
10/12/2021 | 46 | 4 | -42
10/13/2021 | 69 | 7 | -62
10/14/2021 | 46 | 2 | -44
10/15/2021 | 53 | 7 | -46
10/16/2021 | 49 | 1 | -48
10/17/2021 | 47 | 7 | -40
10/18/2021 | 51 | 3 | -48
10/19/2021 | 47 | 6 | -41
10/20/2021 | 51 | 4 | -47
10/21/2021 | 44 | 7 | -37
10/22/2021 | 43 | 5 | -38
10/23/2021 | 43 | 4 | -39
10/24/2021 | 41 | 2 | -39
10/25/2021 | 36 | 4 | -32
10/26/2021 | 39 | 1 | -38
10/27/2021 | 42 | 9 | -33
10/28/2021 | 34 | 3 | -31
10/29/2021 | 27 | 2 | -25
10/30/2021 | 24 | 1 | -23
10/31/2021 | 28 | 5 | -23
11/1/2021 | 37 | 3 | -34
11/2/2021 | 42 | 2 | -40
11/3/2021 | 48 | 5 | -43
11/4/2021 | 36 | 2 | -34
11/5/2021 | 27 | 2 | -25
11/6/2021 | 34 | 1 | -33
11/7/2021 | 32 | 4 | -28
11/8/2021 | 45 | 4 | -41
11/9/2021 | 31 | 4 | -27
11/10/2021 | 42 | 5 | -37
11/11/2021 | 44 | 10 | -34
11/12/2021 | 38 | 3 | -35
11/13/2021 | 32 | 0 | -32
11/14/2021 | 33 | 4 | -29
11/15/2021 | 40 | 2 | -38
11/16/2021 | 35 | 4 | -31
11/17/2021 | 47 | 5 | -42
11/18/2021 | 43 | 8 | -35
11/19/2021 | 39 | 5 | -34
11/20/2021 | 42 | 9 | -33
11/21/2021 | 34 | 5 | -29
11/22/2021 | 44 | 17 | -27
11/23/2021 | 45 | 17 | -28
11/24/2021 | 45 | 27 | -18
11/25/2021 | 47 | 25 | -22
11/26/2021 | 44 | 30 | -14
11/27/2021 | 37 | 23 | -14
11/28/2021 | 16 | 29 | 13

**Comment by mmontesanonyc** [comment]
Thanks so much for the well-documented issue! These issues should be fixed with the[ 12/3 data update](https://github.com/nychealth/coronavirus-data/commit/7efb59141803843cae86e17317218aca110cb650).

**Comment by hjstein** [comment]
So you're not going to fix the history?  I'd appreciate it if you could use `git reset` to remove the bad update & replace it with the correct 12/2 data.  I compare counts from different reporting dates to estimate the total.  After you update and I pull your data, it will correct analyses based on the latest data, but not analyses of the changes in the data, such as cell 13 in https://github.com/hjstein/coronavirus-data/blob/master/Notebooks/Current.ipynb.

Thanks.
