### ISSUE TITLE
1. Patients transferred out of NYC and 2. Hospitalizations in new-to-NYC facilities

### ISSUE THREAD

**Issue by rcoikonos** [nychealth/coronavirus-data#22]
Thank you for managing this repository. 

1. How will DOHMH begin to count patients (hospitalizations, deaths) transferred outside the city system to relieve pressure to the system?  https://www.syracuse.com/coronavirus/2020/04/new-york-city-hospitals-begin-transferring-patients-to-upstate-ny-report.html ?

2.  Will data start reflecting cases taken up in USS Comfort and Javitz Center and on what date?

3. Will NYC hospital discharge data start being published ?

**Comment by mmontesanonyc** [comment]
Closing this old issue, as these questions are either answered in existing documentation, or, I assume, no longer relevant.
