### ISSUE TITLE
There's a typo in the rolling average of antigen tests

### ISSUE THREAD

**Issue by smasongarrison** [nychealth/coronavirus-data#220]
![image](https://user-images.githubusercontent.com/6001608/146266304-cba6d377-25b4-48c2-9f34-a2db4dd190e9.png)

**Comment by smasongarrison** [comment]
I don't know if you have access to the it. But under diagnostic testing, the rolling average should read "7-day"

page: https://www1.nyc.gov/site/doh/covid/covid-19-data-totals.page

**Comment by mmontesanonyc** [comment]
Thanks!
