### ISSUE TITLE
Weekly Breakthrough Cases - Unvaccinated Denominator

### ISSUE THREAD

**Issue by HarryLeroy** [nychealth/coronavirus-data#221]
If I am not mistaken, the population denominators used by the city throughout its GitHub database are based on a population of 8,336,817. However, the 2020 census put the city population at 8,804,190.

This isn't likely to move the needle for most metrics provided in the city database, but it does imply that the city is undercounting the current unvaccinated 12+ population by ~400,000 people. The city's current estimate for that population is ~750,000, and for the week-of-12/4 numbers provided today, the denominator appears to be ~886,000.

Is the city using the old population estimates to calculate the number of unvaccinated people? If so, does the city intend on updating any of its rate-based numbers to reflect the 2020 Census numbers?

Thanks,
HL

**Comment by penguingiraffe2** [comment]
This is a great point and great question. 
Would like to see this addressed too

**Comment by mmontesanonyc** [comment]
Hi, thanks for your question. Here's a bit more [information about the denominators we're using](https://github.com/nychealth/coronavirus-data#rates-per-100000-people). Our denominators are a product of several different data sources. Our population experts are working to adjust our denominators to reflect the information in the 2020 Census. 

You're right that the denominators for the unvaccinated population may be incorrect - this may be the case for the vaccinated population, too. [More about inconsistencies in vaccination rates](https://github.com/nychealth/covid-vaccine-data#zip-codes-and-zip-code-tabulation-areas-zctas).

That said, the purpose of denominators is not to provide an accurate count of people living in the city, but rather, a reliable estimate that helps us calculate stable and reliable rates over time.
