### ISSUE TITLE
`latest/now-weekly-breakthrough.csv` lost data for week of 12/18/21

### ISSUE THREAD

**Issue by slinkp** [nychealth/coronavirus-data#224]
The weekly breakthrough rate had a week of data added for 12/18/2021 yesterday 
in this commit: https://github.com/nychealth/coronavirus-data/commit/8f02aac470948433b1f92b944c6b8b2f6e337010

That update was undone yesterday as part of the 12/31 update, so we lost a week of data in that file:
https://github.com/nychealth/coronavirus-data/commit/e407293679c37bf66d171fac10daf0c1aa926bbe#diff-9c6dbf55971c2bdf4a110660e28401db511447b0d1bbe15c2682441290dd791d

Please fix that. It's a very useful graph on the NYC data site for understanding breakthrough trends, and as of right now it's nearly 3 weeks old, only goes up to 12/11/2021.

**Comment by MarkDDR** [comment]
Looks like the missing data has been restored
