### ISSUE TITLE
Weekend updates?

### ISSUE THREAD

**Issue by jeremydratcliff** [nychealth/coronavirus-data#226]
Hello,

At @CSSEGISandData, we've detected updates for NYC for every day this past weekend. Has the update schedule changed? The [README file](https://github.com/nychealth/coronavirus-data/blob/master/README.md) still indicates weekday updates only. Thank you very much!

**Comment by mmontesanonyc** [comment]
Hi there. We're doing some weekend updating again to support data needs during the Omicron surge.
