### ISSUE TITLE
now-weekly-breakthrough.csv Update Lag

### ISSUE THREAD

**Issue by RuijingZ** [nychealth/coronavirus-data#227]
I see now-weekly-breakthrough.csv only has data until 12/18, which lags for about 3 weeks, but other weekly csv files have data until 1/1. May I ask if  there is any new data for this dataset?

**Comment by mmontesanonyc** [comment]
Hi there. Given the recent surge in cases, it's taking longer to process information across lab, hospitalization, and vaccination datasets. Thanks for your patience.
