### ISSUE TITLE
Y axis max for Weekly Rates/Hospitalizations and Weekly Rates/Deaths too low

### ISSUE THREAD

**Issue by dbyolton** [nychealth/coronavirus-data#228]
https://www1.nyc.gov/site/doh/covid/covid-19-data.page#daily

Sadly Omicron has the Y axis max for Weekly Rates/Hospitalizations and Weekly Rates/Deaths too low.  Weekly Rates/Cases looks OK.

**Comment by mmontesanonyc** [comment]
Thanks - refreshing your browser should fix that.
