### ISSUE TITLE
Unvaxxed Denominators?

### ISSUE THREAD

**Issue by warrtalon** [nychealth/coronavirus-data#230]
Hello @kjohnson5nyc or @mmontesanonyc !

In the breakthrough-summary.csv section of the Readme, the attached definitions are given.
![image](https://user-images.githubusercontent.com/98188224/150838783-b77e1dc8-bc1d-47b5-85f4-5179d35191b2.png)

Is this explanation true? There are over 570,000 unvaxxed in ages 0-4. Are none of these counted in the Unvaxxed denominators and therefore not counted in the Unvaxxed rates? Their Cases/Hosps are also not counted in the rest of the metrics?
![image](https://user-images.githubusercontent.com/98188224/150840021-8d0269dd-619b-4c36-a7f9-000acf0e6249.png)

Where can we find the raw # of Cases, Hospitalizations, and Deaths by age and vax status? I can only find rates, which then requires reverse calculating the quantity per age group, but then that work without knowing the unvaxxed denominators.

Here is an example from the UK on how they provide the data.
![image](https://user-images.githubusercontent.com/98188224/150603400-5c4d8d86-ca20-40f2-9eb6-20dd92f411ab.png)

This table is my attempt at guessing the deaths by age group for the week of 12/25 based on the 93 (Vax) / 154 (Unvax) raw numbers shown in Latest/Now-Weekly-Breakthrough. Can we get a table added that provides these numbers raw for Deaths and Hosps like the UK?
![image](https://user-images.githubusercontent.com/98188224/150839860-302a9af3-2e62-4ca7-97aa-4389288fccc2.png)

Thank you!

**Comment by warrtalon** [comment]
Hi, @acharney2 , should I tag someone elsen besides @kjohnson5nyc and @mmontesanonyc , or will this get picked up by someone eventually?

Thanks again!

**Comment by mmontesanonyc** [comment]
Hi, thanks for your interest. The documentation is accurate; these data compare rates by vaccination status, among people who are eligible to be vaccinated. 

We are not currently publishing counts by both age and vaccination status.

**Comment by warrtalon** [comment]
Thank you. It would be excellent if the Vax vs. Unvax data could be separate by age group. This is critical for understanding the risk ratios for different demographics (ages and race/ethnicity). This is especially important when only 73% of 75+ are fully vaxxed. If a large portion of the Hosps/Deaths come from this group, then it throws off the all-age ratios.

There are more 75+ unvaxxed than all of 35-74 combined (by a lot). This should dramatically affect the age-adjustment, but for some reason the age-adjustment rates go the other direction. This can't be reconciled without seeing the pop denominators and age groupings.

I really appreciate the way this data is exposed and laid out. We're only missing a few key details.

Thank you so much - to you and your team.

Best,
Clayton
