### ISSUE TITLE
Deaths by MZCTA

### ISSUE THREAD

**Issue by Sage1piece** [nychealth/coronavirus-data#232]
In the technical notes "Reporting on COVID-19 deaths", you mentioned that "starting in June 2020, people who died more than 60 days after their COVID-19 diagnosis and starting August 3, 2021, people who died more than 30 days after their COVID-19 diagnosis who did not have "COVID" or similar listed on their death certificate are removed from the death count. This is to address instances in which a person was diagnosed with COVID-19 and survived, but later died, likely of other causes." My question is: how do we know when and from where (MZCTA) these unqualified deaths are removed?

**Comment by mmontesanonyc** [comment]
Thanks for your interest. We're not currently publishing data on these patients.
