### ISSUE TITLE
RE: last7days by modzcta

### ISSUE THREAD

**Issue by MAF9-JHU** [nychealth/coronavirus-data#234]
I'm looking for the time trend of 'people_positive' by modzcta. Is there a respository of last7days by modzcta? I have found the caserate-by-modzcta under trends. Thanks.

**Comment by mmontesanonyc** [comment]
To protect privacy, we don't publish the number of people positive by both modzcta and day. However, you can see [daily percent positivity data here](https://github.com/nychealth/coronavirus-data/blob/master/latest/pp-by-modzcta.csv).
