### ISSUE TITLE
Vaccine Status Definition and Age-Adjustment Clarifications

### ISSUE THREAD

**Issue by warrtalon** [nychealth/coronavirus-data#235]
Hello, @acharney2 , in this Readme, the definitions for "Vaccinated" and "Unvaccinated" leave room for interpretation.

https://github.com/nychealth/coronavirus-data/blob/master/latest/Readme.md 

May we know the following?

Breakthrough Summary.csv:
1) In what category do you place those who are <14 days after the most recent dose completing their primary series?
- Are those counted as "Unvaccinated," or is there a 3rd unseen category (e.g. "Partially Vaccinated")?
2) What is the formula used to create the Hosp/Death adjusted rates? I know it's based on the 2000 age distribution standard, but what is the formula? It appears to nearly triple the crude rate even though the largest Unvaxxed cohort is 75+ (besides 5-12)

Now-Weekly-Breakthrough.csv:
1) Does this table include all COVID outcomes for each week, or is there another set of outcomes not seen because they don't fit the "Unvaccinated" or "Vaccinated" definitions?
2) Hosp/Death rates:
- Can you add columns for crude rate (like you show for Cases)?
- If not, can you add population columns for Vax and Unvax so we can see the denominators? This would help us in the public to validate the math - it's great for transparency and confidence 👍

My chart here shows what I mean. The yellow line is my calculation for crude rate while the blue line is yours. It makes a huge difference (blue vs. yellow):
![image](https://user-images.githubusercontent.com/98188224/153772030-ccf8be83-0b40-4bd2-88a0-3e68dfb1896b.png)

This 2nd version includes my interpolation for weeks 1/8-1/29 since those seem to have incomplete Vax Record Matching:
![image](https://user-images.githubusercontent.com/98188224/153772126-10f82285-8811-45c5-ae09-6f34c67e78e3.png)

These details are important, because you can see how that artificial blue hump dramatically impacts the chart on the website:
![image](https://user-images.githubusercontent.com/98188224/153772096-8fd7ac16-a800-4655-8a36-665f9b99b9a7.png)

Since the charts are being shared widely on social media by Commissioner Chokshi and very large media accounts before Vax Record Matching is complete, it can lead to public misconceptions and unintended policy impacts. You can see why I care so much about it, and I know you do, too. 🙏 

Thank you!
-Clayton

**Comment by dd11235** [comment]
I was just about to ask about the definition of "Vaccinated" and "Unvaccinated" in the breakthrough data myself so hope you get an answer soon!

**Comment by warrtalon** [comment]
> I was just about to ask about the definition of "Vaccinated" and "Unvaccinated" in the breakthrough data myself so hope you get an answer soon!

Definitions are on that link I gave at the top. Here's a snippet:
![image](https://user-images.githubusercontent.com/98188224/153883995-421221c9-ddc9-4b94-8d7c-16c2d9a0c7a3.png)

**Comment by mmontesanonyc** [comment]
Hi, thanks for the interest. 

re:  breakthrough-summary.csv: we do not have a partially vaccinated category in these data, and partially vaccinated people (those who are <14 days after completing the primary series) are excluded from these data, including the denominators. 

re: age-adjustment: [You can read more about age-adjustment here](https://www.nlm.nih.gov/nichsr/stats_tutorial/section2/mod5_age.html). This is a standard analytical process in epidemiology. When two populations have very different age distributions, crude rates primarily reveal age differences, whereas age-adjusted rates separate the effect of the age differences from the effect of the thing you want to study. In this case, the standard and appropriate way to compare these two populations is via age-adjusted rates.

**Comment by warrtalon** [comment]
> Hi, thanks for the interest.
> 
> re: breakthrough-summary.csv: we do not have a partially vaccinated category in these data, and partially vaccinated people (those who are <14 days after completing the primary series) are excluded from these data, including the denominators.
> 
> re: age-adjustment: [You can read more about age-adjustment here](https://www.nlm.nih.gov/nichsr/stats_tutorial/section2/mod5_age.html). This is a standard analytical process in epidemiology. When two populations have very different age distributions, crude rates primarily reveal age differences, whereas age-adjusted rates separate the effect of the age differences from the effect of the thing you want to study. In this case, the standard and appropriate way to compare these two populations is via age-adjusted rates.

Thank you for the partial vax answer. That makes sense and is good to confirm.

FOr the age-adjustment, I acknowledge awareness of the standard, and I understand why it's usually done. What I'm asking is what exact formula you're using and how it accounts for 75+ having more Unvaxxed than any other age group. This would seemingly cause the age-adjustment to go the other direction. Why would more young people being vaccinated cause age-adjustment to triple the crude rate?

May we see the calculations and how this works? If not, it's like a black box that no one in the public can understand.

Thank you!
