### ISSUE TITLE
Definition of confirmed COVID death change

### ISSUE THREAD

**Issue by jeezyjtrain** [nychealth/coronavirus-data#236]
It seems as though the definition of what is deemed a confirmed COVID death has been changed around or on February 3rd as shown by the usage of the way back machine. My question is when did this occur and will past data be amended to apply this change/where is the update for this change in definition. The current definition is:

“There are two classifications of COVID-19 deaths reported:

A death is classified as confirmed if the decedent was a NYC resident who had a positive molecular test for the virus that causes COVID-19 and did not die of external causes such as gunshot wounds or drug overdoses.”

Which was change from simply:

“ A death is classified as confirmed if the decedent was a NYC resident who had a positive molecular test for the virus that causes COVID-19” 

This change in definition needs to be accounted for as the very definition of a confirmed COVID death has changed, almost to assume that all the data gathered throughout the onset of the pandemic reflect this new definition, which is simply not the case.

![9E9B904F-46D7-4EC6-A2FB-80B69696CCCD](https://user-images.githubusercontent.com/99855204/154398453-1173f2cb-c6bb-42a2-bd0d-6ac780b0ff08.png)
![2C819423-F375-4873-A672-731A866327FD](https://user-images.githubusercontent.com/99855204/154398454-2ca6931b-742a-4375-974c-8146dfac5fe3.png)
![D3B10225-748B-402D-B878-D9B62CDA8B0B](https://user-images.githubusercontent.com/99855204/154398455-1ed30e69-472d-484c-ac59-4458d8a89346.png)
![3B4A7A4E-F3C8-4649-BD54-2DA57A788C6F](https://user-images.githubusercontent.com/99855204/154398457-65e4bc87-8b09-4785-9e64-cc734712351a.png)
![2D20FA14-E4B8-4CF9-AC91-2FBF7CBA8B42](https://user-images.githubusercontent.com/99855204/154398459-254680c0-92fc-430f-9d4c-73d8da5ec010.png)
![E4FEB13E-1F31-4164-BC89-4AA8E52D8623](https://user-images.githubusercontent.com/99855204/154398460-ab14f4e5-9092-4c24-9228-1b853fbec129.png)
![B6E9D3A7-703C-41E2-8275-796D1029739C](https://user-images.githubusercontent.com/99855204/154398462-e480e1ae-6158-4f3d-b9b9-70d9169a0df9.png)
![9BBC9E58-9EFA-45C8-992B-BA603F1DEE27](https://user-images.githubusercontent.com/99855204/154398466-4939dfe0-6a82-468b-9a32-13d569f0a762.jpeg)
![41C8D428-34AE-45FF-A32B-82D8F26D3B3A](https://user-images.githubusercontent.com/99855204/154398468-907c1ed8-fcdd-47c4-9dcb-014b05013144.png)

**Comment by martinssanchez** [comment]
Would really appreciate some transparency in this process...

**Comment by mmontesanonyc** [comment]
Hi, thanks for your interest. 

Our documentation on deaths was indeed updated on Feb 3 (feel free to use the git history in this repository instead of the wayback machine if you want to look at changes, by the way). However, this change was to **clarify** the definition we had been using and continue to use. It was not a change in inclusion/exclusion criteria.

**Comment by jeezyjtrain** [comment]
> Hi, thanks for your interest.
> 
> Our documentation on deaths was indeed updated on Feb 3 (feel free to use the git history in this repository instead of the wayback machine if you want to look at changes, by the way). However, this change was to **clarify** the definition we had been using and continue to use. It was not a change in inclusion/exclusion criteria.

Using as of when? Because according to data and Gov. Kochul, the separation of hospitalization data between an individual with a positive COVID case who was admitted to a hospital for a non-COVID reason and an individual who was admitted for COVID as their primary ailment wasn’t determined until January 4th and 5th. And according to these articles, it was discovered that about 42% of hospital patients with COVID had been admitted for other issues and then we’re subsequently diagnosed. If there was no distinction made between the hospitalization data until January 4th and 5th, then when specifically was this distinction made for
![42A746E9-0699-4D65-86D9-1EDA5915D265](https://user-images.githubusercontent.com/99855204/155763037-386346b9-14c6-40f0-b427-1bf68ef520b0.jpeg)
![FFA928FA-18DB-44CC-8A62-FFA7540E3D4B](https://user-images.githubusercontent.com/99855204/155763040-7290e7a6-8caf-43d8-b105-e18c287dcb91.png)
![6CEC0F88-D281-4426-B08E-4D6A13D9C08E](https://user-images.githubusercontent.com/99855204/155763042-9fcccbdb-3067-4d22-88d5-6314dc933fab.jpeg)
![425F6635-3DC0-45CC-B4A3-79FAE3EADEC1](https://user-images.githubusercontent.com/99855204/155763114-0cd89d03-c43a-40c4-96bf-e3c43668276e.png)
![8782AD20-7248-4525-8200-1BC289FDE100](https://user-images.githubusercontent.com/99855204/155763118-142b880d-9c91-4bec-afcd-3abfbd66aebf.jpeg)
![D3398AA6-DA69-40B7-AA4B-110678B7EBDC](https://user-images.githubusercontent.com/99855204/155763121-cd1b273a-9a76-47da-8da1-41a54300395b.png)
![CE2E4C29-923B-4AA2-A589-77FCE1DED639](https://user-images.githubusercontent.com/99855204/155763127-c6cd0328-dd35-434e-b7ba-07250b85e281.jpeg)
![CA2AD689-E8EF-4CAA-AB1B-C4A8E7A7C9A1](https://user-images.githubusercontent.com/99855204/155763130-f5867c4a-e3d3-47df-be60-b295d2a5f4bb.png)
![8B3EF01F-46BC-410D-84A9-7D34ACA4D11B](https://user-images.githubusercontent.com/99855204/155763135-0dd1da00-eee0-4ac3-ab20-29e41796c908.png)
 deaths?
