### ISSUE TITLE
Delayed Update for Weekly Breakthroughs?

### ISSUE THREAD

**Issue by warrtalon** [nychealth/coronavirus-data#237]
Hello, Ariel @acharney2 , data is updated each Thursday, but 1 file did not update yesterday and still hasn't yet today.

File Link: https://github.com/nychealth/coronavirus-data/blob/master/trends/weekly-breakthrough.csv (also the now-weekly-breakthrough.csv in /latest) 

Will it be updated today at some point, or is there something wrong with that data?

![image](https://user-images.githubusercontent.com/98188224/154748194-2bd46bf0-e93d-46ba-938b-7c5a56a7b6a6.png)

Thank you!
- Clayton

**Comment by larryq** [comment]
Hi @acharney2, interested in an update to this file as well, thanks much.

**Comment by facebookemojis** [comment]
That is strange why the data is not updated yet?

**Comment by redknightlois** [comment]
Breakthroughs is an important file IMHO. Should be updated every week.

**Comment by BrendanEich** [comment]
Why aren't all files updated at the same time?

**Comment by jcabrera** [comment]
I'm also looking for an update to this file - is there a reason why it wasn't updated at the same time as the others?

**Comment by warrtalon** [comment]
For a second, I thought the team was working today and had updated the delayed file, but alas...
![image](https://user-images.githubusercontent.com/98188224/154995353-8315f055-cfc3-4629-920a-29f06f6ca475.png)

**Comment by warrtalon** [comment]
Hello @mmontesanonyc and @acharney2 , we are now at 13 days (6 days past due) on the Weekly Breakthrough file not being updated.

The website only says there are technical issues and to check back soon, but that warning has been there since Friday or Saturday.

- Will this file ever be updated again?
- Will you now wait until tomorrow's weekly update push?
- What was the technical issue causing delays?

Thank you kindly,
-Clayton

**Comment by larryq** [comment]
Just following up on @warrtalon and his comment above-- any eta for release on the new breakthrough data?  Thx.

**Comment by facebookemojis** [comment]
they clearly dont want to show us this data

Best regards,
*BuyForexSignals.com <http://www.buyforexsignals.com/?email>*

Open a new account with *AvaTrade
<http://www.avatrade.com/lp/rebranding?tag=1686> *or *PrimeXBT
<https://prime-bonus.com/en/buyforexsignals/>*
To get our Signals for FREE

**Comment by mmontesanonyc** [comment]
Thanks for your interest. Breakthrough data have been updated.
