### ISSUE TITLE
Is MODZCTA by location of test or residence of person?

### ISSUE THREAD

**Issue by JimHaughwout** [nychealth/coronavirus-data#239]
Is your data by MODZCTA (cases, hospitalizations, etc.) based on *where* the sample was collected or where the person who was tested lives? If I have a case for MODZCTA of `10023` does this mean the sample was collected at a site in this location *or* does it mean the person who was tested provided a residential address that is based in `10023`?

**Comment by mmontesanonyc** [comment]
Hi, thanks for asking. The geographic data is by location of residence, not testing or treatment. More info [in our documentation](https://github.com/nychealth/coronavirus-data#geography-zip-codes-and-zctas).
