### ISSUE TITLE
Separating 0-1 year old from 1-4 year old data

### ISSUE THREAD

**Issue by laurarpg** [nychealth/coronavirus-data#240]
Can we please create a new report that separates 01 year olds from 1-4 year olds for death counts and hospitalizations from COVID?  Ideally this would go back in time several months.  Thanks in advance!

**Comment by mmontesanonyc** [comment]
Hi, thanks for letting us know what you'd like to see.

Because of very small counts of hospitalizations and deaths among people in this age group, we can't disaggregate further - we need to keep these aggregated to properly protect privacy and calculate stable, reliable rates.

**Comment by laurarpg** [comment]
Sorry I submitted a related request and just wanted to note here - if this cannot be provided on a periodic basis, then please provide:  total number of hospitalizations for 0-1 year olds and 2-4 year olds in NYC to date, and total number of NYC deaths in 0-1 and 2-4 year olds to date.

**Comment by laurarpg** [comment]
Hello, please see my separate request for total deaths and total hospitalizations in NYC to date, for 0-1 year olds and 2-4 year olds.  Understood if you can't provide this on a daily or monthly basis but totals should be available please.
