### ISSUE TITLE
Total number of pediatric deaths 2-4 in NYC vs 0-1

### ISSUE THREAD

**Issue by laurarpg** [nychealth/coronavirus-data#241]
Hi,

I previously requested data be segregated by 0-1 vs 2-4 year olds.  Understood that on a daily/monthly basis you cannot do that.

Can you please provide, total number of pediatric deaths from COVID in the age range 2-4 vs 0-1 years old to date?

**Comment by laurarpg** [comment]
Also total number of hospitalizations please

**Comment by laurarpg** [comment]
Please can I have an update; I think this is data the team should already have, I hope not a significant burden to provide please.

**Comment by laurarpg** [comment]
Please can you provide an update; this is a continuation of a prior request from maybe a month ago now.  This is an important question and transparent, clear data will be helpful.

**Comment by mmontesanonyc** [comment]
Hi, we appreciate your interest, but while we are able to answer your questions about the data, [we are not able to field custom data requests via this repo.](https://github.com/nychealth/coronavirus-data#how-to-use-this-repository)

**Comment by laurarpg** [comment]
Sorry, this is a question about the data.  You have data that is presented in the format of 0-5 year olds.  I am requesting segregation of the data in some format so that it can separately state 0-1 vs 2-4 year olds.  I am not asking for a custom data request.  Moreover, in my prior related request you did not characterize it as a custom data request.  This is critical for folks to understand the data that has been presented so far around the 0-5 year olds, and, understood where this team has an interest in ensuring the data is understood.  "We will try to answer questions about the data in this repository" - I think this should be prioritized because the question will serve to answer whether 2-4 year olds are at particular risk in NYC, vs 0-1 year olds, which is vital to making smart decisions about risk mitigations in schools.
