### ISSUE TITLE
antibody-by-modzcta-by-week

### ISSUE THREAD

**Issue by jennifer-bio** [nychealth/coronavirus-data#242]
I have found files for antibody-by-modzcta.csv in totals and antibody-by-week.csv in trends. I was wondering if there is an antibody-by-modzcta-by-week available (or could be made available)? If not, is there a relationship between the endpoint date of the data in antibody-by-modzcta.csv and the day the file is updated?

**Comment by mmontesanonyc** [comment]
Hi, thanks for your interest. We don't publish antibody data by both week and modzcta. Per our documentation, data are updated at a 3 day lag, so the date the file is updated, it includes data through 3 days prior.
