### ISSUE TITLE
antibody data

### ISSUE THREAD

**Issue by laurarpg** [nychealth/coronavirus-data#244]
I saw there's open data available on percent of antibody tests that are positive.  Please can this be updated so that it can be refined by time.  For example, it would be extremely valuable to know the percent of antibody tests that were positive by age during the last month.  I expect those would be at or above the national average (60% for adults and 75% for children based on recent CDC announcements).

Many thanks in advance

**Comment by mmontesanonyc** [comment]
Hi, thanks for your interest. Antibody data have recently been updated.

**Comment by laurarpg** [comment]
Hi, sorry I don't understand - can you please provide a link to where my request has resulted in updated antibody data?

**Comment by laurarpg** [comment]
I see antibody-by-age was last updated 9/9 - where is the update?  Please can you provide a link.  Here is what I have seen so far:  antibody-by-age.csv at this link:  https://github.com/nychealth/coronavirus-data/tree/master/totals

**Comment by laurarpg** [comment]
Oh - I see here an updated data set:  https://github.com/nychealth/coronavirus-data/blob/master/totals/antibody-by-group.csv posted in May, and the prior one posted in September is here:  https://github.com/nychealth/coronavirus-data/blob/master/totals/antibody-by-age.csv

These don't square though - if you take the May data set and compare to September, for ages 0-4, you see that:

Number of additional tests from September to May = 45196-43601 = 1595
Number of additional positives from September to May = 14431 - 12834 = 1597

This means that every single antibody test done from September to May resulted in a positive test (plus a couple of bonus positive tests).  I can't imagine this is accurate?

I did a similar comparison of the data for 25-34 year olds:

Number of additional tests from September to May = 591638 - 565318 = 26320
Number of additional positives from September to May =  194851 - 162340 = 32511 

In this case, for this age range there are substantially more new positive antibody tests than new people tested.

Please can you help me understand what's going on with this data?

**Comment by laurarpg** [comment]
I will post this as a new issue since I don't see any way to reopen this issue.

**Comment by laurarpg** [comment]
Here is the new issue:  https://github.com/nychealth/coronavirus-data/issues/246 we can continue via that ticket, thank you.
