### ISSUE TITLE
Please help connect May and September antibody data; there appears to be an error

### ISSUE THREAD

**Issue by laurarpg** [nychealth/coronavirus-data#246]
I see here an updated data set for antibody positive tests: https://github.com/nychealth/coronavirus-data/blob/master/totals/antibody-by-group.csv posted in May, and the prior one posted in September is here: https://github.com/nychealth/coronavirus-data/blob/master/totals/antibody-by-age.csv

These don't square though - if you take the May data set and compare to September, for ages 0-4, you see that:

Number of additional tests from September to May = 45196-43601 = 1595
Number of additional positives from September to May = 14431 - 12834 = 1597

This means that every single antibody test done from September to May resulted in a positive test (plus a couple of bonus positive tests). I can't imagine this is accurate?

I did a similar comparison of the data for 25-34 year olds:

Number of additional tests from September to May = 591638 - 565318 = 26320
Number of additional positives from September to May = 194851 - 162340 = 32511

In this case, for this age range there are substantially more new positive antibody tests than new people tested.

Please can you help me understand what's going on with this data?

**Comment by laurarpg** [comment]
How could we use this data then to approximate the percent of New Yorkers currently seropositive?

**Comment by mmontesanonyc** [comment]
These data can't help approximate the percent of New Yorkers currently seropositive. They're too heavily influenced by testing bias. There's no reason to assume that those who have chosen to get tests is a representative sample of all New Yorkers, and cumulative data on nearly 2 years of antibody testing can offer very limited insight into who is currently seropositive.
