### ISSUE TITLE
How to identify hospitalizations due to COVID vs hospitalized patients who happen to have COVID?

### ISSUE THREAD

**Issue by laurarpg** [nychealth/coronavirus-data#247]
Hi all,

please can you help me understand, how have you distinguished for current hospital stats which folks in the hospital came in for something else and happen to test positive for COVID, versus, how many are actually admitted due to COVID?  I would like to understand this for the current hospitalizations.

**Comment by mmontesanonyc** [comment]
Hi, thanks for the inquiry. That distinction can't be made with the data published here. That information is captured in a different data source, the New York State Health Electronic Response Data System (HERDS). [In January, the Health Department published a report on the Omicron variant that included some HERDS data about this question](https://www1.nyc.gov/assets/doh/downloads/pdf/covid/omicron-variant-report-jan-13-22.pdf).
