### ISSUE TITLE
Data for vaccination status has not updated since 6/19

### ISSUE THREAD

**Issue by chichibeth** [nychealth/coronavirus-data#251]
For some reason, the hospitalizations and deaths by vaccination status has not updated since 6/19

**Comment by hbpartonnyc** [comment]
We recently stopped updating our now-weekly-breakthrough file as we evaluate our methods for presenting outcome data by vaccination status. The number of unvaccinated people is calculated by taking the total estimated city population minus the number of those fully or partially vaccinated. However, as more NYC residents become vaccinated, the size of our unvaccinated population approaches zero. And for some groups, we are observing more vaccinated individuals than estimated population. [More about inconsistencies in vaccination rates](https://github.com/nychealth/covid-vaccine-data#zip-codes-and-zip-code-tabulation-areas-zctas).

We continue to work on our methodology to ensure the data we provide are as accurate and transparent as possible. Data comparing cumulative cases, hospitalizations and deaths by vaccination status can still be found in [breakthrough-summary](https://github.com/nychealth/coronavirus-data/blob/master/latest/breakthrough-summary.csv).
