### ISSUE TITLE
Question about total_covid_tests in data-by-modzcta.csv

### ISSUE THREAD

**Issue by rosenfed** [nychealth/coronavirus-data#254]
Hi there, my name is Dan, I'm a data manager with NYC Health + Hospitals. I was looking at the total_covid_tests column in the data-by-modzcta.csv on GitHub and right now it seems like there are  8,867,103 tests in there.
 
https://github.com/nychealth/coronavirus-data/blob/master/totals/data-by-modzcta.csv
 
This seems really low to me, Health + Hospitals alone has done over 10 million tests. I saw that this is just molecular tests, but is there another reason the numbers are so low? Thank you!

Dan Rosenfeld
Senior Data Manager
Test & Trace Corps
Direct: (646) 856-3050
Cell: (267) 884-1530
rosenfed@nychhc.org

**Comment by hbpartonnyc** [comment]
The geographic data presented in this table is by location of residence, not testing. Also, the sum of counts does not include records with missing geographic information. You can find more information [in our documentation](https://github.com/nychealth/coronavirus-data#geography-zip-codes-and-zctas).
