### ISSUE TITLE
last7days-by-modzcta update frequency

### ISSUE THREAD

**Issue by gaylekm** [nychealth/coronavirus-data#256]
Hello!

What is the frequency of updates to the last7days-by-modzcta table?

Many thanks!
Gayle

**Comment by hbpartonnyc** [comment]
The [last7days-by-modzcta table](https://github.com/nychealth/coronavirus-data/blob/master/latest/last7days-by-modzcta.csv) is usually updated every weekday. We had a technical issue yesterday (8/3) which prevented us from updating.

**Comment by gaylekm** [comment]
Thanks so much!
