### ISSUE TITLE
Data updating

### ISSUE THREAD

**Issue by BYRubin** [nychealth/coronavirus-data#258]
The data on the NYC rates of infection, hospitalization and deaths in the unvaccinated, vaccinated no booster, vaccinated with booster populations has not been updated since 11/19. When can I expect the next update?

**Comment by hbpartonnyc** [comment]
Hi there, The now-weekly-breakthrough file is updated on Thursdays containing data through the Saturday 12 days prior. The file with data through 11/19 was posted today and is the latest available.

**Comment by BYRubin** [comment]
Thanks!

Berish

On Thu, Dec 1, 2022 at 3:15 PM hbpartonnyc ***@***.***> wrote:

> Hi there, The now-weekly-breakthrough file is updated on Thursdays
> containing data through the Saturday 12 days prior. The file with data
> through 11/19 was posted today and is the latest available.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nychealth_coronavirus-2Ddata_issues_258-23issuecomment-2D1334379539&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=803PoV1Ra2aa9EgBQzAJKlgUtw6ePc5dJcR9D1W3b0Y&m=jxCAwo5SZuEongpeiYWiDsXs9sITaRCJGKxY9fhYo76K3jxcELSB-_l4EA_3z-1d&s=INzDk9hIp2MupO7DuJvhk4PlariYoc9zDpuqeG66bes&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_A4QVI3NMFYWM5CW2J3ND3C3WLEBO3ANCNFSM6AAAAAASRD33F4&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=803PoV1Ra2aa9EgBQzAJKlgUtw6ePc5dJcR9D1W3b0Y&m=jxCAwo5SZuEongpeiYWiDsXs9sITaRCJGKxY9fhYo76K3jxcELSB-_l4EA_3z-1d&s=RDYi3dA68fYOd34eRmmF2OS0DRr5TC3_XSGEDK__prA&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
Berish Y. Rubin, Ph.D.
Professor
Department of Biological Sciences
Fordham University
441 East Fordham Road
Bronx, New York 10458
Tel: 718-817-3637
Fax: 718-817- 2792
Email: ***@***.***
