### ISSUE TITLE
NYC Dept of Health Data

### ISSUE THREAD

**Issue by BYRubin** [nychealth/coronavirus-data#259]
The "Weekly Rates by Subgroup" data on populations with different vaccination status (https://www.nyc.gov/site/doh/covid/covid-19-data.page#daily) appears to have not been updated recently. The latest data point is 12/24

**Comment by hbpartonnyc** [comment]
Weekly files are updated on Thursdays containing data through the Saturday 12 days prior. Files with data through 12/31 were posted today and are the latest available.

**Comment by BYRubin** [comment]
Very much appreciated!

Berish

On Thu, Jan 12, 2023 at 12:47 PM hbpartonnyc ***@***.***>
wrote:

> Weekly files are updated on Thursdays containing data through the Saturday
> 12 days prior. Files with data through 12/31 were posted today and are the
> latest available.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nychealth_coronavirus-2Ddata_issues_259-23issuecomment-2D1380779717&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=803PoV1Ra2aa9EgBQzAJKlgUtw6ePc5dJcR9D1W3b0Y&m=kf2UvOOCeT-uRJXzQIwjDod_Eo9gxYY4bm3mbDstj-CUXrB3UBdNPw5WBjhTDgWv&s=B5VMIcRwkz9TMEMrCanGRRh-0Lgc6g7ExjIwDGxLPS8&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_A4QVI3NPDHBD7B3HEPA7M3DWSA7SPANCNFSM6AAAAAATXNCIGI&d=DwMCaQ&c=aqMfXOEvEJQh2iQMCb7Wy8l0sPnURkcqADc2guUW8IM&r=803PoV1Ra2aa9EgBQzAJKlgUtw6ePc5dJcR9D1W3b0Y&m=kf2UvOOCeT-uRJXzQIwjDod_Eo9gxYY4bm3mbDstj-CUXrB3UBdNPw5WBjhTDgWv&s=6RkffvCLkhn466nnJoksM4e9lMGTEvPlymgrT2n2v-k&e=>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
Berish Y. Rubin, Ph.D.
Professor
Department of Biological Sciences
Fordham University
441 East Fordham Road
Bronx, New York 10458
Tel: 718-817-3637
Fax: 718-817- 2792
Email: ***@***.***
