### ISSUE TITLE
Weekly Rates vs Daily Counts

### ISSUE THREAD

**Issue by Michael-Cooney** [nychealth/coronavirus-data#260]
Hello!

Using the data-by-day.txt trend dataset, I was able to re-calculate the citywide column for monthly death rates from deathrate-by-modzcta.txt.  I determined the denominator by back-calculation using the by-group.txt total dataset: ~8.34 million.

I cannot seem to calculate the weekly death rates, using the age_all_ages column from weekly-death-rate-age.txt.  For example, data-by-day.txt shows 4 deaths from March 8 - 14, 2020: 3 confirmed and 1 probable.  Using the same population of 8.34 million, the death rate per 100,000 would be 0.048, yet weekly-death-rate-age.txt shows a rate of 1.72.  To get 1.72 using 4 deaths, the population would seem to be only 233,000.

A few months later, June 21 - 27, 2020, there are 128 total deaths.  I calculate a rate of 1.54, but the weekly file lists 0.32.  To get 0.32 using 128 deaths, the population would need to be 34.4 million.  I am having similar trouble with weekly case rates and hospitalization rates.  I didn't check if monthly case and hospitalization rates work out ok.

What am I missing here?

Best regards,
Michael Cooney

**Comment by hbpartonnyc** [comment]
Thanks for flagging this! We have revised the tables for weekly hospitalization and death rates by age and race/ethnicity to correctly categorize people with COVID-19 based on date of event (hospital admission or death). These files previously categorized people with COVID-19 based on date of COVID-19 diagnosis. Trends using the updated data remain the same.

**Comment by Michael-Cooney** [comment]
Fabulous!  Thank you for the update and help.
