### ISSUE TITLE
Trends Readme Deleted

### ISSUE THREAD

**Issue by RishiKowalski** [nychealth/coronavirus-data#265]
Hi, sometime after the 9/19 commit [here](https://github.com/nychealth/coronavirus-data/tree/773a283e3082c07a91282d6bbf58e35c840ab47f/trends), the readme on the trends page disappears. It's accessible on previous commits, but not on the main Trends page currently.

**Comment by rrohrerdohmh** [comment]
Thanks for bringing this to our attention! We have restored the Trends Readme.
