### ISSUE TITLE
NYC ER Visits/Admits for ILI and Pneumonia

### ISSUE THREAD

**Issue by briankoral713** [nychealth/coronavirus-data#29]
Hey all - based on the line graphs here https://www1.nyc.gov/assets/doh/downloads/pdf/imm/covid-19-syndromic-surveillance-04082020-1.pdf

I was able to roughly compile total numbers for each age group and approximate totals - you can view those here https://github.com/briankoral713/NYC-COVID19-Data/blob/master/ER%20Visits-Admits%20NYC.pdf

Remember these are rough estimations based on the line graphs and don't reflect actual numbers.  The trend is that overall visits are on a downtrend however the bulk of ER Visits and Admits reside with the elderly (65+) which has been steadily increasing.  

The age group total population numbers are from https://www.baruch.cuny.edu/nycdata/population-geography/pop-demography.htm

**Comment by ryanwitt** [comment]
@briankoral713 thanks for the analysis! Can you swap the graph labels for admits and visits? I think they are reversed.

**Comment by briankoral713** [comment]
Sure - let me double check - I'll put the Excel file up too to make it easier.

**Comment by briankoral713** [comment]
@ryanwitt you are right! Sorry about that - the original excel file is here: https://github.com/briankoral713/NYC-COVID19-Data/blob/master/Covid19%20NYC%20Data.xlsx

And the corrected PDF is here: https://github.com/briankoral713/NYC-COVID19-Data/blob/master/Covid19%20NYC%20ER%20Visits-Admits.pdf

**Comment by DTPOTO** [comment]
Hello @briankoral713:   I was looking at your spread sheet for the ER admits vs visits.  I understand that you are making eyeball assessments of the actual counts.   That being said, not bad!   You don't actually have the data but your ratio comparison can tell a story about the  population that is entering the hospital ER is shifting over time.  

If I can make some suggestions.    
1)  Calculate the Admin/Visit Ratio (or % Admin) by Age Group
2) Show a double Y-Axis Graph with the 3 Age groups    
     This may be a messy looking at first, if it is not clear then break each Age-Group into its own double Y-Axis chart.
3) Y-Axis 1:   A Barnhart showing the volume per 100,000 population
     Y-Axix 2:  A Line chart showing the % Admitted to the Hospital 
     X-Axis:  The date of ER visit

You need to place 2 notes on your chart if you can.  
I personally struggle with this issue using LibraOffice.  
1) Estimates made based on visual observation of Graphical chart.
2) Volume counts are standardized to a like 100,000 population  <= Very Important

My exception is that you should be showing the ER being face with more older people who are needing greater medical attention.   This is very problematic.

**Comment by briankoral713** [comment]
@DTPOTO great points and thank you!! Let me make those changes now.  Eyeballing is a great point - I did not know what the proper terminology was!

Also I think ER Visits and especially admits are a leading indicator for CV-19 cases/deaths - even though this for all ILI's, it's still a vital barometer to monitor for ultimate containment here in the city.

**Comment by briankoral713** [comment]
OK! The data has been updated.  Thanks for your inputs!

https://github.com/briankoral713/NYC-COVID19-Data/blob/master/Covid19%20NYC%20Data.xlsx

https://github.com/briankoral713/NYC-COVID19-Data/blob/master/Covid19%20NYC%20ER%20Visits-Admits.pdf

**Comment by DTPOTO** [comment]
@briankoral713, I think you are showing the same thing.    
Let me first adjust my hypothesis because the base information is a measurement of the 100,000 like population.   This does not give direct view of the stress on the hospital ER's because the City combined demographics is much different than evenly weighted 100k populations.   This view does give insights to the individual age-groups.

The older group is much smaller in the total population.   This chart can be viewed to understand how the age-groups are progressing overtime during the course of the outbreak.  How many in that age group need to present themselves to the ER and how sick are they.   More of a statement about the age-group than the Hospital system.  Notable 65+ are more needy but are a small portion of the total demand on the system (especially in NYC).

![image](https://user-images.githubusercontent.com/63018432/78923995-158cf180-7a67-11ea-8c57-5b8e5a6bb832.png)

My take, the younger population (45-64) are presenting themselves to the the ER LESS over time, with pretty much the same level of severity.  (50% need to be admitted)  Good News
On the other hand the more needy group (65+) is presenting themselves at almost the same level but with great level of severity.  (100%+ need to be admitted) Bad News

In general, the good news is that overall Flue-Like & Pneumonia are down.

**Comment by briankoral713** [comment]
![image](https://user-images.githubusercontent.com/63133428/78926448-16c01d80-7a6b-11ea-8d28-63a1db44f3fa.png)
@DTPOTO nope I updated it! 

Above you are showing totals rather than standardized for 100k - I am showing the standardized as you suggested, although our totals are more or less the same!

![image](https://user-images.githubusercontent.com/63133428/78926887-e331c300-7a6b-11ea-8330-4db189c20a34.png)

**Comment by DTPOTO** [comment]
@briankoral713:
Ok, the 100k view is more informative.  
(Note: try to match your colors by Age-Group and the black background makes it hard to delineate colors, at least for us old-guys!)

Interpretation of the 100k graph
1) The Youngest 18-44 are presenting themselves less overtime.   Very Good
2) The Middle age 45-64 are presenting about the same (a little less) with about the same level of severity (50% Admission)    Good
3) The Older age group 65+ are presenting at MUCH higher numbers with greater severity!!  Very bad!!

The 100k chart tells the same story as where the Italians (and I think Spanish) failed.  That is to minimize or defer the impact on the elderly.   This is not just a fill good goal but major part in keeping the Health-Care System from being overwhelmed.   

By the way, I notice that you did not break out the young-retired(65-74) from the old-retired (75+).   My concern with the young-retired is that they may exposed themselves more than the old-retired to the virus by being out-and-about.   The Young-Retired can be the carriers acting as elderly assistants.   Visiting, dropping off the supplies at 80 year old's house.   I see separating the Young-Retired out from the Old-Retired as important in tracking communicable disease.   Looking at the NYC-DOHMH ER-Visits PDF you can see the age-groups showing the wave, younger to older groups.    Surprisingly starting with the youngest group (FIFO).

Do you know, when did NYS or NYC restrict access to Nursing Homes?    When the Governor or Mayor make requirement (request) for the elderly to isolate from the general public?   With hind sight using the 100k chart, the elderly issolation needed to occur late Feb or Early March (two weeks prior to the peak ER utilization).   

----- 

Now that I realize that you are estimating the TOTAL ER VISTS & ADMINS without regard to the Like Population.   I am not sure how you got those numbers.   But lets, think about how we could present the combined stress on the Health Care System.   
1) StackBar graph breaking out the 3 Age-Groups showing TOTAL VISITS
2) StackBar graph breaking out the 3 Age-Groups showing TOTAL ADMISSIONS
    (Not sure that you have the youngest for Admissions) 
My feeling is that NYC's younger demographic profile will make it hard to see elderly stress as an issue.  I don't believe there is obvious ER capacity definition, it would have to account for patient severity.  

It would be nice if we could apply a weighting based on age-group.   For example, a 75+ person most likely would require more attention.   The Admission number my be a good way to develop a weighting factor.

**Comment by briankoral713** [comment]
"Ok, the 100k view is more informative.
(Note: try to match your colors by Age-Group and the black background makes it hard to delineate colors, at least for us old-guys!)"

Sounds good, will do!

"The Older age group 65+ are presenting at MUCH higher numbers with greater severity!! Very bad!!"

Yes - agreed!  That is what I noticed immediately. 

"By the way, I notice that you did not break out the young-retired(65-74) from the old-retired (75+). My concern with the young-retired is that they may exposed themselves more than the old-retired to the virus by being out-and-about."

Fair points!  I lumped them together because I did not see a 65 year old being much different than a 75+ (no offense here!!).  They seem to follow a similar trend so I thought it better to simply add them together, but I do see your point!

"Looking at the NYC-DOHMH ER-Visits PDF you can see the age-groups showing the wave, younger to older groups. Surprisingly starting with the youngest group (FIFO)."

Indeed!  Something I did not see before - there is definitely a wave beginning with the youngest age group. 

"Now that I realize that you are estimating the TOTAL ER VISTS & ADMINS without regard to the Like Population. I am not sure how you got those numbers. But lets, think about how we could present the combined stress on the Health Care System."

I just added the respective totals after de-standardizing them from "per 100k" - the population by age group is from the CUNY Baruch link above.  

Thanks again!

**Comment by DTPOTO** [comment]
@briankoral713 have you seen https://www1.nyc.gov/site/doh/covid/covid-19-goals.page 
The hospital admission goals looks like a good read on system stress.   I think you ware on to something with your ER visits/Admins comparisons by Age Group (Flue/Pneumonia symptoms).   How do the DOH Covid-19 Hospitalizations line up with your assessment?   If I recall right we were seeing an Age-Progression vs what the DOH is showing a total Unit decrease.   I think this may be in agreement.
