### ISSUE TITLE
Publish borough level breakdown

### ISSUE THREAD

**Issue by jqnatividad** [nychealth/coronavirus-data#3]
Can the data be broken down to the borough level?

Interestingly, USAFacts is publishing confirmed and deaths down to the borough level, which even the NYTimes COVID19 repo nor the JHU COVID19 repo does not do.

https://usafacts.org/visualizations/coronavirus-covid-19-spread-map/

Where do they get the borough breakdowns if not NYCDOMH, which they list as one of their sources?

With the USAFacts data, I was able to pull together this quick boro-level viz using Google Colab
https://colab.research.google.com/drive/17-g0CIG57q13S4p26r6NpCFTLSYA1mBn

**Comment by danielw2904** [comment]
The data is available in the daily summary. The internat archive has data starting March 17 (March 19 first snapshot). However, it would be great to have that further back 

https://web.archive.org/web/*/https://www1.nyc.gov/assets/doh/downloads/pdf/imm/covid-19-daily-data-summary.pdf

**Comment by chazeon** [comment]
I have been tracking it from PDF they are publishing for some time, see here:
https://github.com/chazeon/NYState-COVID-19-Tracker/blob/master/data/NYC-covid-19-daily-data-summary.csv
https://github.com/chazeon/NYState-COVID-19-Tracker/blob/master/data/NYC-covid-19-daily-data-summary-deaths.csv

**Comment by chazeon** [comment]
Also, hospitalizations: https://github.com/chazeon/NYState-COVID-19-Tracker/blob/master/data/NYC-covid-19-daily-data-summary-hospitalizations.csv

**Comment by extremeheat** [comment]
Working on a viz right now, and this would be very helpful. Right now we can visualize by ZIP-code for positive cases, but data on deaths by borough (or even zip if possible) would be nice to have. And that can be used to extrapolate recoveries too.

![image](https://user-images.githubusercontent.com/13713600/78308760-5476f080-7517-11ea-9238-69d137a05528.png)
