### ISSUE TITLE
Current Hospitalizations

### ISSUE THREAD

**Issue by mattdatajourno** [nychealth/coronavirus-data#34]
Is it possible to report the current hospitalizations each day as opposed to the "ever hospitalized?" The current hospitalizations are what all other NY jurisdictions are reporting, apparently from HERD.

**Comment by mmontesanonyc** [comment]
We are reporting the number of admissions each day. In order to know the number of currently hospitalized, we would need to know how many discharges have occurred. Unfortunately we have not received complete data on hospital discharges at this time.
