### ISSUE TITLE
zip code data not updated

### ISSUE THREAD

**Issue by andrewmartini** [nychealth/coronavirus-data#36]
First off, thank you for providing this data. I started looking at the data just a few days ago, and I noticed that the test-by-zcta.csv  file has been the same for the past 3 days (with a total number of cases standing at 94,499 for the city.  Is this data being updated?

**Comment by extremeheat** [comment]
@mmontesanonyc ZIP data out of date again.

Needed to update -> http://covid.realtime.nyc/#mode=usa-nyc-latest
