### ISSUE TITLE
testing.csv file?

### ISSUE THREAD

**Issue by mizmee** [nychealth/coronavirus-data#38]
Hi,

Readme says that there should be a file called testing.csv, which is supposed to include "counts of New York City residents with specimens collected for SARS-CoV-2 testing by day, the subsets who tested positive as confirmed COVID-19 cases, were ever hospitalized, and who died."
 
Will that be posted soon? Also, last week the mayor was promising a count of people admitted into the ICU as well has being hospitalized.  Will that be in that file?

Thanks,

**Comment by rak5381** [comment]
That file is no longer kept here, but the data is available from the state by county at https://health.data.ny.gov/Health/New-York-State-Statewide-COVID-19-Testing/xdss-u53e 

Note that this is data for persons tested on a date, not specimens tested. Also note that if a person is tested on multiple occasions they will appear as multiple tests.

**Comment by mizmee** [comment]
Great. Thanks for the info. Best, Mike

    On Tuesday, April 14, 2020, 2:55:56 AM EDT, rak5381 <notifications@github.com> wrote:  
 
 


That file is no longer kept here, but the data is available from the state by county at https://health.data.ny.gov/Health/New-York-State-Statewide-COVID-19-Testing/xdss-u53e

Note that this is data for persons tested on a date, not specimens tested. Also note that if a person is tested on multiple occasions they will appear as multiple tests.
