### ISSUE TITLE
Recovery Data

### ISSUE THREAD

**Issue by jwlbjtu** [nychealth/coronavirus-data#39]
First I want to thank you for this great effort of providing this data. It is very helpful and critical. 

Them I just curious, are there any data about the recovered cases in NYC? Since the outbreak has been about one month long, are there any recoveries cases? 

Thanks.

**Comment by extremeheat** [comment]
Most people recover at home under the radar, so there's no way to get a really good number. Most people recover in 2 weeks or less, and those that don't die so you can use that flow of logic to get a rough estimate of recoveries. Not a statistically meaningful number but it can be extrapolated if you need it.
