### ISSUE TITLE
Raw data

### ISSUE THREAD

**Issue by abrahams1** [nychealth/coronavirus-data#4]
Does anyone have the raw data grabs from the PDF's published for data older than March 31? This is what I have from pdf's but wanted the historical breakdowns starting March 1st.

Borough | Cases | Hospitalized | Deaths | DateTime
-- | -- | -- | -- | --
Bronx | 1071 |   |   | March 21, 2020 5:00PM
Brooklyn | 2484 |   |   | March 21, 2020 5:00PM
Manhattan | 1863 |   |   | March 21, 2020 5:00PM
Queens | 2254 |   |   | March 21, 2020 5:00PM
Staten Island | 437 |   |   | March 21, 2020 5:00PM
Unknown | 5 |   |   | March 21, 2020 5:00PM
Bronx | 1829 |   |   | March 23, 2020 9:30PM
Brooklyn | 3494 |   |   | March 23, 2020 9:30PM
Manhattan | 2572 |   |   | March 23, 2020 9:30PM
Queens | 3621 |   |   | March 23, 2020 9:30PM
Staten Island | 817 |   |   | March 23, 2020 9:30PM
Unknown | 6 |   |   | March 23, 2020 9:30PM
Bronx | 2328 |   |   | March 24, 2020 9:30PM
Brooklyn | 4237 |   |   | March 24, 2020 9:30PM
Manhattan | 2887 |   |   | March 24, 2020 9:30PM
Queens | 4364 |   |   | March 24, 2020 9:30PM
Staten Island | 953 |   |   | March 24, 2020 9:30PM
Unknown | 7 |   |   | March 24, 2020 9:30PM
Bronx | 3924 | 1071 |   | March 26, 2020 9:30PM
Brooklyn | 5705 | 968 |   | March 26, 2020 9:30PM
Manhattan | 3907 | 729 |   | March 26, 2020 9:30PM
Queens | 7026 | 1659 |   | March 26, 2020 9:30PM
Staten Island | 1276 | 283 |   | March 26, 2020 9:30PM
Unknown | 35 | 10 |   | March 26, 2020 9:30PM
Bronx | 4880 | 1200 | 79 | March 27, 2020 4:00PM
Brooklyn | 7091 | 989 | 82 | March 27, 2020 4:00PM
Manhattan | 4627 | 709 | 55 | March 27, 2020 4:00PM
Queens | 8529 | 1810 | 124 | March 27, 2020 4:00PM
Staten Island | 1534 | 321 | 26 | March 27, 2020 4:00PM
Unknown | 36 | 10 |   | March 27, 2020 4:00PM
Bronx | 5352 |   | 110 | March 28, 2020 10:00AM
Brooklyn | 7789 |   | 118 | March 28, 2020 10:00AM
Manhattan | 5036 |   | 79 | March 28, 2020 10:00AM
Queens | 9228 |   | 174 | March 28, 2020 10:00AM
Staten Island | 1718 |   | 36 | March 28, 2020 10:00AM
Unknown | 35 |   |   | March 28, 2020 10:00AM
Bronx | 6250 | 1729 | 153 | March 29, 2020 10:00AM
Brooklyn | 8887 | 1617 | 168 | March 29, 2020 10:00AM
Manhattan | 5582 | 1074 | 94 | March 29, 2020 10:00AM
Queens | 10737 | 2536 | 219 | March 29, 2020 10:00AM
Staten Island | 1984 | 444 | 43 | March 29, 2020 10:00AM
Unknown | 35 | 10 | 1 | March 29, 2020 10:00AM
Bronx | 6925 | 1880 | 215 | March 30, 2020 5:00PM
Brooklyn | 10171 | 1661 | 216 | March 30, 2020 5:00PM
Manhattan | 6060 | 1075 | 119 | March 30, 2020 5:00PM
Queens | 12756 | 2650 | 305 | March 30, 2020 5:00PM
Staten Island | 2140 | 465 | 58 | March 30, 2020 5:00PM
Unknown | 35 | 10 | 1 | March 30, 2020 5:00PM
Bronx | 7815 | 2056 | 262 | March 31, 2020 5:00PM
Brooklyn | 11160 | 1901 | 261 | March 31, 2020 5:00PM
Manhattan | 6538 | 1130 | 129 | March 31, 2020 5:00PM
Queens | 13869 | 2954 | 376 | March 31, 2020 5:00PM
Staten Island | 2354 | 499 | 67 | March 31, 2020 5:00PM
Unknown | 35 | 9 | 1 | March 31, 2020 5:00PM

NYCAgeRange | Cases | Hospitalized | Deaths | DateTime
-- | -- | -- | -- | --
0 to 17 | 323 |   |   | March 23, 2020 9:00AM
18 to 44 | 5704 |   |   | March 23, 2020 9:00AM
45 to 64 | 4069 |   |   | March 23, 2020 9:00AM
65 to 74 | 1308 |   |   | March 23, 2020 9:00AM
75 > | 930 |   |   | March 23, 2020 9:00AM
Unknown | 5 |   |   | March 23, 2020 9:00AM
0 to 17 | 374 |   |   | March 24, 2020 10:00AM
18 to 44 | 6786 |   |   | March 24, 2020 10:00AM
45 to 64 | 4906 |   |   | March 24, 2020 10:00AM
65 to 74 | 1591 |   |   | March 24, 2020 10:00AM
75 > | 1109 |   |   | March 24, 2020 10:00AM
Unknown | 10 |   |   | March 24, 2020 10:00AM
0 to 17 | 446 |   |   | March 25, 2020 10:00AM
18 to 44 | 8880 |   |   | March 25, 2020 10:00AM
45 to 64 | 6786 |   |   | March 25, 2020 10:00AM
65 to 74 | 2226 |   |   | March 25, 2020 10:00AM
75 > | 1633 |   |   | March 25, 2020 10:00AM
Unknown | 40 |   |   | March 25, 2020 10:00AM
0 to 17 | 495 | 46 |   | March 26, 2020 5:00PM
18 to 44 | 10145 | 950 |   | March 26, 2020 5:00PM
45 to 64 | 7869 | 1749 |   | March 26, 2020 5:00PM
65 to 74 | 2627 | 946 |   | March 26, 2020 5:00PM
75 > | 1935 | 1029 |   | March 26, 2020 5:00PM
Unknown | 41 | 0 |   | March 26, 2020 5:00PM
0 to 17 | 543 | 47 | 0 | March 27, 2020 4:00PM
18 to 44 | 11617 | 971 | 16 | March 27, 2020 4:00PM
45 to 64 | 9158 | 1886 | 78 | March 27, 2020 4:00PM
65 to 74 | 3034 | 1032 | 90 | March 27, 2020 4:00PM
75 > | 2286 | 1103 | 182 | March 27, 2020 4:00PM
Unknown | 67 | 0 |   | March 27, 2020 4:00PM
0 to 17 | 573 |   | 0 | March 28, 2020 9:00AM
18 to 44 | 12590 |   | 22 | March 28, 2020 9:00AM
45 to 64 | 10019 |   | 125 | March 28, 2020 9:00AM
65 to 74 | 3354 |   | 120 | March 28, 2020 9:00AM
75 > | 2568 |   | 249 | March 28, 2020 9:00AM
Unknown | 54 |   | 1 | March 28, 2020 9:00AM
0 to 17 | 619 | 67 | 0 | March 29, 2020 10:00AM
18 to 44 | 14233 | 1459 | 33 | March 29, 2020 10:00AM
45 to 64 | 11577 | 2765 | 162 | March 29, 2020 10:00AM
65 to 74 | 3954 | 1499 | 159 | March 29, 2020 10:00AM
75 > | 3020 | 1620 | 324 | March 29, 2020 10:00AM
Unknown | 71 | 0 |   | March 29, 2020 10:00AM
0 to 17 | 714 | 72 | 1 | March 30, 2020 5:00PM
18 to 44 | 16028 | 1448 | 54 | March 30, 2020 5:00PM
45 to 64 | 13344 | 2887 | 216 | March 30, 2020 5:00PM
65 to 74 | 4496 | 1612 | 215 | March 30, 2020 5:00PM
75 > | 3410 | 1722 | 428 | March 30, 2020 5:00PM
Unknown | 95 | 0 |   | March 30, 2020 5:00PM
0 to 17 | 757 | 74 | 1 | March 31, 2020 5:00PM
18 to 44 | 17347 | 1532 | 67 | March 31, 2020 5:00PM
45 to 64 | 14689 | 3195 | 259 | March 31, 2020 5:00PM
65 to 74 | 5015 | 1826 | 255 | March 31, 2020 5:00PM
75 > | 3866 | 1922 | 514 | March 31, 2020 5:00PM
Unknown | 97 | 0 |   | March 31, 2020 5:00PM

NYCAgeSex | Cases | Hospitalized | Deaths | DateTime
-- | -- | -- | -- | --
Female | 3318 |   |   | March 21, 2020 5:00PM
Male | 4787 |   |   | March 21, 2020 5:00PM
Unknown | 10 |   |   | March 21, 2020 5:00PM
Female | 5255 |   |   | March 23, 2020 9:00AM
Male | 7097 |   |   | March 23, 2020 9:00AM
Unknown | 17 |   |   | March 23, 2020 9:00AM
Female | 6374 |   |   | March 24, 2020 10:00AM
Male | 8379 |   |   | March 24, 2020 10:00AM
Unknown | 23 |   |   | March 24, 2020 10:00AM
Female | 8655 |   |   | March 25, 2020 10:00AM
Male | 11325 |   |   | March 25, 2020 10:00AM
Unknown | 31 |   |   | March 25, 2020 10:00AM
Female | 10124 | 1918 |   | March 26, 2020 5:00PM
Male | 12948 | 2801 |   | March 26, 2020 5:00PM
Unknown | 40 | 1 |   | March 26, 2020 5:00PM
Female | 11250 |   | 151 | March 27, 2020 10:00AM
Male | 14279 |   | 215 | March 27, 2020 10:00AM
Unknown | 44 |   |   | March 27, 2020 10:00AM
Female | 12928 |   | 206 | March 28, 2020 10:00AM
Male | 16192 |   | 311 | March 28, 2020 10:00AM
Unknown | 38 |   |   | March 28, 2020 10:00AM
Female | 14837 | 3001 | 264 | March 29, 2020 10:00AM
Male | 18593 | 4408 | 414 | March 29, 2020 10:00AM
Unknown | 44 | 1 |   | March 29, 2020 10:00AM
Female | 16920 | 3130 | 334 | March 30, 2020 5:00PM
Male | 21120 | 4610 | 569 | March 30, 2020 5:00PM
Unknown | 47 | 1 | 1 | March 30, 2020 5:00PM
Female | 18677 | 3455 | 401 | March 31, 2020 5:00PM
Male | 23043 | 5093 | 694 | March 31, 2020 5:00PM
Unknown | 51 | 1 | 1 | March 31, 2020 5:00PM

**Comment by chazeon** [comment]
Please find at my repo:
https://github.com/chazeon/NYState-COVID-19-Tracker

**Comment by chazeon** [comment]
See documents for original pdf, CSV in data directory
I haven’t put up hospitalization data yet but that would be a few minutes’ work.

**Comment by dbathgate** [comment]
I built out a dashboard in Grafana showing real time historical data for NY.
https://drb-corona.apps.pcfone.io/d/OFmA529Zz/covid-19-cases-in-ny

I also have an API if you want the raw data from the database:
https://corona-ny-api.apps.pcfone.io/
