### ISSUE TITLE
Today's (4/13) case/hospitalization/death count not properly updated

### ISSUE THREAD

**Issue by cgseife** [nychealth/coronavirus-data#40]
Hello...

Thanks much for posting this data. It's an important resource.

Today's (early) update of case-hosp-death.csv has an updated count of cases, but neither hospitalizations nor deaths are updated -- they match yesterday's numbers. Similarly, the death/hosp numbers on the official NYCDOHMH data page are not updated, even though cases are.

Thanks for your attention!

--Charles Seife

**Comment by briankoral713** [comment]
Agreed they put this up way earlier than usual..

**Comment by cgseife** [comment]
3/14 update is almost what the 3/13 update should have been; however, hospitalizations still not updated.

**Comment by cgseife** [comment]
Closing this issue; updates have resumed, albeit with a discontinuity caused by the hiccup.
