### ISSUE TITLE
Hospital Cases Discharged

### ISSUE THREAD

**Issue by jboresta** [nychealth/coronavirus-data#42]
Can the summary file including new cases, hospitalizations and deaths by date be enhanced to include a subset of the hospitalized column providing a count of cases that recovered and were released ?

**Comment by mmontesanonyc** [comment]
Unfortunately we have not received complete data on hospital discharges at this time, so this is not something we can include.

**Comment by jboresta** [comment]
?Ok. Thanks.


John L. Boresta, M.P.A.

Correctional Health Services

Associate Staff Analyst

NYC Health and Hospitals Corporation

Cube 18-141

55 Water St.

New York, N.Y. 10041

jboresta@nychhc.org<mailto:jboresta@nychhc.org>

(646) 614-0045

 "Each problem that I solved became a rule, which served afterwards to solve other problems" Rene Descartes

________________________________
