### ISSUE TITLE
So much fluctuation in cases, hospitalizations and deaths today

### ISSUE THREAD

**Issue by KnitAndTheCity** [nychealth/coronavirus-data#45]
Hello - I track the numbers daily and keep them for review. The differences between the cases-hosp-death file currently posted and the one from yesterday is quite substantial. For example - March 20 has been hovering around 3600-3900 cases since I started tracking on March 31. However, in today's file - they are now at 2594. In total - the number of positive cases for the day nets to be 3420 more since yesterday - which seems directionally correct. But the day by day numbers are way different. Any ideas?

**Comment by mmontesanonyc** [comment]
The number of cases diagnosed for 3/20 ([as posted on 4/19](https://github.com/nychealth/coronavirus-data/commit/498c34f8534bc865b15dd09e9b560bd457ef5b9b)) was 3959. There may be an error in your documentation.
