### ISSUE TITLE
zip data vs cases file

### ISSUE THREAD

**Issue by KnitAndTheCity** [nychealth/coronavirus-data#46]
I've noticed the total number of positives in the zip file (132,001) does not match the total number of cases in the cases-hosp-death file (129,786). Any reason for that? I would think they would be the same.

**Comment by mmontesanonyc** [comment]
Currently, the data for ZIP codes and the epi curves are 'cut' at slightly different times, resulting in occasional small discrepancies that are consistent with efforts to unite data from several different sources.
