### ISSUE TITLE
tests-by-zcts.csv data issue

### ISSUE THREAD

**Issue by stephenpace-sfc** [nychealth/coronavirus-data#48]
Data quality question on tests-by-zcts.csv (cumulative count of New York City residents by ZIP code of residence):

What does it mean if MODZCTA is NA? Does this just mean you don't know their ZIP code but they are still a New York resident? Can we assume that all of these people live in New York if we are mapping these ZIPs to geography?

**Comment by mmontesanonyc** [comment]
Per [Readme](https://github.com/nychealth/coronavirus-data), data by zcta are for NYC residents.  NA values are for individuals where ZCTA is not known because of incomplete address information.
