### ISSUE TITLE
NY city zcta shape files

### ISSUE THREAD

**Issue by ParamjitGill** [nychealth/coronavirus-data#49]
How many Zip code (zcta) areas are in the NY city? Corona virus data are posted for 177 zcta areas here. Does any one have the shape files for these 177 zip codes or knows where to get these?  I have two different shape files: one with 200 and the other with 214 zipcode areas but those don't have some of the 177 zcta areas for which we have the corona virus data.

**Comment by double-dose-larry** [comment]
Not all zip codes have people

**Comment by LilySu** [comment]
@ParamjitGill you can easily find the shp files in the nyc open data portal, but here it is: https://github.com/LilySu/Covid-19nyc/tree/master/nyc_geojson
It seems to be missing a few places like Red Hook, Fire Island, an area in the Bronx, and the Rockaways, you can view here: https://colab.research.google.com/drive/1r7nK5G1OxIQkToU4KMhOeGA_9J_70MKQ
