### ISSUE TITLE
COVID-19 Deaths by NYC Zip Code

### ISSUE THREAD

**Issue by deverreaux137** [nychealth/coronavirus-data#51]
Is there any way to modify the tests-by-zcta file to include confirmed deaths by zip code? It would be helpful to know the confirmed death rate alongside the positive test rate. If not, where might I find this data (whether as a GitHub project or other form)? Thanks!

**Comment by cgseife** [comment]
Seconded.... especially retrospectively, deaths will be much more useful to understand the dynamics of the epidemic than "cases" will be.
