### ISSUE TITLE
Discrepancy with Daily Data Summary: Total Cases

### ISSUE THREAD

**Issue by duncanslp** [nychealth/coronavirus-data#53]
Hi, thanks so much for making all these data available. How is "diagnosis date" defined (i.e., from test administered vs results received)? I note that there is a considerable difference between the figures in case-hosp-death.csv and the daily differences between the nyc.gov Daily Data Summary: Total Cases pdfs. Wondering if this might be explained by case-hosp-death.csv using the testing date and Daily Data Summary: Total Cases pdfs using the results date. Any insight appreciated. Thanks again.

**Comment by mmontesanonyc** [comment]
Diagnosis date is the date on which the specimen (swab) is collected. 

There are discrepancies between Daily Data Summary: Total Cases and case-hosp-death.csv for several reasons. 

First, the former shows cumulative counts and the latter shows daily counts. Secondly, the Daily Data Summary displays data by report date (when the Health Department learned about it), which is impacted by reporting lags. Diagnosis date is more reflective of when people are getting sick and being tested.  The reporting date may be delayed compared to diagnosis date — information about cases over the previous week will be incomplete until the laboratories and hospitals report the results for people who were tested to us, which can take a few days to a week.
