### ISSUE TITLE
Lack of metadata

### ISSUE THREAD

**Issue by natschil** [nychealth/coronavirus-data#54]
There is currently a substantial lack of metadata regarding what the numbers in this database actually represent. For example, what is the denominator for DEATH_RATE in by-age.csv? Is it confirmed positive cases in that age bracket, or is it total population?

**Comment by mmontesanonyc** [comment]
Per Readme, rates are per 100,000 people, not per 100,000 cases.

**Comment by natschil** [comment]
Sure, but each case is a person, so saying 100,000 people doesn't really clarify things. So are these 100k people 100k people of arbitrary age, or are these 100,000 people in that age group?

**Comment by mmontesanonyc** [comment]
Age-specific rates are per 100,000 people who live in NYC in that age group. So the rate of death among 75+ (1,045/100,000) indicates that there are 1,045 deaths for every 100,000 New Yorkers who are aged 75+.

**Comment by natschil** [comment]
That additional information makes the statistic understandable, thanks. I'm guessing that HOSPITALIZED_RATE should be interpreted in the same way?

Note that I'm not raising this issue just for myself, but to point out that I think the way they are conveyed on github (outside of this issue) makes it challenging for scientists/members of the public/media to understand what the numbers actually refer to.
