### ISSUE TITLE
why age group is so weird?

### ISSUE THREAD

**Issue by jackzhp** [nychealth/coronavirus-data#60]
0–17
18–44
45–64
65–74
75+

why can not be 0-9,10-19, 20-29 etc?

the state wide fatality data https://covid19tracker.health.ny.gov/views/NYS-COVID19-Tracker/NYSDOHCOVID-19Tracker-Fatalities?%3Aembed=yes&%3Atoolbar=no&%3Atabs=n
is with 0-9,10-19, etc.

but I can not find the case data by age group, I want to calculate CFR (https://en.wikipedia.org/wiki/Case_fatality_rate).

**Comment by mmontesanonyc** [comment]
We are reporting out data for these age groups because COVID-19 trends were similar within the specified groups. That is, there are more noteworthy differences between these age groups than within them.
