### ISSUE TITLE
sex x age breakdown

### ISSUE THREAD

**Issue by wyesoslo** [nychealth/coronavirus-data#62]
Is it possible to get a sex x age breakdown?  Other data sources have suggested that the female advantage only holds for 60+ years (or perhaps 70+ years) and is reversed for younger ages.

**Comment by mmontesanonyc** [comment]
Hello, thanks for the question. We are closing this old issue since these data aren’t available in this repository, and though it's helpful to see what data people are interested in, we are not able to field custom data requests through Github.
