### ISSUE TITLE
The 5-12 update has missing zips

### ISSUE THREAD

**Issue by zmgcohen** [nychealth/coronavirus-data#65]
These are cumulative so any zip code that has been present in past data sets should be included in this one.

Looks like the following are missing:
11371
11359
11430
11040
11001
11003

are missing. Thanks for maintaining this set, it's been invaluable.

**Comment by mmontesanonyc** [comment]
These ZIPs have not been included in our past datasets. 

We are reporting these data by modified ZCTA (ZIP Code Tabulation Area). For several reasons, there are fewer ZCTAs than ZIP Codes. For example, 11371 is the ZIP code for La Guardia Airport; and 11040 includes part of Queens as well as part of Nassau County. 

You can get more information about the difference between ZIP Codes, ZIP Code Tabulation Areas, and modified ZCTAs at [geography-resources](https://github.com/nychealth/coronavirus-data/tree/master/Geography-resources).
