### ISSUE TITLE
Hospital deaths?

### ISSUE THREAD

**Issue by kristinwd** [nychealth/coronavirus-data#66]
Can anyone confirm that the deaths in this table are 'all reported NYC deaths', or only reported 'hospital deaths'?

The reported case counts from all three organizations will not match because of different data sources and cleaning procedures.

_Originally posted by @mmontesanonyc in https://github.com/nychealth/coronavirus-data/issues/27#issuecomment-611544092_

**Comment by mmontesanonyc** [comment]
Unless specified as being for "probable COVID-19 deaths," data in this repository are "confirmed COVID-19 deaths": deaths among NYC residents who had a positive laboratory test for COVID-19, regardless of hospitalization status.
