### ISSUE TITLE
Missing ZIP code: 11249

### ISSUE THREAD

**Issue by penguinland** [nychealth/coronavirus-data#67]
`tests-by-zcta.csv` does not contain data for ZIP code 11249 (western Williamsburg, right on the East River). Any chance that can be added in? 

Thanks for the data! Keep up the good work.

**Comment by mmontesanonyc** [comment]
We report data using ZIP Code Tabulation Areas (ZCTAs). 

ZCTAs were created for the 2010 census. The 11249 ZIP was created in late 2011, when 11211 was split into 11211 and 11249. 

Tests for people in the ZIP Code 11249 are included in the ZCTA 11211.

**Comment by penguinland** [comment]
Thanks very much for explaining!
