### ISSUE TITLE
All CAUSE MORTALITY

### ISSUE THREAD

**Issue by tylermcclellan450** [nychealth/coronavirus-data#68]
Will the Deaths not known to be associated with COVID (either probably or confirmed) now now longer be reported?

Does that mean one will have to glean said data from the CDC instead?

and on the question of the CDC, can you confirm the timeframe over which their data converges with yours? My understanding is that the data is all self-reported so that other than lags, eventually what the CDC shows for all cause mortality by week should be exactly equal to what the NYC health data shows. Is this understanding correct?

thanks for all the good work.

**Comment by mmontesanonyc** [comment]
Unfortunately we are no longer able to provide these data. But yes, you can use the CDC as a source for NYC's all-cause mortality data.
