### ISSUE TITLE
Timeseries data for COVID-19 cases by patient ZIP code

### ISSUE THREAD

**Issue by thiagoghisi** [nychealth/coronavirus-data#7]
Would it be possible to release a cumulative time-series historical data for the following CSV: 

https://github.com/nychealth/coronavirus-data/blob/master/tests-by-zcta.csv

```
DATE,ZIPCODE,CONFIRMED,HOSPITALIZED,DEATHS
2020-01-21,10001,1,0,0
2020-01-22,10001,2,1,0
2020-01-23,10001,3,1,1
...
2020-04-01,10001,265,59,33
```

**Comment by DnSu** [comment]
if this is not possible, at least put extraction timestamp on all data. this one someone who is poling this data regularly can build their own time series. Right now the only way to tell the date of some of this data is through commit history on github.

**Comment by DnSu** [comment]
@thiagoghisi nytimes has time-series https://github.com/nytimes/covid-19-data

**Comment by jqnatividad** [comment]
Also, it'd be great if you can post historical data zipcode data as well.

In the NYTimes article https://www.nytimes.com/interactive/2020/04/01/nyregion/nyc-coronavirus-cases-map.html, they had data predating April 1st, and they cite NYCDOMH as their source.

In addition, a breakdown by community board would be awesome as well!

**Comment by akilism** [comment]
+1 on the time series data by zip code.

**Comment by mjjohns1** [comment]
Time series data by zip code is too granular for public release. Data at such a small scale would make it possible to re-identify people, violating basic standards for handling protected health information. It's unlikely DOHMH would ever do such an irresponsible thing.

**Comment by extremeheat** [comment]
@mjjohns1 NYC is very dense and provide data by ZIP-code isn't as granular as you think. Providing data like that helps get an important idea of how the virus spread in NYC, which is not a very accurate representation (does not account for people who were positive but never tested) but it is a representation which is better than nothing. It can already be done as-is from a current reference point. Proving data by ZIP in NYC is similar to proving data by county in some parts of the US because of density. We just want the data prior to when the repo came live.

**Comment by akilism** [comment]
wrote a little node script to compile the zcta testing data into one csv. you'll have to rewind this repos history to get the previous day's data but should work nicely moving forward.

https://github.com/akilism/compile-city-covid

**Comment by jqnatividad** [comment]
Thanks @akilism !

I went ahead and used your utility and compile the data, publish and maintain it at

https://data.beta.nyc/dataset/nyc-covid-19-tests-by-zipcode-time-series

I went ahead and use the compiled data and used it in this dashboard -

https://data.beta.nyc/dataset/nyc-covid-19-tests-by-zipcode-time-series

**Comment by thiagoghisi** [comment]
That is amazing @jqnatividad and @akilism! Thanks so much for putting this together and for sharing it here.

![image](https://user-images.githubusercontent.com/270128/79858609-af289d00-839d-11ea-975c-6a71b72a206a.png)


![image](https://user-images.githubusercontent.com/270128/79858698-d1221f80-839d-11ea-9831-ddf52603b3e1.png)

I'm closing this issue now.

**Comment by thiagoghisi** [comment]
Before I close this, for future reference, I also found this incredible work by @chazeon on https://github.com/chazeon/NYState-COVID-19-Tracker that is pretty much doing what I was originally hoping for. It's being updated daily for the past month.

The timeseries dataset for COVID-19 cases by patient ZIP code for NYC is available here: 

https://github.com/chazeon/NYState-COVID-19-Tracker/blob/master/data/NYC-github-coronavirus-data-tests-by-zcta.csv

**Comment by mmontesanonyc** [comment]
> Time series data by zip code is too granular for public release. Data at such a small scale would make it possible to re-identify people, violating basic standards for handling protected health information. It's unlikely DOHMH would ever do such an irresponsible thing.

Indeed - to protect patient privacy, we are not yet prepared to release data at this granularity.

**Comment by jqnatividad** [comment]
Thanks @thiagoghisi 
Speaking of time-series data, you may want to check out the R<sub>t</sub> charts on the dashboard.

![Screenshot from 2020-04-22 15-45-49](https://user-images.githubusercontent.com/1980690/80027045-21d66d00-84b1-11ea-930c-3bb520e07d88.png)

https://data.beta.nyc/pages/nyc-covid19#rtbm

I was inspired by what @k-sys did with https://rt.live, and computed R<sub>t</sub> on a borough level.

Currently investigating doing it too at the zipcode level in NYC, now that we have the data...
