### ISSUE TITLE
Deaths with Pre-existing conditions by type?

### ISSUE THREAD

**Issue by debstersocal** [nychealth/coronavirus-data#70]
Is there any chance of getting the deaths with a pre-existing condition by type(s) of condition or illness?   Or maybe a breakout of how many, 1, 2-3, 4+?   
Research project for GWU.

**Comment by debstersocal** [comment]
Example:  CDC data has cateogies.
https://data.cdc.gov/NCHS/Conditions-contributing-to-deaths-involving-corona/hk9y-quqm

**Comment by mmontesanonyc** [comment]
Unfortunately we are not able to provide that information at this time.
