### ISSUE TITLE
Population Estimate Sources and Methods? 

### ISSUE THREAD

**Issue by jpfreeley** [nychealth/coronavirus-data#72]
Can you please post link to "intercensal estimates by the Bureau of Epidemiology Services" (README.md - line 166)? 

Does that above differ from "interpolated intercensal population estimates updated in 2019" (README.md - line 50)? If so, please post link. 

Can you describe the DOH's method of producing "these population estimates based on estimates from the U.S. Census Bureau and NYC Department of City Planning" (README.md - line 50)?

The population numbers seem to differ from US Census ACS-5 2018 Data. https://api.census.gov/data/2018/acs/acs5.html

**Comment by mmontesanonyc** [comment]
No, these two don’t differ - each time we calculate a rate we use a denominator from the Health Department’s methods for estimating populations.

Yes, our population numbers differ from ACS data. To better allocate populations in areas with large amounts of new residential construction, we incorporate Certificate of Occupancy data into estimates. To account for undercounting in the 2010 Census in certain areas, one of our inputs includes NYC Department of City Planning Population Adjustments to the 2010 Census. 

Denominators for populations by modified ZIP code tabulation area are in the pop_denominator field of data-by-modzcta.csv.
