### ISSUE TITLE
Covid Deaths  (NYCHA)

### ISSUE THREAD

**Issue by DC1100** [nychealth/coronavirus-data#73]
Where can we find covid-19 deaths by NYCHA development?

Seeing articles mentioning DOH has published data on Monday with cases and deaths by development.

**Comment by ddlouise** [comment]
I would also like to know this. How do we get access to this data, if possible?

**Comment by mmontesanonyc** [comment]
Hello, thanks for the question. We are closing this old issue since these data aren’t available in this repository, and though it's helpful to see what data people are interested in, we are not able to field custom data requests through Github.
