### ISSUE TITLE
Historical "by-boro.csv"?

### ISSUE THREAD

**Issue by seeess1** [nychealth/coronavirus-data#74]
Can you add a historical file for by-boro.csv with a date column? That would be very helpful.

**Comment by mmontesanonyc** [comment]
Borough-specific daily counts of cases, hospitalizations, and deaths are available in [this file](https://github.com/nychealth/coronavirus-data/blob/master/boro/boroughs-case-hosp-death.csv).

**Comment by seeess1** [comment]
Thank you

**Comment by mmontesanonyc** [comment]
The daily counts are linked in my previous comment in this thread. Cumulative counts are [here](https://github.com/nychealth/coronavirus-data/blob/master/by-boro.csv).

**Comment by InformationForHumans** [comment]
Thank you @mmontesanonyc

**Comment by seijibk** [comment]
Am I correct that there is no way to see the cumulative total for two days ago, for example?

**Comment by Syi824** [comment]
Thank you @mmontesanonyc. Was looking for cumulative per day but will be able to create a new column for that.
