### ISSUE TITLE
History of probable deaths

### ISSUE THREAD

**Issue by bjudkewitz** [nychealth/coronavirus-data#77]
Please add a history of the probable deaths by day (and, if possible, by sex). The data seems to be available, since it is plotted on https://www1.nyc.gov/site/doh/covid/covid-19-data-deaths.page

**Comment by mmontesanonyc** [comment]
This file is [here](https://github.com/nychealth/coronavirus-data/blob/master/deaths/probable-confirmed-dod.csv).

**Comment by bjudkewitz** [comment]
Thanks! Does the data exist by sex?

**Comment by mmontesanonyc** [comment]
Yes, [here](https://github.com/nychealth/coronavirus-data/blob/master/deaths/probable-confirmed-by-sex.csv). Other data on probable and confirmed deaths are in files labeled "probable-confirmed" in the [deaths folder](https://github.com/nychealth/coronavirus-data/tree/master/deaths).

**Comment by bjudkewitz** [comment]
Sorry if I wasn't clear. That file lists the total counts by sex, but not as a function of time. I am looking for the daily probable death counts by sex.

**Comment by mmontesanonyc** [comment]
Unfortunately we are not able to provide that data at this time.
