### ISSUE TITLE
Cross-Tabs?

### ISSUE THREAD

**Issue by adp2020** [nychealth/coronavirus-data#79]
Apologies if i have missed it, but where are the data files that permit us to see the cross-tabbed results that were previously being released by the city, e.g. this breakdown that tracked deaths by age, sex, location, and underlying condition.

https://www1.nyc.gov/assets/doh/downloads/pdf/imm/covid-19-daily-data-summary-deaths-05042020-1.pdf

**Comment by mmontesanonyc** [comment]
Hello, thanks for the question. We are closing this old issue since these data aren’t available in this repository, and though it's helpful to see what data people are interested in, we are not able to field custom data requests through Github.
