### ISSUE TITLE
Deaths by Borough

### ISSUE THREAD

**Issue by laceyrkeller** [nychealth/coronavirus-data#8]
Please publish deaths and hospitalizations by borough, as it appears here: https://www1.nyc.gov/assets/doh/downloads/pdf/imm/covid-19-daily-data-summary-deaths.pdf

**Comment by ret394** [comment]
pdf links to https://www1.nyc.gov/site/doh/covid/covid-19-data.page#download

**Comment by albertc44** [comment]
I've been keeping track of all the data from the NYC Health PDFS here: https://coda.io/@atc/us-coronavirus-covid-19-2019-ncov-updates/new-york-city-38. There's a table at the bottom that let's you filter raw data by borough in a format that's good for a database or pivoting in Excel.
