### ISSUE TITLE
Underlying Conditions

### ISSUE THREAD

**Issue by matthewfienman** [nychealth/coronavirus-data#81]
I find the deaths by underlying conditions exhibit a good view.  Is there logic as to the underlying condition shareable.  Does the underlying data have a yes/no toggle for each of the conditions listed?  Is this coming solely from the Hospital Claim data.  Are there other factors (e.g. severity of the comorbidities?). Would be interesting to see this as a dataset to be worked with.

**Comment by PraesidiumOil** [comment]
I have been trying to find the case count by age group and underlying illness. Do you know where to find this? I have found for death count but not by confirmed case count?

**Comment by mmontesanonyc** [comment]
Data on underlying conditions comes to us as text and goes through a resource-intensive import and cleaning process to identify underlying conditions; assessing severity from these data is not possible.
