### ISSUE TITLE
Total hospitalizations on any given day

### ISSUE THREAD

**Issue by haldunanil** [nychealth/coronavirus-data#82]
It appears that the file here tracks the number of _new_ hospitalizations but not the total number of people at the hospital on any given day. Am I right on this? 
- If this is the case, is there another file in the repo that has the total hospitalizations information? 
- If not, can it be added?

**Comment by mmontesanonyc** [comment]
Correct, we are only showing the number of _admissions_ to the hospital per day. Our systems don’t provide reliable, timely information on hospital discharge status.

**Comment by haldunanil** [comment]
Understood. Is there any desire/plan to include gathering such information in the future?
