### ISSUE TITLE
5/25 Tests by zip - same data as 5/24 

### ISSUE THREAD

**Issue by johnvsantore** [nychealth/coronavirus-data#83]
Hello! It appears the tests by zip data for 5/25 is the same as for 5/24 - am I confused? 

Thanks for your help,
John

**Comment by ZackingIt** [comment]
John you are not confused the repo maintainer has clearly made an error

**Comment by johnvsantore** [comment]
Thanks, Zack - is there a way to notify the repo maintainer?
