### ISSUE TITLE
Confirmed Cases by Age and Underlying Illness vs No Underlying Illness

### ISSUE THREAD

**Issue by PraesidiumOil** [nychealth/coronavirus-data#84]
I am trying to find data on how many confirmed cases there have been by age group and by underlying illness or no underlying illness. There is good data on this for death count but not for cases. The goal is to attempt to project a fatality rate by age category with illness and without illness.

**Comment by mmontesanonyc** [comment]
Hello, thanks for the question. We are closing this old issue since these data aren’t available in this repository, and though it's helpful to see what data people are interested in, we are not able to field custom data requests through Github.
