### ISSUE TITLE
Case and death data by NTA, PUMA, or Community District

### ISSUE THREAD

**Issue by lblok** [nychealth/coronavirus-data#85]
Hi DOHMH, thank you **so** much for the work you've been doing to publish this data, and doing it so quickly. I heard you might be working on publishing the case and death data by Neighborhood Tabulation Area. I need to analyze it by community district or PUMA, and I learned that NTAs can be aggregated up to PUMAs, so that would be fine. Do you have an approximate timeline for publishing?

**Comment by gugmifrt** [comment]
Hi @lblok just wanted to follow up to see if you ever found a way to solve this. It's somewhat possible to mimic/piece together areas with census tract data e.g. https://censusreporter.org/profiles/14000US36061013700-census-tract-137-new-york-ny/ mapped to https://communityprofiles.planning.nyc.gov/manhattan/5 but open to error of course.

**Comment by lblok** [comment]
I submitted a request form to DOHMH for the data by community district and they sent it to me by email. I had to sign a data security agreement (even though community districts are a much larger geography than modified ZCTAs). Census tracts can be aggregated to PUMAs, which approximate community districts, but not sure how you're suggesting getting there from ZCTAs.

**Comment by gugmifrt** [comment]
Thank you! Is this the page you used to make that request or is there another?: https://www1.nyc.gov/site/doh/data/data-sets/data-requests-application-process-for-identifiable-vital-statistics-data.page

**Comment by lblok** [comment]
I did it via a contact who works there, but that looks like the right
place, or maybe this?
https://www1.nyc.gov/site/doh/data/data-sets/vs-data-req-form.page

Or maybe someone from the agency can respond here :)

**Comment by mmontesanonyc** [comment]
Hello, thanks for the question. We are closing this old issue since these data aren’t available in this repository, and though it's helpful to see what data people are interested in, we are not able to field custom data requests through Github.
