### ISSUE TITLE
Historical data-by-modzcta.csv

### ISSUE THREAD

**Issue by kmcguinness92** [nychealth/coronavirus-data#86]
Is there a way to access an older version of this -- like the data that was uploaded March 31 or another date?

Hoping to to do a comparison over time.

**Comment by seijibk** [comment]
+1

**Comment by mmontesanonyc** [comment]
Hello. We started producing this file on May 19 and are not able to provide a version of this file prior to that date.

**Comment by dmonopoly** [comment]
Yes, it seems not easy to get further historical data.

Some ideas:
It looks like there's more historical data on https://www1.nyc.gov/site/doh/covid/covid-19-data-archive.page, but it's less accurate. The pdfs only provide broad ranges of counts.

https://data.cityofnewyork.us/Health/Modified-Zip-Code-Tabulation-Areas-MODZCTA-/pri4-ifjk also may have some info but it wouldn't be easy to connect it smoothly to the current data.

**Comment by nittyjee** [comment]
What I'm seeing is that the first link only has pdfs by borough and the second link has MODZCTA data only for May 19th. Is that correct?
