### ISSUE TITLE
deaths by underlying condition

### ISSUE THREAD

**Issue by curieus** [nychealth/coronavirus-data#87]
can you clarify if underlying conditions are pre-existing conditions?  in another post, you refer to CDC classifications, but those relate to cause of death.   so, for example, ARDS can be something the CDC includes.  this is not a pre-existing condition, but rather a symptom of covid-19.

**Comment by mmontesanonyc** [comment]
Underlying conditions include lung disease, asthma, heart disease, a weakened immune system, obesity, diabetes, kidney disease, liver disease and cancer. These are not known to be symptoms of COVID-19.
