### ISSUE TITLE
Data on cases or tests by zcta (or modczta, zipcode or health dist) prior to 3/31/2020

### ISSUE THREAD

**Issue by fianchetto1** [nychealth/coronavirus-data#88]
I see that you have data on cases by borough back to 2/29/20. That would seem to imply you have some information on addresses back to that date. is there any way you can break down cases prior to 3/31/20 by a more detailed geographic descriptor? Health district? Zip code? ZCTA? Even if you can't produce a breakdown all the way back to the beginning of March, could you produce a breakdown by March 15? Thanks -- fianchetto1

**Comment by mmontesanonyc** [comment]
Hello, thanks for the question. We are closing this old issue since these data aren’t available in this repository, and though it's helpful to see what data people are interested in, we are not able to field custom data requests through Github.
