### ISSUE TITLE
data-by-modzcta - no new cases or deaths on 6/14?

### ISSUE THREAD

**Issue by svfnyc** [nychealth/coronavirus-data#89]
I've been tracking 3 nyc zip codes (10028, 10128, and 10029) and today's (6/14) data shows 0 new cases or deaths in all 3 zips since yesterday. Seems like a mistake given the recent trends. I do see a new numbers of tests so I know there was an update. Noticing last Sunday in those zip codes there were also no new cases - is there an issues getting case data on Sunday?

**Comment by mmontesanonyc** [comment]
As our daily counts decrease, more ZIPs will have 0 new deaths and 0 new cases on more days. This is not a mistake — just good news.
