### ISSUE TITLE
tests_by_zcta.csv using modified ZCTA's

### ISSUE THREAD

**Issue by buzaidj** [nychealth/coronavirus-data#90]
Was the now no longer updated tests_by_zcta.csv file using modified ZCTA's? A version from 7 days ago and an April 4th version I have saved only have data for 177 ZCTA's, but the crosswalk file ZCTA-to-MODZCTA.csv seems to indicate that there are 214 ZCTA's and 177 modified ZCTA's. Were some ZCTA's left out or were modified ZCTA's used all along?

**Comment by mmontesanonyc** [comment]
Yes, these were modified zctas.
