### ISSUE TITLE
Can I access all data updates? Time series?

### ISSUE THREAD

**Issue by nittyjee** [nychealth/coronavirus-data#91]
Hello - I'm looking through the history of csv files and only finding updates going back a few weeks. Can I access data for all updates? I want to create an animated map of how cases have changed. For now only doing total cases in zcta's.

It would be great to just have a time series csv to track case counts in each place.
We can potentially do it or help you with that, we'd just need the past data first, and then we can build code to automatically update going forward.

We're going to add it to out map here:
http://coronastate.org/

**Comment by nittyjee** [comment]
Oh, just saw this:
https://github.com/nychealth/coronavirus-data/issues/86

Is the file you started creating on May 19th available? I'm not seeing it.

**Comment by nittyjee** [comment]
One more thing - I do see that the historic files for tests by zcta were being updated from the beginning. That might work:
https://github.com/nychealth/coronavirus-data/blob/master/tests-by-zcta.csv

Of course I'd prefer to get them directly from the cases zcta. It seems more up to date anyway, at least right now.
https://github.com/nychealth/coronavirus-data/blob/master/data-by-modzcta.csv

In any case, we can create time series for all files, we'd just need the data.

**Comment by dmonopoly** [comment]
Let's consolidate discussion into #86 so if anyone wants to find a way they can.

This bug is a dupe of #86.

**Comment by nittyjee** [comment]
Totally agree, thanks.

**Comment by nittyjee** [comment]
> Totally agree, thanks.
