### ISSUE TITLE
Is the data in "data-by-modzcta.csv" indeed cumulative?

### ISSUE THREAD

**Issue by dmonopoly** [nychealth/coronavirus-data#92]
The README says "This file contains the following cumulative indicators by modified ZCTA..." currently for this csv file.

However, I found a drop in COVID_CASE_COUNT for zip code 10023 for these dates:

6/15: 567  ([link](https://github.com/nychealth/coronavirus-data/blob/8ebc7a35f37f2ed2310574ea5b2e4047163c8265/data-by-modzcta.csv))
6/16: 566 ([link](https://github.com/nychealth/coronavirus-data/blob/a86f0bf54cf761a0756e99d24fd037c04cb0a2ec/data-by-modzcta.csv))

which doesn't make sense.

Or is there inherent noise in these metrics?

**Comment by dmonopoly** [comment]
I noticed this issue for zip code 10001 between May 30 and May 31 as well: it drops by 1.

Btw, thank you very much for maintaining and updating this dataset.

**Comment by mmontesanonyc** [comment]
As records we receive get updated, de-duplicated or corrected, reported values may decrease or change. For example, a record may have an outdated address for somebody. When their record gets updated with their current address, the case is reassigned to their actual ZIP of residence — and the previous ZIP to which the case was assigned sees a drop of 1. As we mention, data are always preliminary and subject to change.

**Comment by dmonopoly** [comment]
Thanks for the clear answer.
