### ISSUE TITLE
case-hosp-death.csv date issue.

### ISSUE THREAD

**Issue by HarryBirtles** [nychealth/coronavirus-data#97]
The Date of Interest field appears to be by reported date in today's update (7/2) as it is now showing a weekly pattern (lower figures at the weekend) which wasn't previously there.

This is also the case in the boro/boroughs-case-hosp-death.csv file.

**Comment by mmontesanonyc** [comment]
No, we continue to report date of event, not date of report, for cases, hospitalizations, and deaths. The weekly pattern that appears in date of diagnosis (cases) reflects a known pattern of reduced healthcare-seeking behavior, and reduced operations (particularly among smaller clinics) on weekends.

**Comment by HarryBirtles** [comment]
Apologies, my mistake.  Thanks for your answer and ongoing work on this.
