### ISSUE TITLE
Probable and Confirmed Deaths by Borough and Date of Death

### ISSUE THREAD

**Issue by HarryBirtles** [nychealth/coronavirus-data#98]
Would it be possible to get Probable and Confirmed Deaths by Borough and Date of Death?  

This is available already for confirmed deaths through the boro/boroughs-case-hosp-death.csv file, but not for probable deaths.

Probably deaths are available by either borough, or date of death at the moment, but by both would allow us to see the complete picture for deaths by borough over time.

Many thanks,

Howard

**Comment by mmontesanonyc** [comment]
Hello, thanks for your request but we are unable to provide that at this time.

**Comment by HarryBirtles** [comment]
May I ask why you are unable to provide it?  

The data appears to be broken down by both in separate tables, so appears to be available in this granular format.
